### ISSUE TITLE
loadding的背景色不能修改

### ISSUE THREAD

**Issue by jingzhanwu** [fluttercandies/flutter_smart_dialog#1]
loadding框的背景色目前是黑色，是否可以提供对外设置的接口，或者背景修改为半透明

**Comment by CNAD666** [comment]
- 不好意思哈，刚看到，提的issue，github通知里面也不显示

showLoading这个调用loading弹窗的方法，loading已经`完善了相关设置参数`

- 请将版本更新到：flutter_smart_dialog: ^1.2.0
  - 然后运行：pub upgrade，pub get
- 设置loading颜色和透明度，可以向下面这样使用

```darty
SmartDialog.showLoading(
	maskColorTemp: Colors.blue.withOpacity(0.3),
);
```

**Comment by CNAD666** [comment]
> loadding框的背景色目前是黑色，是否可以提供对外设置的接口，或者背景修改为半透明

我去，你的意思是loading的背景

- api加了，更新下版本

```dart
flutter_smart_dialog: ^1.2.1
```

- 使用

```dart
SmartDialog.showLoading(
  //遮罩颜色
  maskColorTemp: Colors.black.withOpacity(0.35),
  //loading背景色
  background: Colors.blue.withOpacity(0.9),
);
```

**Comment by 2352253775qq** [comment]
SmartDialog.show 的maskColorTemp也不生效呀...
