### ISSUE TITLE
使用GoRouter该如何初始化smartDialog?

### ISSUE THREAD

**Issue by jscoolso** [fluttercandies/flutter_smart_dialog#103]
### 版本信息
- Flutter版本：[3.4.0-33.0.pre.5]
- flutter_smart_dialog版本：[v4.8.0]

### 使用GoRouter路由时，该如何初始化SmartDialog？

GetMaterialApp(
          。。。
          navigatorObservers: [FlutterSmartDialog.observer],
          builder: FlutterSmartDialog.init(
            // 自定义loading
            loadingBuilder: (String msg) => CustomLoadingWidget(loadingText: msg),
          ),
          。。。
        );
      }

GoRouter(
   。。。
    observers: [FlutterSmartDialog.observer],
    。。。
  )

goRouter 没有builder 设置了observers，还是无法使用SmartDialog

**Comment by xdd666t** [comment]
可以参考下
- https://blog.csdn.net/u013937668/article/details/127071736
- https://github.com/fluttercandies/flutter_smart_dialog/issues

**Comment by xdd666t** [comment]
这个问题先关了，上面俩个链接里面的方案，应该能解决你的问题
