### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by indeedshaw** [fluttercandies/flutter_smart_dialog#104]
### 版本信息
- Flutter版本：v3.0.5 [举例：v3.0.5]
- flutter_smart_dialog版本：v4.2.8+2 [举例：v4.2.8+2]

### 描述bug/需求
编译报错

### 问题demo
不知道是不是这边的错误，望解答。
编译过程中报如下错误：
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/119829832/216942112-9eb89349-3d1c-40c0-b58b-93526a2b1a5c.png">

**Comment by xdd666t** [comment]
flutter 3.7版本的改动是不可空了，我晚上回去还原下吧，感觉对flutter低版本不太友好

**Comment by xdd666t** [comment]
- 试试新版本

```dart
dependencies:
  flutter_smart_dialog: ^4.8.2+3
```

**Comment by indeedshaw** [comment]
编译通过了~
