### ISSUE TITLE
SmartDialog.showAttach设置alignment为Alignment.center出现偏移

### ISSUE THREAD

**Issue by OnePiece-D** [fluttercandies/flutter_smart_dialog#107]
SmartDialog.showAttach设置Alignment.center折叠屏展开折叠状态会出现偏移情况

**Comment by xdd666t** [comment]
折叠屏，，，没这个设备，这个只能靠你自强了

**Comment by OnePiece-D** [comment]
应该是屏幕尺寸变化的时候没有更新，他的位置才没改变

**Comment by xdd666t** [comment]
你可以试试，把showAttach的keepSingle参数设置为true，然后等界面折叠变动完后（应该相关回调吧？），重新调用下你用的showAttach，这时候会重新计算targetContext相关坐标信息

**Comment by xdd666t** [comment]
这个先关了，这种case可能需要你自己去针对性解决
