### ISSUE TITLE
flutter项目在iOS上启动app时，总是报出异常

### ISSUE THREAD

**Issue by xiaowei4554** [fluttercandies/flutter_smart_dialog#108]
### 版本信息
- Flutter版本：v3.7.1
- flutter_smart_dialog版本：v4.8.2+3

### 这里时初始化
`builder: FlutterSmartDialog.init(
        builder: (context, childV) {
          return MediaQuery(
            ///设置文字大小不随系统设置改变
            data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
            child: childV ?? Container(),
          );
        },
      ),`

### 这里是异常位置位置
_FlutterSmartDialogState中的initState方法中
`var navigator = widget.child as Navigator;`
### 这里是异常信息
_CastError (type 'FocusScope' is not a subtype of type 'Navigator' in type cast)

**Comment by xdd666t** [comment]
贴下完整可运行的简化main代码

**Comment by xiaowei4554** [comment]
> 贴下完整可运行的简化main代码
抱歉，这可能是我的错误导致的，和你的作品无关，感谢及时回复

**Comment by zxtyjx** [comment]
@xiaowei4554 你好，我也遇到跟你相同的问题，方便告知你是怎么排查解决这个问题的吗？
![image](https://github.com/fluttercandies/flutter_smart_dialog/assets/8037264/0b0c23c4-302b-4c20-a7dd-d90130801758)
我的项目是从flutter3.3.9升级3.10.2后出现的问题，项目是windows、macos

**Comment by xiaowei4554** [comment]
> @xiaowei4554 你好，我也遇到跟你相同的问题，方便告知你是怎么排查解决这个问题的吗？
> ![image](https://user-images.githubusercontent.com/8037264/244881637-0b0c23c4-302b-4c20-a7dd-d90130801758.png)
> 我的项目是从flutter3.3.9升级3.10.2后出现的问题，项目是windows、macos

其实这个问题并没有真正解决，虽然存在，但实际上并不影响它的工作，请在运行时取消勾选检查异常的选项

**Comment by xdd666t** [comment]
参考：https://github.com/fluttercandies/flutter_smart_dialog/issues/135

**Comment by xiaowei4554** [comment]
> 参考：#135
感谢你的回复，我刚更新到新版，已完美解决了问题，感谢
