### ISSUE TITLE
关于使用SmartDialog以后，调试变得困难的问题。

### ISSUE THREAD

**Issue by popopopdcvvbf** [fluttercandies/flutter_smart_dialog#109]
### 版本信息
- Flutter版本：3.3.8
- flutter_smart_dialog版本：^4.8.2+3

### 描述bug/需求
准确来说不是bug，
我在用AS开发过程中有经常使用Flutter Performance工具栏的Show Debug Paint。
<img width="884" alt="image" src="https://user-images.githubusercontent.com/120216692/219306965-069b6e23-a3bf-4374-9c8e-0624246a7b61.png">。
正因为在MaterialApp的build中让Smartdialog.init进行了接管,导致每次Show Debug Paint都会有一层蒙版遮盖出现，让我调试会有很大的问题。
<img width="449" alt="image" src="https://user-images.githubusercontent.com/120216692/219307832-fae70628-252e-456b-8fd5-88255b39d9fb.png">

**Comment by the6nnoo** [comment]
切换大号关注一下

**Comment by xdd666t** [comment]
**因为弹窗的相关优先级的处理（toast，loading），就目前内部实现来说，有点无解（无法在内部无感去解决）**

- 只能折中了，需要更新下版本
```
dependencies:
  flutter_smart_dialog: ^4.8.2+5
```

- 这边提供了参数，可以让你比较方便的关闭SmartDialog功能（只在debug模式下起效，release自动失效，防止你忘了调回去）
- 
```dart
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: SmartDialogPage(),
      builder: FlutterSmartDialog.init(
        // 需要 'show debug paint' 的时候，设置为true
        useDebugModel: true,
      ),
    );
  }
}
```

**Comment by xdd666t** [comment]
- 这个问题已经彻底解决，可以试下新版本，同时废弃也不需要useDebugModel参数了

```dart
dependencies:
  flutter_smart_dialog: ^4.9.7
```
