### ISSUE TITLE
DropdownButton not working as widget of SmartDialog

### ISSUE THREAD

**Issue by matthiaslarisch** [fluttercandies/flutter_smart_dialog#11]
Hello,

I wanted to use the SmartDialog with a DropdrownButton as widget. When calling the show method of the SmartDialog, the SmartDialog appears displaying the DropdownButton but when clicking on the DropdownButton nothing happen and there is this output in the terminal:

`======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
Navigator operation requested with a context that does not include a Navigator.

The context used to push or pop routes from the Navigator must be that of a widget that is a descendant of a Navigator widget.
When the exception was thrown, this was the stack: 
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
packages/flutter/src/widgets/navigator.dart 2741:9                                                                         <fn>
packages/flutter/src/widgets/navigator.dart 2747:14                                                                        of
packages/flutter/src/material/dropdown.dart 1341:48                                                                        [_handleTap]
packages/flutter/src/gestures/recognizer.dart 193:24                                                                       invokeCallback
packages/flutter/src/gestures/tap.dart 608:48                                                                              handleTapUp
packages/flutter/src/gestures/tap.dart 296:5                                                                               [_checkUp]
packages/flutter/src/gestures/tap.dart 230:7                                                                               handlePrimaryPointer
packages/flutter/src/gestures/recognizer.dart 558:9                                                                        handleEvent
packages/flutter/src/gestures/pointer_router.dart 94:12                                                                    [_dispatch]
packages/flutter/src/gestures/pointer_router.dart 139:9                                                                    <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:13      forEach
packages/flutter/src/gestures/pointer_router.dart 137:17                                                                   [_dispatchEventToRoutes]
packages/flutter/src/gestures/pointer_router.dart 123:7                                                                    route
packages/flutter/src/gestures/binding.dart 440:19                                                                          handleEvent
packages/flutter/src/gestures/binding.dart 420:14                                                                          dispatchEvent
packages/flutter/src/rendering/binding.dart 278:11                                                                         dispatchEvent
packages/flutter/src/gestures/binding.dart 374:7                                                                           [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 338:5                                                                           handlePointerEvent
packages/flutter/src/gestures/binding.dart 296:7                                                                           [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 279:32                                                                          [_handlePointerDataPacket]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 1018:13           invoke1
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/platform_dispatcher.dart 182:5             invokeOnPointerDataPacket
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart 130:39                [_onPointerData]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart 555:18                <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart 508:21                <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/pointer_binding.dart 216:16                loggedHandler
Handler: "onTap"
Recognizer: TapGestureRecognizer#3fd62
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(250.4, 360.8)
  finalLocalPosition: Offset(35.4, 25.6)
  button: 1
  sent tap down
====================================================================================================`

Attached you can find an example project which is showcasting the issue.

Do you have any advice?

Thank you and best regards,
Matthias
[smart_dialog_test.zip](https://github.com/fluttercandies/flutter_smart_dialog/files/7257920/smart_dialog_test.zip)

**Comment by CNAD666** [comment]
DropdownButton uses BuildContext, so it needs a Navigator widget parent node

- you can do this

```dart
  SmartDialog.show(
    maskColorTemp: Colors.white,
    widget: MaterialApp(
      home: DropdownButton(
        items: itemsList,
        onChanged: (value) => print('$value'),
      ),
    ),
  );
```

**Comment by matthiaslarisch** [comment]
The provided solution is working. We also found that it is working like that:

MaterialApp(
        builder: (BuildContext context, Widget? widget) {
          return Navigator(
            onGenerateRoute: (settings) => MaterialPageRoute(
                builder: (context) => FlutterSmartDialog(child: widget)),
          );
        },
