### ISSUE TITLE
兼容flutter_boost

### ISSUE THREAD

**Issue by huqigu** [fluttercandies/flutter_smart_dialog#112]
flutter_boost提供了添加路由监听的方法，如下：

BoostLifecycleBinding.instance
        .addNavigatorObserver(FlutterSmartDialog.observer);

可解决 https://github.com/fluttercandies/flutter_smart_dialog/issues/64 的问题

我发现flutter_boost早就提供了这个接口，想问一下作者是没有看到还是会有其他问题？

**Comment by xdd666t** [comment]
我这边很少用flutter_boost，之前用也是有人提这方面issue，我才试了下

感谢哈，我把这个加进文档里
