### ISSUE TITLE
弹出一个dialog，然后app退到后台 等待几十秒时间久一点之后 再进入app   dialog会自动消失

### ISSUE THREAD

**Issue by afskalsfk** [fluttercandies/flutter_smart_dialog#113]
如题：弹出一个dialog，然后app退到后台 等待几十秒时间久一点之后 再进入app   dialog会自动消失，安卓、ios 都会出现

对此情况 我该如何进行弹窗保活

我的用法如下，只用了builder这一个参数
    SmartDialog.show(builder: (context) {
                                      return CommonDialog(
                                        headerTitle: "***",
                                        bodyContent: JNXuanZeDialog(
                                          model: RtnInfoSelectSkillsList(),
                                          type: 2,
                                          position: index + 1,
                                        ),
                                      );
                                    });

**Comment by xdd666t** [comment]
必现吗？方便的话录个视频康康

**Comment by afskalsfk** [comment]
录好了 但是文件大没没地方上传  能加下微信吗  我的：Stephen___Y

**Comment by xdd666t** [comment]
我这边试了下，打开个SmartDialog弹窗，把app退出后，在后台挂了十分钟，然后打开app，弹窗依旧在

或许你可以新建个项目，用简单的代码测试下，排除下是不是业务代码导致的

- 我的测试代码

```dart
SmartDialog.show(builder: (_) {
  return Container(
    height: 80,
    width: 180,
    decoration: BoxDecoration(
      color: Colors.black,
      borderRadius: BorderRadius.circular(10),
    ),
    alignment: Alignment.center,
    child: const Text(
      'easy custom dialog',
      style: TextStyle(color: Colors.white),
    ),
  );
});
```
