### ISSUE TITLE
结合PopupMenuButton使用时，show dialog也会随pop up menu 关闭

### ISSUE THREAD

**Issue by EvanJin** [fluttercandies/flutter_smart_dialog#114]
### Version Information
- Flutter version: [e.g. v3.7.5]
- flutter_smart_dialog version: [e.g. v4.9.0+1]

### Describe the bug/requirement
Please describe the bug or requirement accurately

### Problem demo
![image](https://user-images.githubusercontent.com/1031636/223298771-66334d12-4575-414e-8853-d6d61e8f0549.png)
在popupmenubutton的onSelected回调方法内，调用show dialog，会发现 dialog更新popupmenu一起关闭，目前只能用delay的方式，延时show dialog的调用，不过还是有偶现一起关闭的现象

**Comment by xdd666t** [comment]
提供下能复现的简化demo吧（可移植性的main文件）

**Comment by EvanJin** [comment]
简单的创建一个popupmenubutton, onselected 里面写SmartDialog.show就可以复现了

**Comment by xdd666t** [comment]
你可以新建一个项目里面写个简单demo，也是让你去除掉业务代码个干扰，而且，从你的截图上看不出任何使用SmartDialog的相关配置信息

- 目前遇到很多之前的issue，都有原有业务代码导致而产生的相关问题

**Comment by xdd666t** [comment]
这个有点无语，PopupMenuButton内部用的用得弹窗页面（和页面跳转一样），SmartDialog内部记录成了页面转换，就自动把弹窗绑定

SmartDialog.show默认会将Dialog和当前路由绑定，路由关闭后，也会自动关闭Dialog

- 你把bindPage属性设置为false吧

```dart
SmartDialog.show(
  bindPage: false,
  builder: (_) {
    return Container(
      height: 80,
      width: 180,
      decoration: BoxDecoration(
        color: Colors.black,
        borderRadius: BorderRadius.circular(10),
      ),
      alignment: Alignment.center,
      child: Text(
        'easy custom dialog',
        style: TextStyle(color: Colors.white),
      ),
    );
  },
);
```
