### ISSUE TITLE
flutter devtools里额外出现一个蒙层把widget全部都盖住了

### ISSUE THREAD

**Issue by ghost** [fluttercandies/flutter_smart_dialog#115]
### 版本信息
- Flutter版本：v3.7.0
- flutter_smart_dialog版本：master

### 描述bug/需求
1. windows下跑仓库里的example
2. 打开flutter devtools里的"overlay guidlines to assists with fixing layout issues"
3. 可以看到在额外有一个蒙层把widget其它实际widget的框都挡住了
 	![image](https://user-images.githubusercontent.com/109515842/223942757-3ee33710-5e49-4b2a-97b3-6968c5eacc86.png)

有一点影响开发

### 问题demo
包里的example

**Comment by xdd666t** [comment]
- 这个问题已经彻底解决，可以试下新版本，同时废弃也不需要useDebugModel参数了

```dart
dependencies:
  flutter_smart_dialog: ^4.9.7
```
