### ISSUE TITLE
添加TextField后不支持跟随键盘弹起

### ISSUE THREAD

**Issue by travon-wu** [fluttercandies/flutter_smart_dialog#116]
### 版本信息
- Flutter版本：3.3.4
- flutter_smart_dialog版本：4.9.0

### 描述bug/需求
在Dialog内添加TextField的时候，输入框获取焦点时键盘会挡住Dialog，无法跟随键盘弹起。

**Comment by wosika** [comment]
您好，请问您有解决方案吗？

**Comment by xdd666t** [comment]
@wosika 看看这个吧 https://github.com/fluttercandies/flutter_smart_dialog/issues/35
