### ISSUE TITLE
4.9.0+1在release版多次显示toast会遮挡页面不能操作

### ISSUE THREAD

**Issue by CarrySniper** [fluttercandies/flutter_smart_dialog#118]
### 版本信息
- Flutter版本：[举例：v3.7.7]
- flutter_smart_dialog版本：[举例：v4.9.0+1]

### 描述bug/需求
和Flutter版本无关，debug没问题。
新版在release版多次显示toast会遮挡页面不能操作。
重现方法：打包一个release包安装到手机，功能是按钮点击触发
```
SmartDialog.showToast(
  "message",
   displayType: SmartToastType.last, // 连续调用toast，后一条toast会顶掉前一条toast
);
```
连续点击多次按钮就会出现类似应用卡死的现象。
是设置这个属性才发生：displayType: SmartToastType.last

**Comment by mdddj** [comment]
不设置这个displayType: SmartToastType.last 也会发生

**Comment by CarrySniper** [comment]
感谢你的来信。
 
你的来信已经发送到CJQ处。

**Comment by xdd666t** [comment]
- 对于SmartToastType.last导致卡死的问题解决了，使用新版本试试吧

```dart
dependencies:
  flutter_smart_dialog: ^4.9.0+2
```
