### ISSUE TITLE
新版Toast release 导致应用卡死, 无响应

### ISSUE THREAD

**Issue by mdddj** [fluttercandies/flutter_smart_dialog#119]
### 版本信息
- Flutter版本：[举例：v3.7.7]
- flutter_smart_dialog版本：[举例：v4.9.0+1]

### 描述bug/需求
![image](https://user-images.githubusercontent.com/29020213/224470303-d2ed8fab-72e4-4a20-8b66-c0e874b1192c.png)

**Comment by xdd666t** [comment]
你这个怎么操作后，发生的？

**Comment by mdddj** [comment]
> 你这个怎么操作后，发生的？
不太确定, 线上版本发生的, bugly捕获的信息太少,也没说项目上的哪一行代码出的错, 有用的信息就是第二行

**Comment by mdddj** [comment]
> * 这个问题解决了，使用新版本试试吧
> 
> ```dart
> dependencies:
>   flutter_smart_dialog: ^4.9.0+2
> ```

好的,大佬幸苦了

**Comment by xdd666t** [comment]
😂不好意思，回复错了

- 这个异常信息太少，有点不确认是不是#118 case导致，你可以更新版本试试
  - 如果依旧有上报异常，看看能不能提供更新详细的信息

```dart
dependencies:
  flutter_smart_dialog: ^4.9.0+2
```

**Comment by mdddj** [comment]
😂 那可能要过一段时间看用户的反馈,我这也没办法复现

**Comment by xdd666t** [comment]
> 😂 那可能要过一段时间看用户的反馈,我这也没办法复现

OK，这个issue先留着
