### ISSUE TITLE
toast的maskColor无效

### ISSUE THREAD

**Issue by lizhuoyuan** [fluttercandies/flutter_smart_dialog#120]
### 版本信息
- Flutter版本：[举例：v3.7.6]
- flutter_smart_dialog版本：[举例：4.9.0+3]

### 描述bug/需求
全局设置的toast和单独设置的toast的maskColor属性无效

### 问题demo
```
 SmartDialog.config.toast = SmartConfigToast(
        alignment: Alignment.center,
        //maskColor: const Color(0xCC1D4049),
        maskColor: Colors.red);




 SmartDialog.showToast('msg',maskColor: Colors.red);
```

两种方式弹出的toast背景都是黑的

**Comment by xdd666t** [comment]
因为Toast的特殊性，所以usePenetrate参数默认设置为true，该参数为true，遮罩将会自动失效

还有你说的Toast背景和遮罩还是有很大区别的

想高度自定义Toast的样式，请参考：https://github.com/fluttercandies/flutter_smart_dialog/issues/24
