### ISSUE TITLE
showAttach useSystem设置为 true 和系统弹框交互显示层级错误

### ISSUE THREAD

**Issue by muuyao** [fluttercandies/flutter_smart_dialog#121]
### 版本信息
- Flutter版本：v3.7.7
- flutter_smart_dialog版本：v4.9.0

### 描述bug/需求
通过 showAttach 弹出弹框，然后弹框里点击输入框会打开系统的日期组件，之前通过 useSystem：true 可以实现层级正常显示，但是升级 4.9.0 之后，系统的日期组件会显示在弹框下层

**Comment by xdd666t** [comment]
给下简单的demo吧

**Comment by muuyao** [comment]
> 给下简单的demo吧
已经找到问题了，加上 navigatorObservers: [FlutterSmartDialog.observer] 就好了，但之前版本不加的时候也是好的
