### ISSUE TITLE
连续多次打开toast后无法关闭toast

### ISSUE THREAD

**Issue by yhz199132** [fluttercandies/flutter_smart_dialog#122]
### 版本信息
- Flutter版本：[v3.7.7]
- flutter_smart_dialog版本：[v4.9.0+3]

### 描述bug/需求
快速的连续多次调用SmartDialog.showToast后，toast会一直显示无法关闭，当displayType为SmartToastType.onlyRefresh时稳定复现。下面是异常信息
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/overlay.dart': Failed assertion: line 164 pos 12: '_overlay != null': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      OverlayEntry.remove (package:flutter/src/widgets/overlay.dart:164:12)
#3      ToastTool.dismiss (package:flutter_smart_dialog/src/custom/toast/toast_tool.dart:29:38)

### 问题demo

`SmartDialog.showToast( '这是toast信息',
      alignment: alignment ?? Alignment.topCenter,
      displayTime: const Duration(milliseconds: 1800),
      displayType: SmartToastType.onlyRefresh, builder: (context) {
    return ToastView(
      toastType: toastType,
      message: message,
    );
  });`

**Comment by xdd666t** [comment]
- 这个问题已经解决了哈，更新到新版本试试

```dart
dependencies:
  flutter_smart_dialog: ^4.9.0+4
```

**Comment by yhz199132** [comment]
@xdd666t  版本4.9.0+4  无法拉取   pub get  报错  depends on flutter_smart_dialog ^4.9.0+4 which doesn't match any versions, version solving failed.
pub get failed

**Comment by xdd666t** [comment]
- 检查下你的写法吧，我这边能拉新版本

![image](https://user-images.githubusercontent.com/35656085/226260015-38caf2fe-567d-4ae3-a567-37dac301b6e4.png)

**Comment by yhz199132** [comment]
> * 检查下你的写法吧，我这边能拉新版本
> 
> ![image](https://user-images.githubusercontent.com/35656085/226260015-38caf2fe-567d-4ae3-a567-37dac301b6e4.png)

确认写法没有问题 ，+3的版本可以正常拉取

错误信息：
Because mobile_client depends on flutter_smart_dialog ^4.9.0+4 which doesn't match any versions, version solving failed.
pub get failed
command: "/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "/flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "/.pub-cache",
}
exit code: 1

**Comment by xdd666t** [comment]
按理来说，不会拉不成功的，这个包早就发布成功了

或许可以新建个flutter项目，然后写入这个版本，尝试拉下看看

- 我感觉可能是缓存的原因，或者代理的原因，或者尝试切换其他的pub代理源

![image](https://user-images.githubusercontent.com/35656085/226264730-40c1a036-7a26-43c0-a1de-97b25fe9d17a.png)
