### ISSUE TITLE
Date Picker in SmartDialog

### ISSUE THREAD

**Issue by NiranjanShah** [fluttercandies/flutter_smart_dialog#123]
Hello, 
first of all thank you for this beautiful library.

We are not able to show date picker in Smart Dialog.

when trying to open the datepicker on a button click, below error is been shown.

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Navigator operation requested with a context that does not include a Navigator.
The context used to push or pop routes from the Navigator must be that of a widget that is a descendant of a Navigator widget.

PS: we are using GetMaterial App

**Comment by xdd666t** [comment]
Do not use the context in the builder of SmartDialog to open showDatePicker, please use the context of the external page

**Comment by mstestlp** [comment]
> Do not use the context in the builder of SmartDialog to open showDatePicker, please use the context of the external page

使用外部显示后,日期dlg在弹窗的底部,如何放到最顶层呢

After using external display, how to place the date dlg at the bottom of the pop-up window on the top level
