### ISSUE TITLE
SmartDialog想要不擋著BottomNavigationBar

### ISSUE THREAD

**Issue by felix0324324** [fluttercandies/flutter_smart_dialog#124]
### 版本信息
- Flutter版本：3.7.7
- flutter_smart_dialog版本：4.9.0

### 描述bug/需求
我正在使用(https://github.com/BilalShahid13/PersistentBottomNavBar)PersistentBottomNavBar的底層實現
以下的UI, 但是我是要使用SmartDialog.showAttach 和 targetContext實現嗎? 
已經取得了Navigation的NavigationKey的context但放進去也只是右邊效果
這個搞了幾天還是做不了左邊的效果...

![dd0Wjmb](https://user-images.githubusercontent.com/16462532/228146534-957df905-1b6a-4a9c-974c-a04aaa347c8d.jpg)

請求大佬指點一下

**Comment by xdd666t** [comment]
- show可以试下这个

![image](https://user-images.githubusercontent.com/35656085/228147578-0f90f919-690e-4adf-b874-7d665ebce8dd.png)

- showAttach可以试下这个

![image](https://user-images.githubusercontent.com/35656085/228147725-9c4b0ceb-a85b-4525-9da1-a4b6aa907687.png)

**Comment by felix0324324** [comment]
> * show可以试下这个
> 
> ![image](https://user-images.githubusercontent.com/35656085/228147578-0f90f919-690e-4adf-b874-7d665ebce8dd.png)
> 
> * showAttach可以试下这个
> 
> ![image](https://user-images.githubusercontent.com/35656085/228147725-9c4b0ceb-a85b-4525-9da1-a4b6aa907687.png)

試了但轉換下面Tab時沒能消失
我開了個Demo請看看[在這](https://github.com/felix0324324/Persistent-smart_dialog)


<img width="510" alt="螢幕截圖 2023-03-28 下午3 15 47" src="https://user-images.githubusercontent.com/16462532/228157955-1c9588aa-e3cb-401b-82a2-cfc22ae2bf4f.png">
<img width="510" alt="螢幕截圖 2023-03-28 下午3 15 52" src="https://user-images.githubusercontent.com/16462532/228157983-9be15f3f-604d-49d3-8b4d-a072d5f846ee.png">
<img width="510" alt="螢幕截圖 2023-03-28 下午3 15 58" src="https://user-images.githubusercontent.com/16462532/228157990-69f89787-c2fa-4f03-8b89-4be45f1e5caa.png">

我在push view後馬上call了個SmartDialog.show如下圖

> ElevatedButton(
                    onPressed: () {
                      PersistentNavBarNavigator.pushNewScreenWithRouteSettings(
                        context,
                        settings: const RouteSettings(name: "/home"),
                        screen: const MainScreen2(),
                        pageTransitionAnimation:
                            PageTransitionAnimation.scaleRotate,
                      );
                      SmartDialog.show(
                          ignoreArea: const Rect.fromLTRB(0, 0, 0, 120),
                          builder: (final build) => Container(
                                height: 100,
                                width: 100,
                                color: Colors.red,
                              ));
                    },
                    child: const Text(
                      "Go to Second Screen ->",
                      style: TextStyle(color: Colors.white),
                    ),
                  ),

謝謝你了!!

**Comment by xdd666t** [comment]
需要转行tab的时候显隐，可以配合使用bindWidget，bindWidget需要当前tab子页面的context

**Comment by felix0324324** [comment]
> 需要切换tab的时候显隐dialog，可以配合使用bindWidget，bindWidget需要当前tab子页面的context

已bind上正確的context還是有問題
但最後發現是... animateTabTransition只能是true, 不能是false, 不然轉換tab後當前dialog不會消失

解決方法 : 
```
PersistentTabView(
      context,
      controller: controller.myController,
      screens: _buildScreens(),
      items: _navBarsItems(),
      screenTransitionAnimation: ScreenTransitionAnimation(
        animateTabTransition: true,
      ),
    );
```

感謝 @xdd666t 的幫忙
