### ISSUE TITLE
有關使用Getx時產生var navigator = widget.child as Navigator;的問題 

### ISSUE THREAD

**Issue by felix0324324** [fluttercandies/flutter_smart_dialog#125]
版本信息
Flutter版本：3.7.7
flutter_smart_dialog版本：4.9.0
描述bug/需求

### 问题demo
<img width="978" alt="螢幕截圖 2023-03-28 下午4 54 41" src="https://user-images.githubusercontent.com/16462532/228183950-3140d608-1396-400c-8385-aac053e42d5c.png">

這個不是很知道要怎搞...
已經用了Getx和你們的example了

**Comment by xdd666t** [comment]
贴下你的初始化代码看看

**Comment by felix0324324** [comment]
```
> 贴下你的初始化代码看看


void main() {
  runApp(
    GetMaterialApp.router(
        navigatorObservers: [FlutterSmartDialog.observer],
        title: "Application",
        initialBinding: BindingsBuilder(
          () {
            Get.put(AuthService());
          },
        ),
        getPages: AppPages.routes,
        builder: (context, myWidget) {
          myWidget = FlutterSmartDialog.init()(context, myWidget);
          return myWidget;
        }),
  );
}
```

<img width="1310" alt="螢幕截圖 2023-03-28 下午7 29 30" src="https://user-images.githubusercontent.com/16462532/228222417-50eb6602-10cc-4663-889a-16b6379241f0.png">

**Comment by xdd666t** [comment]
- 这样写

![image](https://user-images.githubusercontent.com/35656085/228222784-1008b442-dad0-46f9-9cc6-63ed8adfdd3b.png)

- 如果需要用到builder，可以用init种的提供出来的builder

![image](https://user-images.githubusercontent.com/35656085/228223025-5f6e1936-2f39-4790-a10b-f29ae798f1c0.png)

**Comment by xdd666t** [comment]
还有，用到GetMaterialApp.router参考这边写法 #67
