### ISSUE TITLE
flutter_smart_dialog少export了SmartConfigNotify

### ISSUE THREAD

**Issue by Dabbit-Chan** [fluttercandies/flutter_smart_dialog#126]
### 版本信息
- flutter_smart_dialog版本：[举例：v4.9.0]

### 描述bug/需求
flutter_smart_dialog少export了SmartConfigNotify导致我改SmartConfigNotify的时候要手动import😂

**Comment by xdd666t** [comment]
😂等我晚上回去改

**Comment by xdd666t** [comment]
- OK了，试试新版本哈

```dart
dependencies:
  flutter_smart_dialog: ^4.9.0+5
```
