### ISSUE TITLE
showAttach 指定targetBuilder弹出的位置不对

### ISSUE THREAD

**Issue by hukejia** [fluttercandies/flutter_smart_dialog#127]
- flutter_smart_dialog版本：[4.9.0]

我理解的targetBuilder的意思是指定弹出的坐标点，但是指定之后弹出的位置并不是我指定的位置，

```
SmartDialog.showAttach(
          targetContext: context,
          targetBuilder: (targetOffset,targetSize){
            print(targetOffset);
            print(targetSize);
            return Offset(0, 100);

            // final parentRenderBox = widget.parentKey!.currentContext!.findRenderObject() as RenderBox;
            // Offset parentOffset = parentRenderBox.localToGlobal(Offset.zero);
            // Size parentSize = parentRenderBox.size;
            // double topSpace = targetOffset.dy - parentOffset.dy ;
            // double bottomSpace = parentOffset.dy + parentSize.height  - (targetOffset.dy + targetSize.height);
            //
            // double space = max(topSpace, bottomSpace);
            // if(space > height){
            //   return Offset(targetOffset.dx + targetSize.width / 2, topSpace  > bottomSpace ? targetOffset.dy - height : targetOffset.dy + targetSize.height);
            // }else{
            //   return Offset(targetOffset.dx + targetSize.width / 2, parentOffset.dy + parentSize.height / 2);
            // }
          },
          builder: (context) => Container(
            width: 100,
            height: 100,
            color: Colors.red,
          ),
        );

**Comment by xdd666t** [comment]
这是因为内部会根据你的偏移量和目标widget的尺寸，算出一个比较合适的居中数据，如果你想完全自定义，把targetContext设置为null就行了

**Comment by hukejia** [comment]
> 这是因为内部会根据你的偏移量和目标widget的尺寸，算出一个比较合适的居中数据，如果你想完全自定义，把targetContext设置为null就行了，可参考这个用法：https://xdd666t.github.io/flutter_use/web/index.html#/smartDialog?dialogType=AttachDialogPoint
> 
> * 请注意，因为targetContext设置为null，所以这时候回调的targetOffset,targetSize的数据都会为0

targetContext不为null的时候targetBuilder的作用是啥，我一直没试出规律

**Comment by xdd666t** [comment]
可以比较灵活的调整自动计算位置的偏移量

- 比如：我想在自动计算的基础上，是的dialog和目标widget间保持20的距离，这样就能在目标widget下方20的距离处出现

```dart
SmartDialog.showAttach(
  targetContext: context,
  targetBuilder: (targetOffset,targetSize){
    return Offset(targetOffset.dx, targetOffset.dy + 20);
  },
  builder: (context) => Container(
    width: 100,
    height: 100,
    color: Colors.red,
  ),
);
```

**Comment by hukejia** [comment]
> 可以比较灵活的调整自动计算位置的偏移量
> 
> * 比如：我想在自动计算的基础上，使得dialog和目标widget间保持20的距离，这样就能在目标widget下方20的距离处出现
> 
> ```dart
> SmartDialog.showAttach(
>   targetContext: context,
>   targetBuilder: (targetOffset,targetSize){
>     return Offset(targetOffset.dx, targetOffset.dy + 20);
>   },
>   builder: (context) => Container(
>     width: 100,
>     height: 100,
>     color: Colors.red,
>   ),
> );
> ```

有一种场景，类似微信聊天气泡长按弹出菜单，长按第一个的时候弹出菜单，长按另一个气泡的时候关闭第一个菜单，弹出第二个菜单，我用这个库试的结果是，长按第二个的时候，正常弹出来了，但是手松开的时候，弹窗就自动关闭了，我把clickMaskDismiss设置成false，第二个框能正常弹出，但是点击mask弹窗又不会消失，有没有办法解决这个问题

**Comment by xdd666t** [comment]
- 全局配置下，遮罩的点击响应事件类型就行了

```dart
SmartDialog.config.attach = SmartConfigAttach(
  maskTriggerType: SmartMaskTriggerType.down,
);
```
