### ISSUE TITLE
4.9.0+5 SmartToastType.last toast不消失

### ISSUE THREAD

**Issue by bbaiqiang** [fluttercandies/flutter_smart_dialog#128]
### 版本信息
- Flutter版本：3.7.6
- flutter_smart_dialog版本：4.9.0+5

当类型为SmartToastType.last时，连续调用多次SmartDialog.showToast(str)方法，toast不会消失。

void showToast(String str) {
  SmartDialog.config.toast = SmartConfigToast(
      alignment: Alignment.center,
      displayType: SmartToastType.last,
    );
    SmartDialog.showToast(str);
}

**Comment by xdd666t** [comment]
- 解决了，试试新版本

```dart
dependencies:
  flutter_smart_dialog: ^4.9.0+6
```

**Comment by bbaiqiang** [comment]
问题解决了，谢谢大佬

**Comment by hy106211** [comment]
Flutter版本：3.10.5
flutter_smart_dialog版本：4.9.6

同样的问题，偶现

**Comment by Gerry1218** [comment]
4.9.8+1 多次调用偶现
