### ISSUE TITLE
toast with RichText

### ISSUE THREAD

**Issue by Maheaven** [fluttercandies/flutter_smart_dialog#129]
### Version Information 
- flutter_smart_dialog版本：[v4.9.0]

### Describe the bug/requirement
I need a toast containing RichText, and I can customize the UI, but I can only pass in a String, which doesn't fit my needs. FlutterSmartToastBuilder Whether to add a non-required dynamic parameter

```dart
typedef FlutterSmartToastBuilder = Widget Function(String msg);
```

**Comment by xdd666t** [comment]
This is the configuration of the global Toast. I think it should be as simple as possible. If you have more customization requirements, you can use the `builder` parameter of showToast.

**Comment by Maheaven** [comment]
> 这是全局Toast的配置。我认为它应该尽可能简单。如果你有更多的自定义需求，可以使用`builder`showToast的参数。

I see.Thanks!
