### ISSUE TITLE
使用auto_route, 如何初始化SmartDialog

### ISSUE THREAD

**Issue by sineom-1** [fluttercandies/flutter_smart_dialog#130]
### 版本信息
- Flutter版本：[v3.7.12]
- flutter_smart_dialog版本：[v4.9.0+6]

### 描述bug/需求
[auto_route](https://pub.dev/packages/auto_route#installation)的初始化使用MaterialApp.router的routerConfig，SmartDialog的navigatorObservers改如何初始化呢？

**Comment by xdd666t** [comment]
没用过auto_route，不太清楚

你不配置navigatorObservers，在这个路由框架中，会遇到什么问题，useSystem参数可正常使用吗？

**Comment by sineom-1** [comment]
感谢大佬的回复！
  已经找到解决方案了。 [参考次Issues](https://github.com/Milad-Akarie/auto_route_library/issues/424)
