### ISSUE TITLE
auto_route中创建多个router使用nested router时，navigatorObservers添加FlutterSmartDialog.observer报错

### ISSUE THREAD

**Issue by Dean-Spotec** [fluttercandies/flutter_smart_dialog#132]
### 版本信息
- Flutter版本：[v3.7.12]
- flutter_smart_dialog版本：[v4.8.2+4]

### 描述bug/需求
报错：Failed assertion: line 3299 pos 14: 'observer.navigator == null': is not true.
[auto_route](https://pub.dev/packages/auto_route#navigation-observers)文档中描述：使用nested router时，必须每次创建新的observer。是否可以暴露SmartNavigatorObserver出来，让我们直接使用：
```
return MaterialApp.router(                
  routerConfig: _appRouter.config(                         
    navigatorObservers: () => [SmartNavigatorObserver()],                
  ),                  
);
```
> Then we pass our observer to the <routerName>.config(). Important notice that navigatorObservers property is a builder function that returns a list of observes and the reason for that is a navigator observer instance can only be used by a single router, so unless you're using a one single router or you don't want your nested routers to inherit observers make sure navigatorObservers builder always returns fresh observer instances.

**Comment by xdd666t** [comment]
- 请参考：https://github.com/fluttercandies/flutter_smart_dialog/issues/131

<img width="904" alt="image" src="https://github.com/fluttercandies/flutter_smart_dialog/assets/35656085/0616fcd2-ed6c-4c33-bbe2-62f01a66f42b">

**Comment by Dean-Spotec** [comment]
现在项目中就是使用的`FlutterSmartDialog.observer`然后报错，需求就是想实现类似iOS中present一个页面的功能：

https://github.com/fluttercandies/flutter_smart_dialog/assets/75231684/48ce3003-edb3-432a-8dac-15e9ef51d431

想要这种效果，就需要用到auto_route中的nested router，用了nested router则navigatorObservers必须每次都得新建，不能用静态变量或者存储下来的属性。
<img width="1011" alt="image" src="https://github.com/fluttercandies/flutter_smart_dialog/assets/75231684/ce5fd43a-8eab-43cd-8c1a-b60944773b7b">
我写了一个demo，大佬有空可以看下：
[smart_auto.zip](https://github.com/fluttercandies/flutter_smart_dialog/files/11650387/smart_auto.zip)

**Comment by xdd666t** [comment]
- 试下新版本，还是用 `FlutterSmartDialog.observer `

```
dependencies:
  flutter_smart_dialog: ^4.9.1
```

**Comment by Dean-Spotec** [comment]
大佬神速，🥹
