### ISSUE TITLE
在封装的库中引入flutter_smart_dialog，之后在项目中引入封装的库 flutter_smart_dialog 报错

### ISSUE THREAD

**Issue by WoNiu456** [fluttercandies/flutter_smart_dialog#133]
### 版本信息
- Flutter版本：3.7.12
- flutter_smart_dialog版本：^4.9.0+6

### 描述bug/需求
在我自己封装的登录界面库里，引入了 flutter_smart_dialog ，然后在我的测试项目中引入我的登录库，在
SmartDialog.showLoading(backDismiss: false,maskColor: Tool.translucentGrey,msg: ''); 
时报错
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field '_loading@637397047' has not been initialized.
E/flutter (12630): #0      DialogProxy._loading (package:flutter_smart_dialog/src/helper/dialog_proxy.dart)
E/flutter (12630): #1      DialogProxy.showLoading (package:flutter_smart_dialog/src/helper/dialog_proxy.dart:282:12)
E/flutter (12630): #2      SmartDialog.showLoading (package:flutter_smart_dialog/src/smart_dialog.dart:716:33)
E/flutter (12630): #3      Hud.showLoading (package:login/utils/Hud.dart:21:17)
E/flutter (12630): #4      PasswordProvider.getImage (package:login/password/password_provider.dart:32:9)

直接运行我的库 flutter_smart_dialog 是正常的，在另一个项目中引入我的库，flutter_smart_dialog 就出现了这个问题。

### 问题demo
class Hud {

  Hud._internal();

  factory Hud() => _instance;

  static final Hud _instance = Hud._internal();

  static showToast(String msg){
    SmartDialog.showToast(msg,alignment: Alignment.center,displayType: SmartToastType.last);
  }

  static showLoading(){
    SmartDialog.showLoading(backDismiss: false,maskColor: Tool.translucentGrey,msg: '');
  }

  static dismissLoading(){
    SmartDialog.dismiss();
  }

}

**Comment by xdd666t** [comment]
- 必须初始化：https://github.com/fluttercandies/flutter_smart_dialog/issues/131

<img width="962" alt="image" src="https://github.com/fluttercandies/flutter_smart_dialog/assets/35656085/8089ad41-937e-47a5-8199-ec19020bc1f3">
