### ISSUE TITLE
请问有任何形式/方法可以刷新已经打开的Attach的位置，避免动态更改container高度后，超出屏幕

### ISSUE THREAD

**Issue by xlfdyzcs** [fluttercandies/flutter_smart_dialog#134]
### 版本信息
- Flutter版本：3.7.9
- flutter_smart_dialog版本：4.9.0+4

### 描述bug/需求
1，利用SmartDialog.showAttach打开一个container后，它的height设为100
2，经过交互修改1中container的height为200（假设部分内容越界到屏幕下方）
3，调用某个方法或其他操作，刷新dialog的位置，使得2中被屏幕遮挡的内容重新显示出来

**Comment by xdd666t** [comment]
- 内部第一次布局完可以使用这个调整布局坐标点

<img width="982" alt="image" src="https://github.com/fluttercandies/flutter_smart_dialog/assets/35656085/3466f9e3-00c9-4caa-a3bf-591d31076de5">

- 如果你说的这个场景需要延后很多，如果增加这些操作，会让整体api使用变得更加复杂，或许你可以在内部计算完可用高度，定死高度，加上可滚动

**Comment by xlfdyzcs** [comment]
> * 内部第一次布局完可以使用这个调整布局坐标点
> 
> <img alt="image" width="982" src="https://user-images.githubusercontent.com/35656085/243316055-3466f9e3-00c9-4caa-a3bf-591d31076de5.png">
> * 如果你说的这个场景需要延后很多，如果增加这些操作，会让整体api使用变得更加复杂，或许你可以在使用的时候计算完可用高度，定死高度，加上可滚动

好的，感谢答疑
