### ISSUE TITLE
type 'FocusScope' is not a subtype of type 'Navigator' in type cast

### ISSUE THREAD

**Issue by zxtyjx** [fluttercandies/flutter_smart_dialog#135]
### 版本信息
- Flutter版本：3.10.4
- flutter_smart_dialog版本：4.9.1

### 描述bug/需求
项目是由flutter 3.3.9升级到3.10.4的，之前一直没有问题现在每次第一次运行都会报异常,但是项目运行后没有影响
![image](https://github.com/fluttercandies/flutter_smart_dialog/assets/8037264/03aa7a8a-a9d3-40c8-bd29-2320dc34113b)

### 问题demo
![image](https://github.com/fluttercandies/flutter_smart_dialog/assets/8037264/a328dd5b-1f38-4895-8e07-28e0917f0884)

**Comment by xdd666t** [comment]
- 解决了，试下新版本

```
dependencies:
  flutter_smart_dialog: ^4.9.2
```

**Comment by zxtyjx** [comment]
测试了完美解决 👍🏻
