### ISSUE TITLE
Error: LateInitializationError: Field 'contextCustom' has not been initialized

### ISSUE THREAD

**Issue by yc0524** [fluttercandies/flutter_smart_dialog#138]
### 版本信息
- Flutter版本：v3.10.2
- flutter_smart_dialog版本：4.9.1

### 描述bug/需求
直接调用demo报错
![微信图片_20230627175918](https://github.com/fluttercandies/flutter_smart_dialog/assets/33405012/bcfbadc8-d5b0-4914-8ecd-3452821aa841)

### 问题demo
```
void _show() async {
    SmartDialog.show(builder: (_) {
      return Container(
        height: 80,
        width: `180,`
        decoration: BoxDecoration(
          color: Colors.black,
          borderRadius: BorderRadius.circular(10),
        ),
        alignment: Alignment.center,
        child: const Text(
          'easy custom dialog',
          style: TextStyle(color: Colors.white),
        ),
      );
    });
```

**Comment by AnnaBershadska** [comment]
@yc0524 how did you solve it?

**Comment by xdd666t** [comment]
> @yc0524 how did you solve it?
- https://github.com/fluttercandies/flutter_smart_dialog/issues/131
![image](https://github.com/fluttercandies/flutter_smart_dialog/assets/35656085/4eab02f9-5499-4c1c-bed6-a22662c92ee5)
