### ISSUE TITLE
bindPage不起效果

### ISSUE THREAD

**Issue by devbravesy** [fluttercandies/flutter_smart_dialog#141]
### 版本信息
- Flutter版本：3.73
- flutter_smart_dialog版本：4.9.0+6

**Comment by xdd666t** [comment]
给下可复现的简化demo代码

**Comment by xdd666t** [comment]
你这个问题应该是你初始化的配置有问题，这个项目也用的getx：https://github.com/xdd666t/flutter_use，跳转完全符合预期，你自己看看吧
