### ISSUE TITLE
版本4.9.3+1怎么没用loading背景颜色自定义了

### ISSUE THREAD

**Issue by elinxer** [fluttercandies/flutter_smart_dialog#143]
### 版本

flutter_smart_dialog: ^4.9.3+1

loading背景颜色自定义没有了，自行定义整个loading又过于麻烦，建议增加背景颜色可选项，自定义颜色优先级最高，同时增加统一style：颜色，图标颜色

**Comment by xdd666t** [comment]
建议走全局自定义loading（可以拷贝出内部的默认loading自己改改）：https://github.com/fluttercandies/flutter_smart_dialog/issues/131
![image](https://github.com/fluttercandies/flutter_smart_dialog/assets/35656085/d92ff9ac-32b1-4f68-83ad-1fb9f44f512e)

提供再多的自定义参数也不能满足所有人的需求，不能让这些没关紧要配置样式的参数过多占用参数配置，这样只会进一步增加理解参数和使用的成本
