### ISSUE TITLE
showLoading时的msg可以动态变化

### ISSUE THREAD

**Issue by luofengBJ** [fluttercandies/flutter_smart_dialog#145]
### 版本信息
- Flutter版本：[举例：v3.0.5]
- flutter_smart_dialog版本：[举例：v4.5.5+2]

### 描述bug/需求
需求：使用SmartDialog.showLoading时，有没有参数可以使得msg能够给动态变化的呢？
场景：点按钮，showLoading后，下载文件，释放，合并，需要将这几个过程量化为百分比显示到showLoading界面上

**Comment by xdd666t** [comment]
- 只改文字，可以使用showLoading(msg: "test")
- 如果需要根据外部变量动态改变，请使用自定义builder，配合SmartDialogController控制刷新
