### ISSUE TITLE
当布局里面有 listview 的时候，listview 顶部会自动留有一点间距

### ISSUE THREAD

**Issue by LuoGuoXin** [fluttercandies/flutter_smart_dialog#146]
### 版本信息
- Flutter版本：3.10.5
- flutter_smart_dialog版本：4.9.1

### 描述bug/需求
就是我弹框里面写了个布局，里面是有个 listview 的，然后界面显示的内容，listview 顶部会留有一点空白，需要手动滑动上去。

### 问题demo
/// 弹出底部弹框

void showBottomDialog(Widget widget) {
  SmartDialog.show(
    alignment: Alignment.bottomCenter,
    builder: (_) => Container(
      width: double.infinity,
      decoration: const BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.only(
          topLeft: Radius.circular(15),
          topRight: Radius.circular(15),
        ),
      ),
      child: SingleChildScrollView(child: widget),
    ),
  );
}

    showBottomDialog(SizedBox(
      height: 400,
      child: Column(
        children: [
          Text("data"),
          Expanded(
            child: ListView.builder(
                itemCount: 100,
                itemBuilder: (context, index) {
                   return Text("data$index");
                }),
          )
        ],
      ),
    ));

[图片样式](https://img-fe.tengzhihh.com/image/65d4b5a541f580-918x1046.png)

请看图片

**Comment by xdd666t** [comment]
这本来就是ListView的特性，你自己看看吧：https://www.cnblogs.com/r1cardo/p/15572161.html
