### ISSUE TITLE
请问有什么办法可以获取当前栈的信息吗？

### ISSUE THREAD

**Issue by Dabbit-Chan** [fluttercandies/flutter_smart_dialog#147]
### 版本信息
- Flutter版本：v3.3.5
- flutter_smart_dialog版本：v4.9.0+5

### 需求
有两个需求：
1、这里我会为每个dialog都设置一个tag，不知道能不能通过tag得知某个dialog是否存在？
2、这里可能会同时存在多个dialog。比如一红一绿两个，绿的先show，红的后show，那么红色的就会叠在绿色的上面，不知是否有方法可以调整两个dialog的层级，让我点绿色的时候绿色在顶，点红色的时候红色在顶？

**Comment by xdd666t** [comment]
对于第二点功能，就目前而言是不会去考虑加的，有几点原因
- 会使得使用成本增加，多种不同优先级弹窗，会使得关闭顺序变的混乱（先关处于上层或者先关后打开，每个人都会有不同的看法）
- 插入不同层级弹窗层，涉及到打开多弹窗和关闭动画的延迟，极大可能会导致插入异常的情况
- 成本上需要花费极大的精力去处理各种弹窗优先级管理，目前多类弹窗：custome，attach，notify，toast，loading，每类弹窗都有自己优先级机制，由于都使用同一栈管理，引入优先级机制需要去兼容多类弹窗各种场景

如果你想是的你的弹窗在上层，你可以使用showNotify去自定义，后打开的弹窗使用show会出现在showNotify的下层
showNotify默认不处理返回按钮，可以看看backType属性

对于第一点，你为什么想知道默认弹窗存在呢？知道他存在后，要干什么呢？

**Comment by Dabbit-Chan** [comment]
> 对于第二点功能，就目前而言是不会去考虑加的，有几点原因
> 
> * 会使得使用成本增加，多种不同优先级弹窗，会使得关闭顺序变的混乱（先关处于上层或者先关后打开，每个人都会有不同的看法）
> * 插入不同层级弹窗层，涉及到打开多弹窗和关闭动画的延迟，极大可能会导致各种插入异常的情况
> * 成本上需要花费极大的精力去处理各种弹窗优先级管理，目前多类弹窗：custome，attach，notify，toast，loading，每类弹窗都有自己优先级机制，由于都使用同一栈管理，引入优先级机制需要去兼容多类弹窗各种场景
> 
> 如果你想是的你的弹窗在上层，你可以使用showNotify去自定义（showNotify优先级在show之上），后打开的弹窗使用show会出现在showNotify的下层 showNotify默认不处理返回按钮，可以看看backType属性
> 
> 对于第一点，你为什么想知道默认弹窗存在呢？知道他存在后，要干什么呢？

这里的业务是这样的：我是在web端使用的。有一个列表，列表里每个item都有个查看记录的按钮，点了之后会弹一个记录弹框，弹框可以拖动，用户可以同时查看多条记录，所以我根据每个记录的id设置弹框的tag。
如果能知道某个tag的弹框存在，那他如果点了同一个“查看记录“，那就不显示新的弹框。
如果可以设置层级，那就可以不显示新的弹框同时把旧弹框置顶。

由于现在不考虑添加层级，那就只能劝说产品不让用户同时查看多条记录了...

**Comment by xdd666t** [comment]
我觉你想麻烦了，就算加了优先级，你还有把之前弹窗置顶的操作，优先级也是针对刚打开的弹窗

有个简单的办法，你之前把弹窗动画关掉就行了，就能达到你想要的效果

**Comment by Dabbit-Chan** [comment]
现在就只需要需求1了

**Comment by Dabbit-Chan** [comment]
> 我觉你想麻烦了，就算加了优先级，你还有把之前弹窗置顶的操作，优先级也是针对刚打开的

现在就只需要需求1了，有什么办法吗？只需要判断弹窗是否出现

**Comment by xdd666t** [comment]
> 现在就只需要需求1了，有什么办法吗？只需要判断弹窗是否出现

这个可以的，周末加上

**Comment by Dabbit-Chan** [comment]
> > 现在就只需要需求1了，有什么办法吗？只需要判断弹窗是否出现
> 
> 这个可以的，周末加上

好的感谢大佬

**Comment by xdd666t** [comment]
- 更新下版本吧

```
dependencies:
  flutter_smart_dialog: ^4.9.4
```

- 使用

```
SmartDialog.config.checkExist(tag: "test");
```

想了下，你说了每次点击之前的弹窗置顶，也比较好做；你只需要把开启和关闭动画关闭，然后点击的时候先关闭对应tag的弹窗，然重新打开一个弹窗就行了

**Comment by Dabbit-Chan** [comment]
> - 更新下版本吧
> 
> ```dart
> dependencies:
>   flutter_smart_dialog: ^4.9.4
> ```
> 
> - 使用
> 
> ```dart
> SmartDialog.config.checkExist(tag: "test");
> ```
> 
> 想了下，你说了每次点击之前的弹窗置顶，也比较好做；你只需要把开启和关闭动画关闭，然后点击的时候先关闭对应tag的弹窗，然重新打开一个弹窗就行了

感谢！我周一试一试。
至于弹窗置顶，这样操作不会充值里面的状态吗？要是不会的话可以试试，会的话那就没法了

**Comment by xdd666t** [comment]
这需要关闭的时候保存弹窗的数据，然后重新打开的时候，再将这些数据塞进去；可能也就一个对象就能完成的时候

**Comment by Dabbit-Chan** [comment]
思路已经有了，回去看看能不能完美实现。因为弹窗里的数据不多，主要是交互麻烦，得保存一下之前交互到了哪一步。

**Comment by Dabbit-Chan** [comment]
exist那个没问题。置顶那个我这边状态太复杂了，不好做就先没弄..
