### ISSUE TITLE
About cheking which dialog open

### ISSUE THREAD

**Issue by 92sajid110** [fluttercandies/flutter_smart_dialog#148]
Hello is there is a way,if not please implement it. i have added backbutton interceptor and in that i want to check if SmartDialog.show(tag:"temp") is open then close it first. and perform some task.
In simple words find open dialogs with tag.
SmartDialog.dismiss(tag:"temp") closes dialog but didn't perform specific task after closing this dialog.
NOTE:- all task is on different file of backbutton handler so onDismis is also work here

Thanks

**Comment by xdd666t** [comment]
- This feature is completed, you need to try this version

```
dependencies:
  flutter_smart_dialog: ^4.9.4
```

- usage

```
SmartDialog.config.checkExist(tag: "test");
```

**Comment by 92sajid110** [comment]
Thanks, a lot.

**Comment by 92sajid110** [comment]
Hello,
after adding this awesome feature, i have one more request i want to use this as bottom sheet,
I successfully created with alignment but want to add animations from bottom to top opening or a way to convert container bottom sheet dialog.
Thanks

**Comment by xdd666t** [comment]
- You can look at this attribute

<img width="1326" alt="image" src="https://github.com/fluttercandies/flutter_smart_dialog/assets/35656085/86a1aa80-92a4-485c-b3b0-8f29539f690a">
