### ISSUE TITLE
LateInitializationError: Field 'contextAttach' has not been initialized.

### ISSUE THREAD

**Issue by tangbing** [fluttercandies/flutter_smart_dialog#150]
### 版本信息
- Flutter版本：3.13.0
- flutter_smart_dialog版本：^4.9.4

### 描述bug/需求
`         Positioned(
            top: 21.w,
            right: 12.w,
            child: GestureDetector(
                onTap: () {
                  print('aaaaa');
                  if (context != null) {
                    print(context);
                    SmartDialog.showAttach(
                      targetContext: context,
                      usePenetrate: true,
                      clickMaskDismiss: true,
                      alignment: Alignment.bottomCenter,
                      builder: (_) {
                        return Container(
                            width: 100, height: 100, color: Colors.red);
                      },
                    );
                  }
                },
                child: Image.asset(AssetsImages.mineDynamicMoreCover,
                    width: 24.w, height: 24.w)),
          )`
提示
项目用了getx，点击报错LateInitializationError: Field 'contextAttach' has not been initialized. 是我用的不对吗？

### 问题demo
‘’‘
import 'package:flutter/material.dart';
import 'package:flutter_smart_dialog/flutter_smart_dialog.dart';
import 'package:get/get.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:huachao/common/routers/pages.dart';
import 'package:huachao/pages/activityList/index.dart';
import 'package:huachao/pages/login/index.dart';
import 'package:huachao/pages/splash/index.dart';

import 'common/routers/names.dart';
import 'common/utils/keyboard_utils.dart';
import 'pages/myTicket/index.dart';
void main() async  {
  await ScreenUtil.ensureScreenSize();
  runApp( MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    
    return GetMaterialApp(
      theme: ThemeData(fontFamily: 'PingFang'),
      getPages: RoutePages.list,
      debugShowCheckedModeBanner: false,
      defaultTransition: Transition.rightToLeft,//默认转场动画
      initialRoute: RouteNames.Initial,
      initialBinding: SplashBinding(),
      home: const SplashPage(),
      /// SmartDialog
      navigatorObservers: [FlutterSmartDialog.observer],
      builder: (context, child) {
        //设置尺寸（填写设计中设备的屏幕尺寸）如果设计基于360dp * 690dp的屏幕
        ScreenUtil.init(context, designSize: const Size(375, 812));
        FlutterSmartDialog.init();

        return Scaffold(
        // Global GestureDetector that will dismiss the keyboard
        body: GestureDetector(
          onTap: () {
            KeyboardUtils.hideKeyboard(context);
          },
          child: child,
        )
        );
      },
    );
  }

}
’‘’

**Comment by xdd666t** [comment]
- 请严格按照文档初始化：https://juejin.cn/post/7026150456673959943#heading-0

![image](https://github.com/fluttercandies/flutter_smart_dialog/assets/35656085/bc91ef02-5123-48c5-a053-6630240a7a68)

**Comment by tangbing** [comment]
`import 'package:flutter/material.dart';
import 'package:flutter_smart_dialog/flutter_smart_dialog.dart';
import 'package:get/get.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:huachao/common/routers/pages.dart';
import 'package:huachao/pages/activityList/index.dart';
import 'package:huachao/pages/login/index.dart';
import 'package:huachao/pages/splash/index.dart';

import 'common/routers/names.dart';
import 'common/utils/keyboard_utils.dart';
import 'pages/myTicket/index.dart';
void main() async  {
  await ScreenUtil.ensureScreenSize();
  runApp( MyApp());
}


class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    
    return GetMaterialApp(
      theme: ThemeData(fontFamily: 'PingFang'),
      getPages: RoutePages.list,
      debugShowCheckedModeBanner: false,
      defaultTransition: Transition.rightToLeft,//默认转场动画
      initialRoute: RouteNames.Initial,
      initialBinding: SplashBinding(),
      home: const SplashPage(),
      /// SmartDialog
      navigatorObservers: [FlutterSmartDialog.observer],

      builder: FlutterSmartDialog.init(builder: _builder),

    );
  }

  Widget _builder(BuildContext context, Widget? child) {
    //设置尺寸（填写设计中设备的屏幕尺寸）如果设计基于360dp * 690dp的屏幕
    ScreenUtil.init(context, designSize: const Size(375, 812));
    return Scaffold(
        // Global GestureDetector that will dismiss the keyboard
        body: GestureDetector(
      onTap: () {
        KeyboardUtils.hideKeyboard(context);
      },
      child: child,
    ));
  }
}`
还是不行
<img width="1374" alt="截屏2023-09-02 18 20 12" src="https://github.com/fluttercandies/flutter_smart_dialog/assets/11678386/89862cb8-4d53-42ff-8921-aea9048b3e5d">

**Comment by xdd666t** [comment]
你给这种demo，让我怎么帮你排查问题？各种三方库的使用，我知道你用的是什么版本？

如果你想解决这个问题，给个简化demo代码，复制到main.dart里是可以直接执行；这个简化demo的压缩包

如果还是这种乱七八糟且不全的demo代码，我会直接关闭这个issue

**Comment by tangbing** [comment]
,不要意思，之前有些事情，demo已经弄好了，大佬可以可以看看，https://github.com/tangbing/test_Demo.git

**Comment by tangbing** [comment]
> ,不好意思，之前有些事情，demo已经弄好了，大佬可以可以看看，[https://github.com/tangbing/test_Demo.git，点击下面地方，调用SmartDialog.showAttach()方法](https://github.com/tangbing/test_Demo.git%EF%BC%8C%E7%82%B9%E5%87%BB%E4%B8%8B%E9%9D%A2%E5%9C%B0%E6%96%B9%EF%BC%8C%E8%B0%83%E7%94%A8SmartDialog.showAttach()%E6%96%B9%E6%B3%95)
> ![image](https://user-images.githubusercontent.com/11678386/270091185-2d0d7c21-b219-4d2e-b84e-a33cae0bb56e.png)
> ![image](https://user-images.githubusercontent.com/11678386/270091265-3bd3269d-b5ce-413d-96e4-2689209dd7a4.png)

**Comment by xdd666t** [comment]
- itemBuilder中的context是SliverChildBuilderDelegate提供，正常方式无法解析，而且就算能解析，你用这个context解析的位置肯定是不对的
- 这样写就行了
<img width="773" alt="image" src="https://github.com/fluttercandies/flutter_smart_dialog/assets/35656085/cfdd4b90-663c-4a29-9734-534846d83630">
- 需要使用指定widget的context，弹窗才能从对应widget位置出来；不是随便塞个context就行了，建议你看看这些使用demo吧：https://xdd666t.github.io/flutter_use/web/index.html#/smartDialog?dialogType=AttachDialogLocation
