### ISSUE TITLE
SmartDialog.showLoading(msg: '加载中', backDismiss: false);失败

### ISSUE THREAD

**Issue by shenglintang** [fluttercandies/flutter_smart_dialog#152]
### 版本信息
- Flutter版本：3.0.0
- flutter_smart_dialog版本：4.9.4

调用SmartDialog.showLoading(msg: '加载中', backDismiss: false);显示了对话框
然后调用SmartDialog.dismiss();关闭对话框
马上又调用SmartDialog.showLoading(msg: '加载中', backDismiss: false);对话框显示不出来

**Comment by xdd666t** [comment]
dismiss是个耗时方法，请await SmartDialog.dismiss()再调用，不然会把第二次调用的也关闭掉
