### ISSUE TITLE
SmartDialog LateInitializationError: Field 'contextAttach' has not been initialized.

### ISSUE THREAD

**Issue by tangbing** [fluttercandies/flutter_smart_dialog#153]
已经添加demo，https://github.com/fluttercandies/flutter_smart_dialog/issues/150#issuecomment-1732229015，帮忙看一下问题，谢谢

**Comment by tangbing** [comment]
> ,不好意思，之前有些事情，demo已经弄好了，大佬可以可以看看，[https://github.com/tangbing/test_Demo.git，点击下面地方，调用SmartDialog.showAttach()方法](https://github.com/tangbing/test_Demo.git%EF%BC%8C%E7%82%B9%E5%87%BB%E4%B8%8B%E9%9D%A2%E5%9C%B0%E6%96%B9%EF%BC%8C%E8%B0%83%E7%94%A8SmartDialog.showAttach()%E6%96%B9%E6%B3%95)

**Comment by xdd666t** [comment]
- itemBuilder中的context是SliverChildBuilderDelegate提供，正常方式无法解析，而且就算能解析，你用这个context解析的位置肯定是不对的

- 需要使用指定widget的context，弹窗才能从对应widget位置出来；不是随便塞个context就行了，建议你看看这些使用demo吧：https://xdd666t.github.io/flutter_use/web/index.html#/smartDialog?dialogType=AttachDialogLocation

- 这样写就行了

<img width="773" alt="image" src="https://github.com/fluttercandies/flutter_smart_dialog/assets/35656085/cfdd4b90-663c-4a29-9734-534846d83630">
