### ISSUE TITLE
 TextField 无法弹出键盘

### ISSUE THREAD

**Issue by bingoHams** [fluttercandies/flutter_smart_dialog#155]
### 版本信息
- Flutter版本：[v3.13.2]
-  flutter_smart_dialog: ^4.9.4

### TextField
使用了 go_router 的TypedGoRoute 自动生成router 文件后 无法弹出键盘

### 问题demo
这是 router 生成代码
@TypedGoRoute<SettingRoute>(path: SettingRoute.path)
class SettingRoute extends GoRouteData {
  const SettingRoute();
  static const path = '/setting';

  @override
  Widget build(BuildContext context, GoRouterState state) {
    return  TestPage();
  }
}

这是大佬的demo 源码
class TestPage extends StatelessWidget {
  const TestPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('设置'),
      ),
      body: Container(
        alignment: Alignment.center,
        child: ElevatedButton(
          onPressed: () => _onTap(context),
          child: const Text("弹窗"),
        ),
      ),
    );
  }

  void _onTap(BuildContext context) {
    SmartDialog.show(
      onDismiss: () => FocusScope.of(context).requestFocus(),
      builder: (_) => const TestDialog(),
    );
  }
}

class TestDialog extends StatefulWidget {
  const TestDialog({Key? key}) : super(key: key);

  @override
  State<TestDialog> createState() => _TestDialogState();
}

class _TestDialogState extends State<TestDialog> {
  final _focusNode = FocusNode();

  @override
  void initState() {
    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
      _focusNode.requestFocus();
    });

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedPadding(
      padding: MediaQuery.of(context).viewInsets,
      duration: const Duration(milliseconds: 100),
      child: Container(
        height: 100,
        width: 300,
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(10),
        ),
        alignment: Alignment.center,
        child: TextField(focusNode: _focusNode),
      ),
    );
  }
}

**Comment by bingoHams** [comment]
router 初始化代码
  ref.watch(asyncThemeProvider.future).then((value) => setState(() {
          model = value;
        }));
    final notifier = ref.watch(routerListenableProvider.notifier);

    final key = useRef(GlobalKey<NavigatorState>(debugLabel: 'routerKey'));
    final router = useMemoized(
      () => GoRouter(
        navigatorKey: key.value,
        refreshListenable: notifier,
        initialLocation: SplashRoute.path,
        debugLogDiagnostics: true,
        routes: $appRoutes,
        observers: [FlutterSmartDialog.observer],
        redirect: notifier.redirect,
      ),
      [notifier],
    );
    return MaterialApp.router(
      routerConfig: router,
      title: 'testDialog',
      theme: ThemeData(
        colorSchemeSeed: Colors.teal,
        useMaterial3: true,
        brightness: model == "light" ? Brightness.light : Brightness.dark,
      ),
      // navigatorObservers: [FlutterSmartDialog.observer],
      // here
      builder: FlutterSmartDialog.init(),
    );

**Comment by xdd666t** [comment]
不解决其它框架奇怪用法导致的SmartDialog问题，目前没这个精力，自己想办法解决吧
