### ISSUE TITLE
弹不出Toast和Dialogue

### ISSUE THREAD

**Issue by xinchengbian** [fluttercandies/flutter_smart_dialog#156]
### 版本信息
- Flutter版本：stable-3.7.6
- flutter_smart_dialog版本：4.9.4

### 描述bug/需求
偶尔会出现任何toast和dialog都弹不出来的问题，没有任何报错，只能重新启动App才能好

### 问题demo
实在整不出demo，就想问问大家有没有遇到过类似的情况，或者有没有建议的排查、解决方案

**Comment by xdd666t** [comment]
如果在开发时出现这种情况，你可以Debug排查下，或者打一些日志

如果有连续开关dialog的需求，需要注意使用 await SmartDialog.dismiss()，dismiss()是个耗时方法，不这样写，有可能误关立马调用的dialog

**Comment by xinchengbian** [comment]
> 如果在开发时出现这种情况，你可以Debug排查下，或者打一些日志
> 
> 如果有连续开关dialog的需求，需要注意使用 await SmartDialog.dismiss()，dismiss()是个耗时方法，不这样写，有可能误关立马调用的dialog

确实是有连续开关 attach 类型的 dialog，dismiss 是有 await 的，而且能走到 await SmartDialog.showAttach 的后面，没有任何异常抛出，就是 targetBuilder 没有走

**Comment by xdd666t** [comment]
Debug  showAttach内部看看吧，看看为啥没走

**Comment by xinchengbian** [comment]
> Debug showAttach内部看看吧，看看为啥没走

这就是最恶心的地方了，debug一次都复现不了，release包复现频率还挺高

**Comment by xdd666t** [comment]
你可以直接改动SmartDialog存档源码，内部多打一些日志，打个Release包，在你的业务环境尝试复现看看，然后观察观察日志

**Comment by xinchengbian** [comment]
> 你可以直接改动SmartDialog存档源码，内部多打一些日志，打个Release包，在你的业务环境尝试复现看看，然后观察观察日志

嗯，准备这样做了，多谢耐心解答，稍后反馈结果

**Comment by xinchengbian** [comment]
源码打日志没有定位到具体问题，偶尔发现刷新MaterialApp或者弹出键盘可以解决，因为当时急着上线，做法是每次调showAttach之前切换了一下主题（实际没做主题切换功能），待到后面时间充裕再慢慢看，问题就暂时关闭了
