### ISSUE TITLE
发现个bug

### ISSUE THREAD

**Issue by GeekTR** [fluttercandies/flutter_smart_dialog#157]
### 版本信息
- Flutter版本：[举例：v2.10.4]
- flutter_smart_dialog版本：[举例：v3.4.1]

### 描述bug/需求
请准确描述bug或需求
使用 SmartDialog.showLoading 后，按返回键 Dialog 不会消失，并且页面会关闭。
经过排查，似乎是 DialogKit.checkExist() 有问题，传入的 dialogTypes 是个集合，但是会在31行直接返回，因为集合里面类型包含SmartAllDialogType.custom, 这样子就不会判断是否存在 Loading 的Dialog了。

### 问题demo

<img width="865" alt="image" src="https://github.com/fluttercandies/flutter_smart_dialog/assets/13369103/cea9eed3-f3b6-4ef2-919c-0ba3854d544d">

**Comment by xdd666t** [comment]
感谢反馈，虽然你说的现象我没法复现，但是逻辑确实存在这个问题

你提交的pr里面代码存在一点问题，结尾应该需要返回result，我本地直接改了提交了，已经发布了新版本，你可以试试

```
dependencies:
  flutter_smart_dialog: ^4.9.5
```

**Comment by GeekTR** [comment]
好的谢谢，我这边测试修改后的代码没问题了
