### ISSUE TITLE
This WholeThing Is Not Working

### ISSUE THREAD

**Issue by asifakhtar98** [fluttercandies/flutter_smart_dialog#16]
SmartDialog.instance.config
    ..backDismiss = true;

**Comment by xdd666t** [comment]
hi，this param is already invalid，and you also not need use it

- I have refactored the underlying code，please use version 3.0

```dart
dependencies:
  flutter_smart_dialog: ^3.0.0
```

- easy use it

```dart
var custom = Container(
    height: 80,
    width: 180,
    decoration: BoxDecoration(
        color: Colors.black,
        borderRadius: BorderRadius.circular(20),
    ),
    alignment: Alignment.center,
    child: Text('easy custom dialog', style: TextStyle(color: Colors.white)),
);
// here
SmartDialog.show(widget: custom, isLoadingTemp: false);
```

![dialogEasy](https://camo.githubusercontent.com/ae3308f93ad4ce86a888d134cf8ebf4c861469fa0d93cc939a90ca85d9c03eeb/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f786464363636742f4d7944617461406d61737465722f7069632f666c75747465722f626c6f672f32303231313130323233323832312e676966)

- please check the readme for details

**Comment by xdd666t** [comment]
- you can check the readme again, it will definitely solve your doubts
- 
https://github.com/fluttercandies/flutter_smart_dialog/blob/master/README.md

**Comment by xdd666t** [comment]
If you still have questions after reading the readme，you can reopen this issue
