### ISSUE TITLE
isExistLoading方法失效

### ISSUE THREAD

**Issue by resultto** [fluttercandies/flutter_smart_dialog#160]
### 版本信息
- Flutter版本：v3.13.9
- flutter_smart_dialog版本：v4.9.0

### 描述bug/需求
用的flutter_user_evdo的demo，里面判断全局dialog的方法isExistLoading失效了。直接用checkExist替换，自定义dialog情况下，返回的始终是false，没法判断是否存在。

### 问题demo
flutter_user_evdo demo的http文件下替换isExistLoading为checkExist()可复现

**Comment by xdd666t** [comment]
- 试下新版本吧，4.9.4版本逻辑处理的有点问题

```
dependencies:
  flutter_smart_dialog: ^4.9.5
```
