### ISSUE TITLE
SmartDialog.show() 在特定情况没有显示

### ISSUE THREAD

**Issue by wubao100** [fluttercandies/flutter_smart_dialog#161]
### 版本信息
- Flutter版本：3.13.4
-  flutter_smart_dialog: ^4.9.5+1

### 描述bug/需求
app有无权限这种功能，注销后我是通过MyApp.navigatorKey.currentContext返回首页（因为不能确定什么时候无权限，只能接口拦截），这种情况返回首页SmartDialog.show()就无法显示了，具体报错如下：

app-监控
错误信息：Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a r
堆栈信息：#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4558:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4572:6)
#2      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:4684:12)
#3      LookupBoundary.findAncestorStateOfType (package:flutter/src/widgets/lookup_boundary.dart:166:13)
#4      Overlay.maybeOf (package:flutter/src/widgets/overlay.dart:515:26)
#5      Overlay.of (package:flutter/src/widgets/overlay.dart:465:34)
#6      overlay (package:flutter_smart_dialog/src/kit/view_utils.dart:19:55)
#7      CustomDialog._pushDialog.<anonymous closure> (package:flutter_smart_dialog/src/custom/custom_dialog.dart:279:9)
#8      ViewUtils.addSafeUse (package:flutter_smart_dialog/src/kit/view_utils.dart:10:15)
#9      CustomDialog._pushDialog (package:flutter_smart_dialog/src/custom/custom_dialog.dart:265:15)
#10     CustomDialog._handleMustO
设备信息：{id: RP1A.200720.011, host: non-pangu-pod-4rjwz, tags: release-keys, type: user, model: 21091116AC, board: evergo, brand: Redmi, device: evergo, product: evergo, display: CUST_evergo, hardware: mt6833, androidId: dc17f14f56f35e8b, bootloader: unknown, version: {baseOS: , sdkInt: 30, release: 11, codename: REL, incremental: V12.5.13.0.RGBCNXM, previewSdkInt: 0, securityPatch: 2023-02-01}, fingerpri
时间：2023-11-23T17:28:06.672
版本号：1.0.0
网络状态：ConnectivityResult.wifi

**Comment by xdd666t** [comment]
感觉你这个弄个下一帧的延时show就行了（addPostFrameCallback）

如果还是不行的话，给下能复现的简化demo吧
