### ISSUE TITLE
bindPage为true的时候，出现页面跳转，此时，onDismiss()方法不会触发

### ISSUE THREAD

**Issue by chensimin920511** [fluttercandies/flutter_smart_dialog#162]
bindPage为true的时候，出现页面跳转，此时，onDismiss()方法不会触发，但是dialog已经跟随page而消失了

**Comment by xdd666t** [comment]
只是隐藏了，你回到这个页面的时候还会出现，并不是关闭了

**Comment by chensimin920511** [comment]
路由使用push的时候确实是隐藏的，但是如果使用的是pushUntil()，或者pushNamedAndRemoveUntil()这种，会把之前的page出栈的方式，此时onDismiss()也是不会触发的

**Comment by xdd666t** [comment]
- 试下新版本

```
dependencies:
  flutter_smart_dialog: ^4.9.5+2
```

**Comment by chensimin920511** [comment]
晚点check一下，感谢fix




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fluttercandies/flutter_smart_dialog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月16日(星期六) 下午5:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fluttercandies/flutter_smart_dialog] bindPage为true的时候，出现页面跳转，此时，onDismiss()方法不会触发 (Issue #162)





  
试下新版本
  dependencies:   flutter_smart_dialog: ^4.9.5+2
