### ISSUE TITLE
输入框顶起问题

### ISSUE THREAD

**Issue by resultto** [fluttercandies/flutter_smart_dialog#163]
### 版本信息
- Flutter版本：3.20
- flutter_smart_dialog版本：4.9.5

### 描述bug/需求
使用SmartDialog.showAttach做评论弹出框的功能，遇到一个问题。输入框无法顶起弹出框。
这种需要被输入框顶起的需求是没法用吗

**Comment by xdd666t** [comment]
https://github.com/fluttercandies/flutter_smart_dialog/issues/35
