### ISSUE TITLE
需求：是否可以针对bindWidget支持一下不在栈顶的页面弹框

### ISSUE THREAD

**Issue by bunny-pu** [fluttercandies/flutter_smart_dialog#164]
### 版本信息
- Flutter版本：无关
- flutter_smart_dialog版本：无关

### 描述bug/需求
需求：在A页面跳到B页面后，A页面网络请求回来，需要展示一个弹框。
预期是B页面展示在栈顶的时候不展示弹框，B退到A页面后弹框再出现。
尝试使用设置bindWidget为A页面的context。无法实现预期的交互

查看代码发现问题在于，pop的时候会检查当前的route是否符合以及会把这个弹框remove掉

### 问题demo
我理解以上的场景在业务中是经常会出现的。是否可以针对bindWidget改造一下支持这种需求呢？

**Comment by bunny-pu** [comment]
目前试着在大佬的代码上做了一点小修改，可以满足```不在栈顶的页面弹框```
1. 进入一个页面就记录当前的router，并在弹框的时候传入router
2. 去掉MonitorWidgetHelper._internal()中的限制```if (monitorDialogQueue.isEmpty || prohibitMonitor) {
        return;
      }```

**Comment by xdd666t** [comment]
看了下，当前版本就支持你说的功能，你把bindPage设置成false就行了
