### ISSUE TITLE
alignment参数失效的问题

### ISSUE THREAD

**Issue by LiJiyaoisrunning** [fluttercandies/flutter_smart_dialog#166]
showAttach的时候，接收的alignment参数，类型是AlignmentGeometry类型，但是在实际渲染时，只判断了其子类Alignment的几种情况，在需要考虑国际化的场景中，比如我传入的参数是AlignmentDirectional.centerStart，这种情况下，这个alignment值就会失效。

**Comment by xdd666t** [comment]
底层使用Alignment绝对的对齐方式，你说的这种情况，start取决于布局的方向，可能在左在右，底层不合适处理这种情况，你上层自己做明确的类型转换吧

**Comment by LiJiyaoisrunning** [comment]
如果是这样的话，应该在接收参数的时候做限制吧，不应该接收AligmentGeometry类型，而是设置接收Alignment类型，不然会对使用者造成误导。
