### ISSUE TITLE
按返回键如何保留dialog但是pop page呢

### ISSUE THREAD

**Issue by shingohu** [fluttercandies/flutter_smart_dialog#168]
### 版本信息
- Flutter版本：[举例：v2.10.4]
- v3.16.5
- flutter_smart_dialog版本：[举例：v3.4.1]
v4.9.6
### 描述bug/需求
按返回键如何保留dialog但是pop page呢?
/// [backDismiss]：true（返回事件将关闭dialog，但是不会关闭页面），
/// false（返回事件不会关闭loading，也不会关闭页面），你仍然可以使用dismiss方法来关闭dialog

**Comment by xdd666t** [comment]
- 这个

![image](https://github.com/fluttercandies/flutter_smart_dialog/assets/35656085/ed985e84-22fe-4067-acd8-ade3b9613f6b)
