### ISSUE TITLE
Android真机开启Impeller使用SmartDialog.show设置maskWidget为高斯模糊BackdropFilter弹窗不显示（显示异常）

### ISSUE THREAD

**Issue by davidche1116** [fluttercandies/flutter_smart_dialog#169]
### 版本信息
- Flutter版本：3.16.5
- flutter_smart_dialog版本：4.9.6

### 描述bug/需求
Android开启Impeller真机测试，发现使用使用SmartDialog.show设置maskWidget为BackdropFilter弹窗不显示（显示异常）
在模拟器中正常、不开启Impeller正常。仅在Android真机开启Impeller弹窗不显示。
Android开启Impeller：https://flutter.cn/docs/perf/impeller
在AndroidManiest.xml文件中添加：
`<meta-data
    android:name="io.flutter.embedding.android.EnableImpeller"
    android:value="true" />
`
有问题的maskWidget：
`maskWidget: BackdropFilter(
          filter: ImageFilter.blur(
            sigmaX: 5,
            sigmaY: 5,
          ),
          child: Container(
            color: Colors.black.withOpacity(0.5),
          ),
        )`

### 问题demo
使用官方demo修改_show函数
`    SmartDialog.show(
        builder: (_) {
          return Container(
            height: 80,
            width: 180,
            decoration: BoxDecoration(
              color: Colors.black,
              borderRadius: BorderRadius.circular(10),
            ),
            alignment: Alignment.center,
            child: const Text(
              'easy custom dialog',
              style: TextStyle(color: Colors.white),
            ),
          );
        },
        // 直接使用Container这样是正常的
        // maskWidget: Container(
        //   color: Colors.black.withOpacity(0.5),
        // )
        // 使用高斯模糊BackdropFilter是异常的
        maskWidget: BackdropFilter(
          filter: ImageFilter.blur(
            sigmaX: 5,
            sigmaY: 5,
          ),
          child: Container(
            color: Colors.black.withOpacity(0.5),
          ),
        )
        );`

**Comment by xdd666t** [comment]
你把SmartDialog.show改成系统的showDialog能正常显示吗？

**Comment by davidche1116** [comment]
改成系统的能正常显示，但系统的没法设置自定义遮罩背景，只能设置一个背景颜色，SmartDialog.show的不设置模糊背景也能正常显示。
demo在这里：
[demo.zip](https://github.com/fluttercandies/flutter_smart_dialog/files/13869997/demo.zip)

**Comment by xdd666t** [comment]
看了下，这应该是Impeller模式下的bug，高斯模糊和动画组件一起使用，会有闪屏的现象

- 你先把动画关掉试试吧：  nonAnimationTypes: [SmartNonAnimationType.maskClose_nonAnimation],

```dart
SmartDialog.show(
  builder: (_) {
    return Container(
      height: 80,
      width: 180,
      decoration: BoxDecoration(
        color: Colors.black,
        borderRadius: BorderRadius.circular(10),
      ),
      alignment: Alignment.center,
      child: const Text(
        'easy custom dialog',
        style: TextStyle(color: Colors.white),
      ),
    );
  },
  // 直接使用Container这样是正常的
  // maskWidget: Container(
  //   color: Colors.black.withOpacity(0.5),
  // )
  // 使用高斯模糊BackdropFilter是异常的
  nonAnimationTypes: [SmartNonAnimationType.maskClose_nonAnimation],
  maskWidget: BackdropFilter(
    filter: ImageFilter.blur(
      sigmaX: 5,
      sigmaY: 5,
    ),
    child: Container(
      color: Colors.black.withOpacity(0.5),
    ),
  ),
);
```
