### ISSUE TITLE
优化

### ISSUE THREAD

**Issue by z624821876** [fluttercandies/flutter_smart_dialog#17]
版本3.0 
1. 需要增加一个关闭所有dialog的方法。
2. 由于Overlayentry 被单例持有 不会更新，导致flutter inspector中的selelct widget mode功能报错，建议在FlutterSmartDialog，initState里面 重新创建所有overlayentry

**Comment by xdd666t** [comment]
关于flutter inspector报错的问题，你可以会产生报错的步骤详细描述下吗？最好填写关键步骤截图和报错截图。

我这边试了flutter inspector里面的 Select Widget Mode是没有报错的

**Comment by xdd666t** [comment]
关闭所有dialog的功能已加，使用依然使用dismiss方法，增加了一个status状态

**Comment by xdd666t** [comment]
- 关闭所有dialog功能已增加，如有需求，请升至：3.0.1 版本

![image](https://user-images.githubusercontent.com/35656085/140614339-c5f4a9d2-9f4c-4ef9-aa6d-28acfdd350e8.png)
