### ISSUE TITLE
弹窗内容交互可变性

### ISSUE THREAD

**Issue by Smeegol** [fluttercandies/flutter_smart_dialog#170]
使用SmartDialog.show(builder: ...)来添加自定义单选框内容的弹窗，无法进行切换修改，交互时失去了可变性，即使绑定了变量，setState({})了，也是不行，请问有无解决方法？谢谢

**Comment by xdd666t** [comment]
builder里面，放个你自己自定义StatefulWidget

**Comment by Smeegol** [comment]
@xdd666t 以下是我创建的单选框内容控件
```
class ReportAlertContentWidget extends StatefulWidget {
  final int selectedIndex;
  final Function(int) onTap;

  const ReportAlertContentWidget({
    super.key,
    required this.selectedIndex,
    required this.onTap,
  });

  @override
  State<ReportAlertContentWidget> createState() => _ReportAlertContentWidgetState();
}

class _ReportAlertContentWidgetState extends State<ReportAlertContentWidget> {
  @override
  Widget build(BuildContext context) {
    return ...;
  }
}
```
参照的[这个链接](https://stackoverflow.com/questions/64728069/flutter-accessing-state-class-variable-of-statefulwidget-from-a-different-class)，`ReportAlertContentWidget`类似里面的`FirstClass`.
外部使用`ReportAlertContentWidget`时，传入外部的`selectedIndex`和`onTap`，在点击切换单选框时，确实能修改此外部的`selectedIndex`值。但是，在点击切换单选框时，通过`onTap`使得外部的`selectedIndex`发生改变，弹窗中的`ReportAlertContentWidget`却未改变，因为其`selectedIndex`是`final`的，导致其UI不会联动变化 :(

**Comment by Smeegol** [comment]
@xdd666t 后来为了联动改变，去掉`selectedIndex`的`final`修饰符、去掉构造方法的`const`修饰符、添加`// ignore: must_be_immutable`注释，后两个都是为了通过编译而添加的，如下：
```
// ignore: must_be_immutable
class CallReportAlertDialogContent extends StatefulWidget {
  int selectedIndex;
  final Function(int) onTap;

  CallReportAlertDialogContent({
    super.key,
    required this.selectedIndex,
    required this.onTap,
  });

  @override
  State<CallReportAlertDialogContent> createState() => _CallReportAlertDialogContentState();
}
```
最终达到了目的，但知道这种方式不优雅，不知大佬有什么推荐做法，谢谢

**Comment by xdd666t** [comment]
- 你这是什么操作，为啥onTap把index传给外部改变selectedIndex？？？
 - 我觉得传入的stf的可以叫initSelectedIndex，传给_ReportAlertContentWidgetState
 - 然后内部改变的数据直接在_ReportAlertContentWidgetState中用局部变量解决，直接刷新

你如果在外部需要感知selectedIndex，可以用onTap传出去，刷新的时候内部局部变量记录下解决，不需要再传进去；或者你非要传进去，就需要在外部刷新ReportAlertContentWidget，确保每次改变后整个ReportAlertContentWidget都能被刷新
