### ISSUE TITLE
某种情况下SmartDialog.showLoading()会被立马关闭

### ISSUE THREAD

**Issue by lzxyh0227** [fluttercandies/flutter_smart_dialog#171]
### 版本信息
- Flutter版本：3.7.12
- flutter_smart_dialog版本：4.9.0

### 描述bug/需求
SmartDialog.showLoading()和SmartDialog.dismiss()包裹住某段正常代码，上一个SmartDialog.dismiss()执行完立马再执行另一个SmartDialog.showLoading()，新的loading也会dismiss，SmartDialog.showLoading()方法也没有tag参数

### 问题demo
SmartDialog.showLoading();
await Future.delayed(const Duration(milliseconds: 2000));
SmartDialog.dismiss();
SmartDialog.showLoading();

**Comment by xdd666t** [comment]
- dismiss()是个耗时方法
SmartDialog.showLoading();
await Future.delayed(const Duration(milliseconds: 2000));
await SmartDialog.dismiss();
SmartDialog.showLoading();

**Comment by 944095635** [comment]
`    SmartDialog.showLoading();
    await Future.delayed(const Duration(milliseconds: 2000));
    await SmartDialog.dismiss();
    SmartDialog.showLoading(msg: "no");`

不对，这样看不到no，必须要 dismiss后 await 250ms 才可以

**Comment by xdd666t** [comment]
- 试下新版本 @944095635 

```dart
dependencies:
  flutter_smart_dialog: ^4.9.7+6
```

**Comment by 944095635** [comment]
我本地版本是
  flutter_smart_dialog: ^4.9.7+2       #Loading 动画&提示
  
  好的，我试试

**Comment by 944095635** [comment]
好了，已经没问题了，感谢。
