### ISSUE TITLE
可否自己处理返回事件

### ISSUE THREAD

**Issue by pangyu646182805** [fluttercandies/flutter_smart_dialog#176]
我的弹窗点击返回的时候需要自己做个动画效果 我试过backDismiss设为false 然后使用PopScope但是没有效果 请问有没有方法我自己处理这个返回事件呢？

**Comment by xdd666t** [comment]
需要自定义动画，请参考：https://github.com/fluttercandies/flutter_smart_dialog/issues/165

**Comment by pangyu646182805** [comment]
谢谢 已解决
