### ISSUE TITLE
DateRangePicker被遮住

### ISSUE THREAD

**Issue by roger66** [fluttercandies/flutter_smart_dialog#177]
### 版本信息
- Flutter版本：3.16.9
- flutter_smart_dialog版本：v4.9.1-v4.9.6

SmartDialog.show以后要弹出一个时间选择器，调用系统showDateRangePicker方法，结果被SmartDialog遮住了，4.9.0版本之前是不会的

**Comment by roger66** [comment]
![1709175690601](https://github.com/fluttercandies/flutter_smart_dialog/assets/16676365/fed269ee-a00b-4288-ac58-ee791db18eee)

**Comment by xdd666t** [comment]
useSystem设置为ture
