### ISSUE TITLE
在app内部展示web view时，dialog的事件会穿透到webview（点击元素而不是遮罩），设置了各种方法均无法避免

### ISSUE THREAD

**Issue by 540765** [fluttercandies/flutter_smart_dialog#178]
### 版本信息
- Flutter版本：3.7.10
- flutter_smart_dialog版本：^4.9.3+2

### 描述bug/需求
在app内部展示web view时，dialog的事件会穿透到webview（点击元素而不是遮罩），设置了各种方法均无法避免

**Comment by xdd666t** [comment]
给了最简demo

**Comment by ArturoRen** [comment]
来补充一下，此问题依然存在，目前的解决办法是在dialog下覆盖一层空白（透明）web view即可，此问题应该是flutter的问题
