### ISSUE TITLE
通过smartDialog.show的形式自定义的widget上有输入框键盘遮挡问题。

### ISSUE THREAD

**Issue by Zhuzhua** [fluttercandies/flutter_smart_dialog#179]
通过查阅历史issues，https://github.com/fluttercandies/flutter_smart_dialog/issues/35 ，添加了 padding: MediaQuery.of(context).viewInsets,  但是当textfield的输入框预期不会被盖住的时候（处于键盘上方），也会往上移动，预期是输入框最下端移动到和键盘上端持平

**Comment by xdd666t** [comment]
这和SmartDialog无关，上面的我只是提供了一个解决布局被挡住的方案，在flutter自带的showDialog也适用

你的这种需求，需要你自己去计算自己的布局位置和键盘位置，再动态刷新自己的布局位置

**Comment by Zhuzhua** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Zhuzhua** [comment]
非smartDialog方式弹出的widget，比如系统的showGeneralDialog，不会遮挡键盘，也不需要计算

**Comment by xdd666t** [comment]
看上去是路由内部做了相关处理，SmartDialog本质是对overlay的封装，对键盘遮挡Widget布局的解决方法对他同样适用，例如 Scaffold的resizeToAvoidBottomInset设置为true,
