### ISSUE TITLE
fluent_ui库如何初始化smartdialog？

### ISSUE THREAD

**Issue by cjcj125125** [fluttercandies/flutter_smart_dialog#180]
### 版本信息
- Flutter版本：3.19.3
- flutter_smart_dialog版本：v4.9.6

### 描述bug/需求
最近使用fluent_ui开发桌面程序，初始化时候使用的是FluentApp.router而不是MaterialApp，请问我该如何初始化smartdialog？

**Comment by Dabbit-Chan** [comment]
1. 既然是`.router`的，那在`routerDelegate`总是会有地方放`FlutterSmartDialog.observer`的
2. `FluentApp.router`里也有`builder`，那就可以加上`FlutterSmartDialog.init`呀

**Comment by xdd666t** [comment]
主要的就是init和observe的处理，你按照楼上老哥说的试试就行了 @cjcj125125

**Comment by cjcj125125** [comment]
楼上大哥说的我试过了，但是routerDelegate需要的参数类型和FlutterSmartDialog.observer的类型不一样，你可以在官方demo上面试试看，官方demo main.dart地址：https://github.com/bdlukaa/fluent_ui/blob/master/example/lib/main.dart
感谢大佬的指点，抱拳.jpg

**Comment by cjcj125125** [comment]
补充一下，他的routerDelegate类型是RouterDelegate<Object>? ，但是FlutterSmartDialog.observer的类型是NavigatorObserver 不匹配的呀

**Comment by Dabbit-Chan** [comment]
RouterDelegate里面一般都会有一个入参叫observer，在observer里加FlutterSmartDialog.observer。如果没有的话他应该有提供addObserver的方法。

**Comment by Dabbit-Chan** [comment]
官方的demo用了GoRouter，如果你的项目没用到GoRouter或者不需要Navigator2.0那你完全不需要使用`FluentApp.route`，用`FluentApp`即可。说得更明白一点就是不需要完全照搬官方demo，他这个demo使用了很多第三方库，根据自己的需求来用fluent_ui就行。

**Comment by cjcj125125** [comment]
感谢您的指点，我也是用了go_router所以就照着他这个写了，入门阶段，很多不懂，感谢大佬指点，小弟感激万分
仰望高端玩家.jpg

**Comment by Dabbit-Chan** [comment]
如果你也用了`go_router`，那么在`GoRouter`里面有个`observers`参数，在里面加上`FlutterSmartDialog.observer`就行

**Comment by cjcj125125** [comment]
好的，非常感谢，我试试看

**Comment by cjcj125125** [comment]
那我将FlutterSmartDialog.init 方法放到FluentApp.router的build方法里面可以么？

**Comment by Dabbit-Chan** [comment]
```
builder: FlutterSmartDialog.init(
              builder: (context, child) {
                return Directionality(
                  textDirection: appTheme.textDirection,
                  child: NavigationPaneTheme(
                    data: NavigationPaneThemeData(
                      backgroundColor: appTheme.windowEffect !=
                          flutter_acrylic.WindowEffect.disabled
                          ? Colors.transparent
                          : null,
                    ),
                    child: child!,
                  ),
                );
              },
            ),
```

**Comment by cjcj125125** [comment]
我嵌套反了，大恩不言谢，请受小弟一拜 ， 感激涕零.jpg
