### ISSUE TITLE
isolate中弹窗无效，提示并未初始化，有没有什么在isolate中使用的方案

### ISSUE THREAD

**Issue by pp126** [fluttercandies/flutter_smart_dialog#182]
### 版本信息
- Flutter版本：[举例：v2.10.4]
- flutter_smart_dialog版本：[举例：v3.4.1]

### 描述bug/需求
请准确描述bug或需求

**Comment by xdd666t** [comment]
ui是无法在子isolate中操作的，你可以在子isolate中去通知主isolate操作相关ui
