### ISSUE TITLE
lastToast没有在overlayEntry.remove()的时候判断mounted，导致有几率报错

### ISSUE THREAD

**Issue by longqian1235** [fluttercandies/flutter_smart_dialog#185]
<img width="669" alt="image" src="https://github.com/fluttercandies/flutter_smart_dialog/assets/19204095/4a086739-4a7f-4f5e-baaa-c0d04b63ca6b">
<img width="559" alt="image" src="https://github.com/fluttercandies/flutter_smart_dialog/assets/19204095/08e2a007-4cb9-411e-9ec2-fc1aabc2b5b8">
<img width="590" alt="image" src="https://github.com/fluttercandies/flutter_smart_dialog/assets/19204095/2c757eef-4992-4479-b105-2ff7d9b5ec07">

**Comment by xietian0908** [comment]
![image](https://github.com/fluttercandies/flutter_smart_dialog/assets/64937500/a9cd47a7-0bcb-4f4b-a0aa-f8044bb72dbe)
同样的问题，会导致后面的弹框都不能使用

**Comment by xdd666t** [comment]
- 试试新版本吧

```dart
dependencies:
  flutter_smart_dialog: ^4.9.6+1
```

**Comment by xietian0908** [comment]
我这里没发现啥问题了
