### ISSUE TITLE
需求

### ISSUE THREAD

**Issue by LvJson** [fluttercandies/flutter_smart_dialog#186]
### 版本信息
- Flutter版本：[v3.16.5]
- flutter_smart_dialog版本：[v4.9.0+6]

### 描述bug/需求
需求场景是这样的：从A页面跳转到B页面之后，A页面里有个弹框在几秒钟之后才会弹出，但我不想让这个弹框出现在B页面。请问如何实现？我尝试使用过bindWidget，能实现上面的需求，但是每次从B页面返回到A页面时，这个弹框会自动关闭。

**Comment by xdd666t** [comment]
bindWidget设置为true，bindPage设置为false

**Comment by LvJson** [comment]
可以了，多谢！
