### ISSUE TITLE
release模式dialog完全出不来

### ISSUE THREAD

**Issue by git-maven** [fluttercandies/flutter_smart_dialog#190]
### 版本信息
- Flutter版本：3.19.5
- flutter_smart_dialog版本：4.9.7+4

### 描述bug/需求
debug模式下正常，release模式就无法弹出来了，要点几十下才出来，回退到4.9.6就正常
另外toast在使用last模式，在A页面弹出后，马上回退到B页面，会不消失

**Comment by xdd666t** [comment]
给下可复现问题，可运行的简化demo，你说的现象也录个视频上传下吧

**Comment by git-maven** [comment]
`class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      builder: FlutterSmartDialog.init(),
      navigatorObservers: [
        FlutterSmartDialog.observer
      ],
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        body: Center(
          child: GestureDetector(
            onTap: () {
              SmartDialog.show(
                tag: '11',
                builder: (context) {
                  return Center(
                    child: Container(
                      height: 300,
                      width: 300,
                      color: Colors.blue,
                    ),
                  );
                },
                animationType: SmartAnimationType.centerFade_otherSlide,
                backDismiss: true,
                keepSingle: true,
                debounce: true,
              );
            },
            child: Container(
              width: 200,
              height: 200,
              color: Colors.red,
            ),
          ),
        ),
      ),
    );
  }
}`

在release模式下，无法弹出dialog，只有当app回后台再回前台才能弹出

**Comment by git-maven** [comment]
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      builder: FlutterSmartDialog.init(),
      navigatorObservers: [
        FlutterSmartDialog.observer
      ],
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        body: Center(
          child: GestureDetector(
            onTap: () {
              SmartDialog.show(
                tag: '11',
                builder: (context) {
                  return Center(
                    child: Container(
                      height: 300,
                      width: 300,
                      color: Colors.blue,
                    ),
                  );
                },
                animationType: SmartAnimationType.centerFade_otherSlide,
                backDismiss: true,
                keepSingle: true,
                debounce: true,
              );
            },
            child: Container(
              width: 200,
              height: 200,
              color: Colors.red,
            ),
          ),
        ),
      ),
    );
  }
}



在release模式下，无法弹出dialog，只有当app回后台再回前台才能弹出

**Comment by git-maven** [comment]
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      builder: FlutterSmartDialog.init(),
      navigatorObservers: [
        FlutterSmartDialog.observer
      ],
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        body: Center(
          child: GestureDetector(
            onTap: () {
              SmartDialog.show(
                tag: '11',
                builder: (context) {
                  return Center(
                    child: Container(
                      height: 300,
                      width: 300,
                      color: Colors.blue,
                    ),
                  );
                },
                animationType: SmartAnimationType.centerFade_otherSlide,
                backDismiss: true,
                keepSingle: true,
                debounce: true,
              );
            },
            child: Container(
              width: 200,
              height: 200,
              color: Colors.red,
            ),
          ),
        ),
      ),
    );
  }
}


在release模式下，无法弹出dialog，只有当app回后台再回前台才能弹出

**Comment by git-maven** [comment]
发现在使用GestureDetector的时候才会出现这种问题，我换了FloatingActionButton就正常了

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      builder: FlutterSmartDialog.init(),
      navigatorObservers: [
        FlutterSmartDialog.observer
      ],
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        body: Center(
          child: FloatingActionButton(
            onPressed:(){
              SmartDialog.show(
                tag: '11',
                builder: (context) {
                  return Center(
                    child: Container(
                      height: 300,
                      width: 300,
                      color: Colors.red,
                    ),
                  );
                },
                animationType: SmartAnimationType.centerFade_otherSlide,
                backDismiss: true,
                keepSingle: true,
                debounce: true,
              );
            },
            tooltip: 'Increment',
            child: const Icon(Icons.add),
          ),
        ),
      ),
    );
  }
  void _incrementCounter() {
    SmartDialog.show(
      tag: '11',
      builder: (context) {
        return Center(
          child: Container(
            height: 300,
            width: 300,
            color: Colors.red,
          ),
        );
      },
      animationType: SmartAnimationType.centerFade_otherSlide,
      backDismiss: true,
      keepSingle: true,
      debounce: true,
    );
    return;
  }
}

**Comment by git-maven** [comment]
https://github.com/fluttercandies/flutter_smart_dialog/assets/45022397/e233f198-37fe-4b58-b723-ba7281889373

问题视频

**Comment by xdd666t** [comment]
- 试试新版本

```
dependencies:
  flutter_smart_dialog: ^4.9.7+5
```

**Comment by git-maven** [comment]
> * 试试新版本
> 
> ```dart
> dependencies:
>   flutter_smart_dialog: ^4.9.7+5
> ```

dialog正常，我今天看看能不能复现toast那个bug

**Comment by xdd666t** [comment]
- 后续需使用最新版本, 这个先关了, 后续再有问题, 描述清楚, 可重开一个issue

```dart
dependencies:
  flutter_smart_dialog: ^4.9.7+7
```
