### ISSUE TITLE
Dialog doesn't show up

### ISSUE THREAD

**Issue by shatanikmahanty** [fluttercandies/flutter_smart_dialog#194]
### Version Information
- Flutter version:  3.22.1 (Stable channel)
- flutter_smart_dialog version: 4.9.7+7

### Describe the bug/requirement

On calling showAttach sometiimes dialog doesn't show up and I get this error.

Attached below is the error trace

I/flutter (25984): Error caught by PlatformDispatcher.instance.onError:Looking up a deactivated widget's ancestor is unsafe.
I/flutter (25984): At this point the state of the widget's element tree is no longer stable.
I/flutter (25984): To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method. #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4743:9)
I/flutter (25984): #1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4757:6)
I/flutter (25984): #2      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:4869:12)
I/flutter (25984): #3      LookupBoundary.findAncestorStateOfType (package:flutter/src/widgets/lookup_boundary.dart:166:13)
I/flutter (25984): #4      Overlay.maybeOf (package:flutter/src/widgets/overlay.dart:580:26)
I/flutter (25984): #5      Overlay.of (package:flutter/src/widgets/overlay.dart:530:34)
I/flutter (25984): #6      overlay (package:flutter_smart_dialog/src/kit/view_utils.dart:19:55)
I/flutter (25984): #7      CustomDialog._pushDialog.<anonymous closure> (package:flutter_smart_dialog/src/custom/custom_dialog.dart:271:9)
I/flutter (25984): #8      ViewUtils.addSafeUse (package:flutter_smart_dialog/src/kit/view_utils.dart:10:15)
I/flutter (25984): #9      CustomDialog._pushDialog (package:flutter_smart_dialog/src/custom/custom_dialog.dart:264:15)
I/flutter (25984): #10     CustomDialog._handleMustOperate (package:flutter_smart_dialog/src/custom/custom_dialog.dart:246:7)
I/flutter (25984): #11     CustomDialog.showAttach (package:flutter_smart_dialog/src/custom/custom_dialog.dart:129:24)
I/flutter (25984): #12     DialogProxy.showAttach (package:flutter_smart_dialog/src/helper/dialog_proxy.dart:250:19)
I/flutter (25984): <asynchronous suspension>

**Comment by xdd666t** [comment]
- please give a simplified demo that can reproduce the problem and can be run directly

**Comment by shatanikmahanty** [comment]
> * please give a simplified demo that can reproduce the problem and can be run directly

Will create one during the weekend and get back to you. Thanks!

**Comment by leavky** [comment]
也有遇到这个，但是升级到最新版本问题貌似没了

**Comment by xdd666t** [comment]
If you still find this problem during the use of the latest version, you can provide a reproducible demo and open another issue, and this issue is closed first.
