### ISSUE TITLE
和getx配合使用，最新flutter sdk有问题。

### ISSUE THREAD

**Issue by winter-tech** [fluttercandies/flutter_smart_dialog#195]
### Version Information
- Flutter version: [3.22.2]
- flutter_smart_dialog version: [4.9.1]

### Describe the bug/requirement
`class ServiceDetailDialogPage extends StatelessWidget {
  ServiceDetailDialogPage({super.key, required this.model});

  final logic = Get.put(ServiceDetailDialogLogic());
  final ListList model;

  @override
  Widget build(BuildContext context) {
    logic.model = model;
    return Container();
  }
}`
这个是使用getx，然后弹出底部的弹框，widget就是上面代码的页面。之前flutter sdk在3.19.0的时候，生命周期是正常的，onInit-->Widget build-->onReady
升级后，生命周期变成了Widget build-->onInit-->onReady

请问是什么原因呢？

**Comment by xdd666t** [comment]
升级下SmartDialog版本

**Comment by winter-tech** [comment]
> 你用的SmartDialog是最新版本?

flutter_smart_dialog: ^4.9.1

**Comment by winter-tech** [comment]
> 你用的SmartDialog是最新版本?

我用  flutter_smart_dialog: ^4.9.7+7 这个，也是一样的问题。

**Comment by xdd666t** [comment]
。。。。。。那我也不清楚呀，可能是flutter最新sdk什么内部机制变了

**Comment by winter-tech** [comment]
> 。。。。。。那我也不清楚呀，可能是flutter最新sdk什么内部机制变了

但是，如果是getx跳转页面，就是Get.to()那种，生命周期也是正常的，用 Get.bottomSheet(ServiceDetailDialogPage(model: model));getx的底部弹框，也是正常的。

**Comment by xdd666t** [comment]
目前没有精力去适配其它三方库的逻辑，只会去兼容flutter sdk的逻辑

例如flutter的StatefulWidget的生命周期回调，如果在SmartDialog上出了问题，我会去解决
