### ISSUE TITLE
showLoading()需求

### ISSUE THREAD

**Issue by felix0324324** [fluttercandies/flutter_smart_dialog#196]
### 版本信息
- Flutter版本： -
- flutter_smart_dialog版本：^4.9.7+7

### 描述需求
請問這兩個能如何加在 showLoading()沒有下面那兩個參數, 要如何加上去?
BuildContext? bindWidget,
bool? bindPage,

**Comment by xdd666t** [comment]
这些参数不适合加在loading上，由于loading的特殊性（单OverlayEntry），如果加了这些参数，会出现在其他页面会打不开loading的情况
