### ISSUE TITLE
E/flutter ( 6354): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field 'contextCustom' has not been initialized.

### ISSUE THREAD

**Issue by q920447939** [fluttercandies/flutter_smart_dialog#198]
### 版本信息
```
- Flutter版本：
    Flutter 3.19.3 • channel stable • https://github.com/flutter/flutter.git
    Framework • revision ba39319843 (4 months ago) • 2024-03-07 15:22:21 -0600
    Engine • revision 2e4ba9c6fb
    Tools • Dart 3.3.1 • DevTools 2.31.1

- flutter_smart_dialog版本：^4.9.6
  
```

### 描述bug/需求
```
Restarted application in 1,685ms.
E/flutter ( 6354): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field 'contextCustom' has not been initialized.
E/flutter ( 6354): #0      DialogProxy.contextCustom (package:flutter_smart_dialog/src/helper/dialog_proxy.dart)
E/flutter ( 6354): #1      DialogProxy.timelyContextCustom (package:flutter_smart_dialog/src/helper/dialog_proxy.dart:66:50)
E/flutter ( 6354): #2      CustomDialog._pushDialog.<anonymous closure> (package:flutter_smart_dialog/src/custom/custom_dialog.dart:266:25)
E/flutter ( 6354): #3      ViewUtils.addSafeUse (package:flutter_smart_dialog/src/kit/view_utils.dart:10:15)
E/flutter ( 6354): #4      CustomDialog._pushDialog (package:flutter_smart_dialog/src/custom/custom_dialog.dart:264:15)
E/flutter ( 6354): #5      CustomDialog._handleMustOperate (package:flutter_smart_dialog/src/custom/custom_dialog.dart:246:7)
E/flutter ( 6354): #6      CustomDialog.show (package:flutter_smart_dialog/src/custom/custom_dialog.dart:53:24)
E/flutter ( 6354): #7      DialogProxy.show (package:flutter_smart_dialog/src/helper/dialog_proxy.dart:139:19)
E/flutter ( 6354): <asynchronous suspension>
E/flutter ( 6354): 

```
### 问题demo

```
Widget buildMaterialApp() {
  // here
  final initSmartDialog = FlutterSmartDialog.init();
  //填入设计稿中设备的屏幕尺寸,单位dp
  return ScreenUtilInit(
    designSize: const Size(430, 932),
    splitScreenMode: false,
    builder: (context, child) {
      return MediaQuery(
        data:
            MediaQuery.of(context).copyWith(textScaler: TextScaler.linear(1.0)),
        child: MaterialApp(
          home: RouterPage(),
          navigatorObservers: [FlutterSmartDialog.observer],
          builder: EasyLoading.init(builder: initSmartDialog),
        ),
      );
    },
  );
}
```

正常使用没有问题，但是我希望在页面一打开就可以渲染出对话框，

这是我的demo代码

```
class _LoginPageState extends State<LoginPage> {
  String? username;
  String? password;
  bool isEnabled = false;

  @override
  void initState() {
    super.initState();
    _show();
  }
   void _show() {
    SmartDialog.show(builder: (_) {
      return Container(
        width: 300,
        height: 170,
        alignment: Alignment.center,
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(20),
        ),
        child: Wrap(spacing: 20, children: [
          ElevatedButton(
            onPressed: () => _openPermanentDialog(),
            child: const Text('open'),
          ),
          ElevatedButton(
            onPressed: () => SmartDialog.dismiss(force: true),
            child: const Text('close'),
          )
        ]),
      );
    });
  }

}
```

辛苦看下，祝大佬生八个儿子

**Comment by q920447939** [comment]
> ### 版本信息
> ```
> - Flutter版本：
>     Flutter 3.19.3 • channel stable • https://github.com/flutter/flutter.git
>     Framework • revision ba39319843 (4 months ago) • 2024-03-07 15:22:21 -0600
>     Engine • revision 2e4ba9c6fb
>     Tools • Dart 3.3.1 • DevTools 2.31.1
> 
> - flutter_smart_dialog版本：^4.9.6
>   
> ```
> 
> ### 描述bug/需求
> ```
> Restarted application in 1,685ms.
> E/flutter ( 6354): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field 'contextCustom' has not been initialized.
> E/flutter ( 6354): #0      DialogProxy.contextCustom (package:flutter_smart_dialog/src/helper/dialog_proxy.dart)
> E/flutter ( 6354): #1      DialogProxy.timelyContextCustom (package:flutter_smart_dialog/src/helper/dialog_proxy.dart:66:50)
> E/flutter ( 6354): #2      CustomDialog._pushDialog.<anonymous closure> (package:flutter_smart_dialog/src/custom/custom_dialog.dart:266:25)
> E/flutter ( 6354): #3      ViewUtils.addSafeUse (package:flutter_smart_dialog/src/kit/view_utils.dart:10:15)
> E/flutter ( 6354): #4      CustomDialog._pushDialog (package:flutter_smart_dialog/src/custom/custom_dialog.dart:264:15)
> E/flutter ( 6354): #5      CustomDialog._handleMustOperate (package:flutter_smart_dialog/src/custom/custom_dialog.dart:246:7)
> E/flutter ( 6354): #6      CustomDialog.show (package:flutter_smart_dialog/src/custom/custom_dialog.dart:53:24)
> E/flutter ( 6354): #7      DialogProxy.show (package:flutter_smart_dialog/src/helper/dialog_proxy.dart:139:19)
> E/flutter ( 6354): <asynchronous suspension>
> E/flutter ( 6354): 
> ```
> 
> ### 问题demo
> ```
> Widget buildMaterialApp() {
>   // here
>   final initSmartDialog = FlutterSmartDialog.init();
>   //填入设计稿中设备的屏幕尺寸,单位dp
>   return ScreenUtilInit(
>     designSize: const Size(430, 932),
>     splitScreenMode: false,
>     builder: (context, child) {
>       return MediaQuery(
>         data:
>             MediaQuery.of(context).copyWith(textScaler: TextScaler.linear(1.0)),
>         child: MaterialApp(
>           home: RouterPage(),
>           navigatorObservers: [FlutterSmartDialog.observer],
>           builder: EasyLoading.init(builder: initSmartDialog),
>         ),
>       );
>     },
>   );
> }
> ```
> 
> 正常使用没有问题，但是我希望在页面一打开就可以渲染出对话框，
> 
> 这是我的demo代码
> 
> ```
> class _LoginPageState extends State<LoginPage> {
>   String? username;
>   String? password;
>   bool isEnabled = false;
> 
>   @override
>   void initState() {
>     super.initState();
>     _show();
>   }
>    void _show() {
>     SmartDialog.show(builder: (_) {
>       return Container(
>         width: 300,
>         height: 170,
>         alignment: Alignment.center,
>         decoration: BoxDecoration(
>           color: Colors.white,
>           borderRadius: BorderRadius.circular(20),
>         ),
>         child: Wrap(spacing: 20, children: [
>           ElevatedButton(
>             onPressed: () => _openPermanentDialog(),
>             child: const Text('open'),
>           ),
>           ElevatedButton(
>             onPressed: () => SmartDialog.dismiss(force: true),
>             child: const Text('close'),
>           )
>         ]),
>       );
>     });
>   }
> 
> }
> ```
> 
> 辛苦看下，祝大佬生八个儿子



自己修复了。处理方案如下：
```
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _show();
    });
  }

```

**Comment by xdd666t** [comment]
一般来说SmartDialog支持在initState回调里面使用

除非你是在打开app的第一个页面, 这个时候, 整个框架还没初始完毕, 可能会导致报错

**Comment by yjt1216** [comment]
我这没有初始化，项目嵌套的太多了
