### ISSUE TITLE
调用show传入ListView后，顶部会多出一截白色空白

### ISSUE THREAD

**Issue by xiaomiaos** [fluttercandies/flutter_smart_dialog#199]
### 版本信息
- Flutter版本：[举例：3.4.0]
- flutter_smart_dialog版本：[举例：^4.9.7+7]

### 描述bug/需求
调用show传入ListView后，顶部会多出一截白色空白

### 问题demo
static showSelectDialog(List<String> list,Function(int) onTap){
    SmartDialog.show(builder: (context) {
      return Container(
        color: Colors.white,
        //child: CommonSelectDialog(data: list, onPressed: onTap),
        child: ListView.builder(
          itemBuilder: (context, index) {
            return Text(
              list[index],style: TextStyle(color: Colors.black),);
          },
          itemCount: list.length,
          shrinkWrap: true,
        ),
      );
    },alignment: Alignment.bottomCenter);
  }
![image](https://github.com/fluttercandies/flutter_smart_dialog/assets/34334414/5e7f72a0-85fe-4f84-a923-f3a947f28e28)

**Comment by xdd666t** [comment]
https://github.com/fluttercandies/flutter_smart_dialog/issues/146
