### ISSUE TITLE
使用组件后，app外圈有绿色的border

### ISSUE THREAD

**Issue by dirkhe1051931999** [fluttercandies/flutter_smart_dialog#2]
如下
![image](https://user-images.githubusercontent.com/22389976/112783992-1ad1ba80-9083-11eb-96f2-4eb5ae12f3d1.png)

**Comment by CNAD666** [comment]
确定是使用SmartDialog造成的吗？从原理上来说，关掉SmartDialog，基本上就就让一个浮在整个app上的布局消失了，出现绿色让人很疑惑。
我这边多个app使用该框架，未出现该情况；方便的话，可以给一个颗粒度最小的脱敏demo吗？

**Comment by CNAD666** [comment]
老兄，长时间没回复，先关了，有问题再反馈

**Comment by bggRGjQaUbCoE** [comment]
跟组件库无关，使用物理键盘会出现绿色焦点边框，可以关闭
`<item name="android:defaultFocusHighlightEnabled">false</item>`
