### ISSUE TITLE
空安全

### ISSUE THREAD

**Issue by 13232989155** [fluttercandies/flutter_smart_dialog#20]
Restarted application in 1,318ms.
E/flutter ( 3366): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 3366): #0      new MonitorPopRoute._
package:flutter_smart_dialog/…/helper/monitor_pop_route.dart:15
E/flutter ( 3366): #1      MonitorPopRoute.instance
package:flutter_smart_dialog/…/helper/monitor_pop_route.dart:12
E/flutter ( 3366): #2      FlutterSmartDialog.monitor
package:flutter_smart_dialog/src/dialog.dart:17
E/flutter ( 3366): #3      FlutterSmartDialog.init
package:flutter_smart_dialog/src/dialog.dart:21

**Comment by xdd666t** [comment]
啥玩意，也不贴代码，也不描述产生报错的具体步骤；运行环境，pub包版本号啥都没，就贴一堆报错？？？犹抱琵琶半遮面让人猜？？？
