### ISSUE TITLE
smartdialog能够在dialog里面展开键盘，而不影响外部的page吗？

### ISSUE THREAD

**Issue by xiaomiaos** [fluttercandies/flutter_smart_dialog#201]
### 版本信息
- Flutter版本：[举例：v2.10.4]
- flutter_smart_dialog版本：[举例：v3.4.1]

### 描述bug/需求
请准确描述bug或需求

**Comment by xdd666t** [comment]
这玩意和焦点有关吧, 和弹窗有啥关系
