### ISSUE TITLE
升级flutter版本导致弹框在跳转页面前无法关闭

### ISSUE THREAD

**Issue by LvJson** [fluttercandies/flutter_smart_dialog#204]
### 版本信息
- Flutter 3.22.3
- flutter_smart_dialog: ^4.9.7+8

### 描述bug/需求
跳转页面前无法关闭弹框，除非使用async/await，但是这样会有明显延迟。

**这个问题是在升级flutter版本之后才出现的。**

### 问题demo
`InkWell(
                          onTap: () {
                            SmartDialog.dismiss();
                            Navigator.push(
                                context,
                                MaterialPageRoute(
                                    builder: (context) => TestPage()));
                          })`

**Comment by xdd666t** [comment]
dismiss本身就是个异步方法, 内部的逻辑根本不能保证同步关闭弹窗, 不加await按照同步思想去使用肯定是不合理的

- 跳转页面后弹窗就隐藏了, 使用dismiss就关不掉了, 你可以把bindPage设置为false, 在尝试关闭

- 另一种解决办法: await之后有延迟因为动画时间问题, 你可以把这个动画弹窗设置短一些, 或者把关闭弹窗的动画直接关闭 nonAnimationTypes: [SmartNonAnimationType.closeDialog_nonAnimation],

**Comment by LvJson** [comment]
将bindPage设置为false更符合我的需求，谢谢！
