### ISSUE TITLE
如何调整MSG大小

### ISSUE THREAD

**Issue by yx-design** [fluttercandies/flutter_smart_dialog#207]
### 版本信息
- Flutter版本：
- 3.19.6
- flutter_smart_dialog版本：
- 4.9.7+9

### 描述bug/需求
  // 加载动画
 高分辨率机器，动画区域太小，如何调整？

### 问题demo
  // 加载动画
  void showLoading({String? msg}) {
    SmartDialog.showLoading(
      msg: msg ?? "加载中...",  // 调整文字大小
      clickMaskDismiss: false,
      animationType: SmartAnimationType.fade,
      backDismiss: true,
    );
  }

**Comment by xdd666t** [comment]
- 请使用自定义的loading样式, 默认样式仅做占位展示: https://github.com/fluttercandies/flutter_smart_dialog/issues/131

![QQ_1722851150693](https://github.com/user-attachments/assets/7f9b0456-d140-4176-9e43-6234fbdd157e)

**Comment by yx-design** [comment]
谢谢！

> * 请使用自定义的loading样式, 默认样式仅做占位展示: [SmartDialog在各类路由框架中如何初始化 #131](https://github.com/fluttercandies/flutter_smart_dialog/issues/131)
> 
> ![QQ_1722851150693](https://private-user-images.githubusercontent.com/35656085/355056701-7f9b0456-d140-4176-9e43-6234fbdd157e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MTA1ODksIm5iZiI6MTcyMjkxMDI4OSwicGF0aCI6Ii8zNTY1NjA4NS8zNTUwNTY3MDEtN2Y5YjA0NTYtZDE0MC00MTc2LTllNDMtNjIzNGZiZGQxNTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAyMTEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NjJiYzVjNWY3NWVmMWMwMDBiZDk0ZDkxZmQ1NjJhMzQzOTVjM2FiNTQ2YzQ3NDNhZGYzOTA4MjIzMDU3ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zwZujqMpztLGkwruQMv3q9sS0bo_TTAcCwMf54Y9VSY)

谢谢！
