### ISSUE TITLE
怎么判断是否初始化

### ISSUE THREAD

**Issue by mdddj** [fluttercandies/flutter_smart_dialog#208]
有时候调用会报错
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field 'contextNotify' has not been initialized.
#0      DialogProxy.contextNotify (package:flutter_smart_dialog/src/helper/dialog_proxy.dart)
#1      DialogProxy.timelyContextNotify (package:flutter_smart_dialog/src/helper/dialog_proxy.dart:69:50)
#2      CustomNotify._pushDialog.<anonymous closure> (package:flutter_smart_dialog/src/custom/custom_notify.dart:148:29)
#3      ViewUtils.addSafeUse (package:flutter_smart_dialog/src/kit/view_utils.dart:13:15)
#4      CustomNotify._pushDialog (package:flutter_smart_dialog/src/custom/custom_notify.dart:141:15)
#5      CustomNotify._handleMustOperate (package:flutter_smart_dialog/src/custom/custom_notify.dart:130:7)
#6      CustomNotify.showNotify (package:flutter_smart_dialog/src/custom/custom_notify.dart:45:24)
#7      DialogProxy.showNotify (package:flutter_smart_dialog/src/helper/dialog_proxy.dart:191:19)

**Comment by xdd666t** [comment]
给下能复现该问题的最简demo
