### ISSUE TITLE
`SmartDialog.showAttach()` fails within Silverlist

### ISSUE THREAD

**Issue by Princewil** [fluttercandies/flutter_smart_dialog#212]
### Version Information
-  Flutter (Channel stable, 3.24.0)
- flutter_smart_dialog: ^4.9.7+9

### Describe the bug/requirement
Calling the `SmartDialog.showAttach()` on a Widget within `SliverList` fails.
Gives the error `type 'RenderSliverList' is not a subtype of type 'RenderBox' in type cast`

### Problem demo
Use a `ListTile` widget as an item within a `SliverList` then on the `ontap` callback of the `ListTile` call the function `SmartDialog.showAttach()` and you see the error.

**Comment by xdd666t** [comment]
Please provide a runnable main file demo.
