### ISSUE TITLE
希望能够增加内置的返回事件回调

### ISSUE THREAD

**Issue by ddxl123** [fluttercandies/flutter_smart_dialog#213]
dialog
在点击`mask`时，可以使用`onMask`来监听是否点击了`Mask`。但是在触发返回事件时，例如`BackButton`或`物理键返回`。
其中`物理键返回`只能使用`backDismiss`来配置是否可以返回，
而`BackButton`可以手动进行是否返回的逻辑处理，例如在返回时需要检测表单是否正确，如果正确可以返回如果错误则无法返回。但是如果想要`BackButton`和`物理键返回`使用相同的业务逻辑，就必须手动封装一层`PopScope`了。
当然还有一种情况是，`点击mask`、`BackButton`、`物理键返回`都需要进行相同的返回检验，这样的话，`onMask`和`BackButton`是可以进行检验业务的，但是`物理键返回`却要手动再封装一个`PopScope`才能进行校验业务。

希望能够内置`PopScope`，这样的话在处理类似的返回校验业务时，就能够更加便捷的调用相同逻辑了。

**Comment by xdd666t** [comment]
- 试下新版本, 返回回调监听: onBack，有问题及时和我说下，这个版本改动量较大

```
dependencies:
  flutter_smart_dialog: ^4.9.8+2
```
