### ISSUE TITLE
能否提供一个类似showModalBottomSheet，可滑动关闭的弹框。

### ISSUE THREAD

**Issue by LvJson** [fluttercandies/flutter_smart_dialog#214]
由于系统提供的BottomSheet弹框局限性太大了，连基本的想关闭指定的弹框都不行；希望提供一个类似showModalBottomSheet，可滑动关闭的弹框，多谢！！！

**Comment by xdd666t** [comment]
SmartDialog.show，alignment设置为Alignment.bottomCenter，自行使用Dismissible做滑动关闭功能，SmartDialog内部没有必要封装Dismissible这个组件
