### ISSUE TITLE
Bad state error  when show toast

### ISSUE THREAD

**Issue by gaochang1993** [fluttercandies/flutter_smart_dialog#219]
### Version Information
- Flutter version: 3.24.2
- flutter_smart_dialog version: 4.9.8

### Describe the bug/requirement
Bad state: RenderBox was not laid out: RenderPadding

<img width="1110" alt="image" src="https://github.com/user-attachments/assets/d59459a6-06cc-4480-b63f-5f7edebe85f1">

**Comment by gaochang1993** [comment]
> * 试下新版本, 有问题及时和我说下，这个版本改动量较大
> 
> ```dart
> dependencies:
>   flutter_smart_dialog: ^4.9.8+2
> ```

我更新下看看

**Comment by iCytus** [comment]
hello， 请问你这边现在还有出现这个问题么？我们用的是 4.9.8+5的版本还是有出现这个问题， @gaochang1993 
<img width="534" alt="image" src="https://github.com/user-attachments/assets/adbf3e7e-a715-4585-8b86-36937731c4ab">

**Comment by gaochang1993** [comment]
> > * 试下新版本, 有问题及时和我说下，这个版本改动量较大
> > 
> > ```dart
> > dependencies:
> >   flutter_smart_dialog: ^4.9.8+2
> > ```
> 
> 我更新下看看


> * 试下新版本, 有问题及时和我说下，这个版本改动量较大
> 
> ```dart
> dependencies:
>   flutter_smart_dialog: ^4.9.8+2
> ```

这个版本还是会有这个问题，最近在大改版，所以没关注到。

**Comment by gaochang1993** [comment]
> hello， 请问你这边现在还有出现这个问题么？我们用的是 4.9.8+5的版本还是有出现这个问题， @gaochang1993 <img alt="image" width="534" src="https://private-user-images.githubusercontent.com/46601004/387918406-adbf3e7e-a715-4585-8b86-36937731c4ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1ODg2OTksIm5iZiI6MTczMjU4ODM5OSwicGF0aCI6Ii80NjYwMTAwNC8zODc5MTg0MDYtYWRiZjNlN2UtYTcxNS00NTg1LThiODYtMzY5Mzc3MzFjNGFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDAyMzMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlODg0YjE1Njk2YmViODYxYWMyY2NlOGJlZGY4YmVlYzMyYTE2NjA5ZmFiNDcxNTg1OTkxZWRmYjFhZjJjNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iHf131zUgcPJFF9D-CLyaFokAmO8IzizCpkii7qMkO8">

还是会有这个问题，如果App启动之后立即出弹窗的话，就可能会出现这个问题。由于最近事情有点多，没有关注这个了。

**Comment by xdd666t** [comment]
@gaochang1993 @iCytus 试试看能不能给出个复现的最简demo

**Comment by iCytus** [comment]
> @gaochang1993 @iCytus 试试看能不能给出个能复现问题的最简demo

主要是本地运行测试没有报出该问题，但是线上发布的版本，一直出现这个问题，所以目前暂时没法整理出可以稳定复现问题的demo。

**Comment by gaochang1993** [comment]
> > @gaochang1993 @iCytus 试试看能不能给出个能复现问题的最简demo
> 
> 主要是本地运行测试没有报出该问题，但是线上发布的版本，一直出现这个问题，所以目前暂时没法整理出可以稳定复现问题的demo。

本地debug 和profile都没有复现，但是就是线上release 会出现在这个问题。最初怀疑的冷启动的时候，帧率比较低，然后由于网络请求失败的toast导致的，但是本地一直没有复现出来

**Comment by Liloupar** [comment]
我也一直遇到这个错误, 有什么办法来临时解决下吗?
```
          Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Bad state: RenderBox was not laid out: RenderPadding#31951. Error thrown .
       at RenderBox.size(box.dart:2212)
       at _ToastHelperState.initState.<fn>(toast_helper.dart:37)
       at ViewUtils.addSafeUse.<fn>(view_utils.dart:12)
       at SchedulerBinding._invokeFrameCallback(binding.dart:1397)
       at SchedulerBinding.handleDrawFrame(binding.dart:1331)
       at SchedulerBinding._handleDrawFrame(binding.dart:1176)
        
```
求问大佬

**Comment by gaochang1993** [comment]
> 我也一直遇到这个错误, 有什么办法来临时解决下吗?
> 
> ```
>           Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Bad state: RenderBox was not laid out: RenderPadding#31951. Error thrown .
>        at RenderBox.size(box.dart:2212)
>        at _ToastHelperState.initState.<fn>(toast_helper.dart:37)
>        at ViewUtils.addSafeUse.<fn>(view_utils.dart:12)
>        at SchedulerBinding._invokeFrameCallback(binding.dart:1397)
>        at SchedulerBinding.handleDrawFrame(binding.dart:1331)
>        at SchedulerBinding._handleDrawFrame(binding.dart:1176)
>         
> ```
> 
> 求问大佬



> 我也一直遇到这个错误, 有什么办法来临时解决下吗?
> 
> ```
>           Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Bad state: RenderBox was not laid out: RenderPadding#31951. Error thrown .
>        at RenderBox.size(box.dart:2212)
>        at _ToastHelperState.initState.<fn>(toast_helper.dart:37)
>        at ViewUtils.addSafeUse.<fn>(view_utils.dart:12)
>        at SchedulerBinding._invokeFrameCallback(binding.dart:1397)
>        at SchedulerBinding.handleDrawFrame(binding.dart:1331)
>        at SchedulerBinding._handleDrawFrame(binding.dart:1176)
>         
> ```
> 
> 求问大佬

暂时没有什么好的解决办法。
一个就是检查一下代码，看有没有什么地方使你的Widget重建导致context改变了。另一个就是如果是启动的时候toast 延迟一定的时间。或者就是直接改源代码，在这里再做一次判断，如果context.mounted = false就取消toast。
