### ISSUE TITLE
弹出框关回调.

### ISSUE THREAD

**Issue by zhanghuan88** [fluttercandies/flutter_smart_dialog#22]
弹出框是关闭完成后,调用回调,可以开始关闭之前调用回调吗

**Comment by xdd666t** [comment]
你可以描述下，在关闭动画之前调用关闭回调，这是基于什么业务场景下的考量？

**Comment by zhanghuan88** [comment]
使用showAttach ,并且使用自带动画方法, 回调是动画结束后才回调. 我打开showAttach的时候,加了个动画,关闭后动画反转. 有点延迟.不使用自带的动画就没这个问题

**Comment by xdd666t** [comment]
> 使用showAttach ,并且使用自带动画方法, 回调是动画结束后才回调. 我打开showAttach的时候,加了个动画,关闭后动画反转. 有点延迟.不使用自带的动画就没这个问题

业务场景应该是，点击showAttach某个自定义按钮，请求接口的时候，有定延迟是吧

**Comment by xdd666t** [comment]
> 使用showAttach ,并且使用自带动画方法, 回调是动画结束后才回调. 我打开showAttach的时候,加了个动画,关闭后动画反转. 有点延迟.不使用自带的动画就没这个问题

你是在onDismiss里面做了自己的动画反转？

**Comment by zhanghuan88** [comment]
是的

**Comment by zhanghuan88** [comment]
得等到下拉框的动画执行,完毕 ,才会执行回调

**Comment by zhanghuan88** [comment]
这样就会有点延迟

**Comment by xdd666t** [comment]
- ok了，升下版本吧
```dart
flutter_smart_dialog: 3.2.3
```

**Comment by zhanghuan88** [comment]
好的

**Comment by zhanghuan88** [comment]
OK了
