### ISSUE TITLE
Can+t pop route using v4.9.8+2 version

### ISSUE THREAD

**Issue by zigapovhe** [fluttercandies/flutter_smart_dialog#222]
### Version Information
- Flutter version: v3.24.3
- flutter_smart_dialog version: v4.9.8+2 

### Describe the bug/requirement
After upgrading your package from v4.9.8+1 to v4.9.8+2 we can't pop the screen after displaying dialog. If I revert back to v4.9.8+1, everything works as expected.

### Problem demo
I'm still working on minimal reproducible example similar to my app, as our app is pretty complex. Do you have any idea, what change from +1 to +2 could contribute to that? Will give you an minimal example in max 2 days, but i'm always using those parameters when displaying an dialog.

  SmartDialog.show(
      alignment: Alignment.center,
      maskColor: Colors.black26,
      clickMaskDismiss: false,
      usePenetrate: false,
      useSystem: true,
      animationType: SmartAnimationType.scale,
      useAnimation: true,
);

**Comment by xdd666t** [comment]
The main change in the +2 version is to roll back the initialization reconstruction. The previous dynamic initialization reconstruction would cause many strange problems.

I need you to provide a demo of the smallest unit that can reproduce the problem so that I can locate the specific cause.
