### ISSUE TITLE
在电视上的应用弹窗中的按钮无法使用遥控获得焦点

### ISSUE THREAD

**Issue by JohnGuSir** [fluttercandies/flutter_smart_dialog#223]
SmartDialog.show(builder: (_){
     return Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          ElevatedButton(
            child: Text("DISMISS"),
            onPressed: () {
              showToast("DISMISS");
            },
          ),
          ElevatedButton(
            child: Text("CONFIRM"),
            onPressed: () {
              showToast("CONFIRM");
            },
          ),
        ],
      );
    });

**Comment by JohnGuSir** [comment]
@xdd666t

**Comment by xdd666t** [comment]
- SmartDialog本质和Flutter页面没有区别, 只是在MaterialApp上面盖了Overlay
- 然后自己看看是不是控件没拿到焦点

**Comment by JohnGuSir** [comment]
@xdd666t 
换成  Get.dialog 是正常的，使用smartdialog 就无法拿到 了，给dialog requestFouce 也拿不到。

**Comment by xdd666t** [comment]
你就使用原生Dialog吧，我这边没电视设备，无法去看具体原因
