### ISSUE TITLE
Go router and Smart dialog issue

### ISSUE THREAD

**Issue by thaarrtt** [fluttercandies/flutter_smart_dialog#228]
### Version Information
- Flutter version , 3.24.1
- flutter_smart_dialog: ^4.9.8

### Describe the bug/requirement
when using go router and smart dialog, when user navigate to a new page then open a 1 smart dialog, current page stack got removed and when the back button is pressed got thrown out of application 

this is not happen when user is not shown any dialog

### Problem demo

repo link soon

**Comment by xdd666t** [comment]
When you can provide the simplest reproducible demo, open an issue
