### ISSUE TITLE
window和web平台问题

### ISSUE THREAD

**Issue by xietian0908** [fluttercandies/flutter_smart_dialog#229]
### Version Information
flutter: 3.24.3
flutter_smart_dialog: ^4.9.8+3

### Describe the bug/requirement
如何能够让attach dialog 随着窗口尺寸变化 而变化，也就是保持与attach的目标位置始终一致

### Problem demo
在线演示demo
![image](https://github.com/user-attachments/assets/6bcd7058-cf69-4bbb-a0f6-5a5e96450f65)

**Comment by xietian0908** [comment]
DialogUtil.showAttach(
                  context,
                  adjustBuilder: (p0) {
                    return AttachAdjustParam(
                      builder: (context) {
                        return SettingAttachDialog();
                      },
                    );
                  },
                  builder: (context, targetWidget, targetHeight) {
                    return SettingAttachDialog();
                  },
                );

https://github.com/user-attachments/assets/6f2c0739-e847-4efe-a8a7-f07e4cdc5e5f


使用 adjustBuilder可以保持位置 但是会闪烁

**Comment by xdd666t** [comment]
尝试把动画关掉 useAnimation 设置为false， 或者animationTime设置为0

**Comment by xietian0908** [comment]
https://github.com/user-attachments/assets/23337952-47fb-454d-9fba-61e9f92039c8

试了下还是有些问题
![image](https://github.com/user-attachments/assets/805a24ee-b52c-47c8-be05-5195a5bce25a)

**Comment by xdd666t** [comment]
- 行了, 试下新版本, 不需要用adjustBuilder, 正常用builder就行了

```dart
dependencies:
  flutter_smart_dialog: ^4.9.8+4
```

**Comment by xietian0908** [comment]
没问题了👍
