### ISSUE TITLE
频繁多次调用，toast不消失

### ISSUE THREAD

**Issue by Gerry1218** [fluttercandies/flutter_smart_dialog#230]
### Version Information
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.5 23F79 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)

### Describe the bug/requirement
http请求的suc和err中显示toast，一部分走suc一部分走err大概率会有toast不消失

### Problem demo
我在请求的suc和err调用了如下方法，
SmartDialog.showToast("testing",
            alignment: Alignment.center, displayType: SmartToastType.onlyRefresh, displayTime: const Duration(seconds: 1));

如果接口频繁调用弹框，大概率出现toast不消失

**Comment by xdd666t** [comment]
复现demo

**Comment by sineom-1** [comment]
+1

**Comment by xdd666t** [comment]
没时间猜原因，没精力试偶发问题，能提供复现最简demo，再提issue
