### ISSUE TITLE
彈出dialog時，如何可以使用"無障礙semantics"的barrierlabel?

### ISSUE THREAD

**Issue by felix0324324** [fluttercandies/flutter_smart_dialog#232]
使用原生"showDialog()"時"無障礙semantics"是沒有問題的
但在flutter_smart_dialog沒有找到方法可以加barrierlabel的位置

**Comment by xdd666t** [comment]
你自己使用ModalBarrier 去处理下吧，可以自定maskBuilder上使用，或者dialog主体上使用stack使用ModalBarrier
