### ISSUE TITLE
使用了咸鱼的flutter_boost,再结合Getx，当设置咸鱼的 withContainer:false,侧滑返回不了(iOS，安卓没验证)

### ISSUE THREAD

**Issue by liamzhouacc** [fluttercandies/flutter_smart_dialog#236]
### 版本信息
- Flutter版本：3.24.4
  flutter_smart_dialog:
    dependency: transitive
    description:
      name: flutter_smart_dialog
      sha256: "7932ab58440379094c6a568efc329d322c6dd740e5a553080f2d56a71ed53752"
      url: "https://pub.dev"
    source: hosted
    version: "4.9.8+3"

使用了咸鱼的flutter_boost,再结合Getx，iOS侧滑返回不了，但去掉FlutterSmartDialog就OK了（如注释代码），代码如下：
    return FlutterSmartDialog.boostMonitor(GetPageRoute(
        settings: newSettings,
        transitionDuration: transitionDuration,
        transition: transition,
        page: page));
    // return GetPageRoute(
    //     settings: newSettings,
    //     transitionDuration: transitionDuration,
    //     transition: transition,
    //     page: page);

**Comment by liamzhouacc** [comment]
直接用咸鱼flutter_boost官方提供的example结合：[SmartDialog在各类路由框架中如何初始化] ，就侧滑返回不了。应该是被SmartDialog影响到了

**Comment by liamzhouacc** [comment]
如下代码的影响：if (route is ModalRoute) {
        willPopCallback() async {
          if (_handleSmartDialog()) {
            DialogProxy.instance.dismiss(
              status: SmartStatus.smart,
              closeType: CloseType.back,
            );
            return false;
          }
          return true;
        }

        // TODO: `addScopedWillPopCallback()` was deprecated after v3.12.0-1.0.pre.
        // ignore: deprecated_member_use
        route.addScopedWillPopCallback(willPopCallback);
        DialogProxy.contextNavigator = route.subtreeContext;
      }
      
      这些代码加了，对iOS有影响，不加貌似没什么问题

**Comment by xdd666t** [comment]
没看到我在issue模板里面的说明吗? 最简可复现问题的demo

如果, 我给你写一堆乱七八糟的代码, 你会帮我解决问题?

**Comment by liamzhouacc** [comment]
问题都帮你找到了，代码也提供很详细,你这心态。。。
都说是如下代码引起的，直接用咸鱼的demo
  Route<dynamic>? _routeFactory(RouteSettings settings, String? uniqueId) {
    var func = routerMap[settings.name!];
    // here
    return FlutterSmartDialog.boostMonitor(func?.call(settings, uniqueId));
  }
![img_v3_02gq_d1fd29ab-7c48-457d-8a82-d583d597bdeg](https://github.com/user-attachments/assets/98ce6e76-2563-40cb-a455-1048a4864cd6)

**Comment by xdd666t** [comment]
我解决问题的态度，取决于你提问题的态度

一个issue都不按照我提供的模板来，写的乱七八糟，还想我对你什么态度？
