### ISSUE TITLE
clickMaskDismiss怎么能动态修改

### ISSUE THREAD

**Issue by ilovexy2tom** [fluttercandies/flutter_smart_dialog#237]
### 版本信息
- Flutter版本：v3.22.2
- flutter_smart_dialog版本：4.9.7+8

### 描述bug/需求
clickMaskDismiss怎么能动态修改，比如我弹框倒计时5s后可以点击外部关闭，刚开始5s内不能点击外部关闭

**Comment by xdd666t** [comment]
clickMaskDismiss设置为false， onMask里面自己写关闭逻辑
