### ISSUE TITLE
attach  在页面返回后 不会自动关闭

### ISSUE THREAD

**Issue by 985211yyg** [fluttercandies/flutter_smart_dialog#243]
### 版本信息
- Flutter版本：[任何版本]
- flutter_smart_dialog版本：[任何版本]

### 描述bug/需求
attach  在页面返回后 不会自动关闭

### 问题demo
![image](https://github.com/user-attachments/assets/12266cf9-874c-4aa9-bb56-875c635538be)

**Comment by 985211yyg** [comment]
补充：实际场景需要事件能穿透，展示 attach 的同时能继续输入搜索

**Comment by xdd666t** [comment]
我的demo是弹窗演示，不是页面，你自己试过吗？？？

**Comment by 985211yyg** [comment]
大佬说的很对，手动处理就 ok
