### ISSUE TITLE
SmartDialog.config 定义的全局alignment属性不能正确传递到toastBuilder

### ISSUE THREAD

**Issue by ManInTheWind** [fluttercandies/flutter_smart_dialog#25]
如题,我初始化的samartDialog.config的alignment为center，但是在toastbuilder传入的还是默认的bottomcenter，
`SmartDialog.config
      ..alignment = Alignment.center
      ..isPenetrate = false
      ..clickBgDismiss = false
      ..maskWidget = maskWidget
      ..animationDuration = Duration(milliseconds: 260)
      ..isUseAnimation = true
      ..isLoading = true
      ..debounce = true
      ..debounceTime = Duration(milliseconds: 300);`
所以我不得不toastbuilder里重新定义一次alignment
` toastBuilder: (
                String msg,
                AlignmentGeometry alignment,
              ) {
                return CustomToastWidget(
                  text: msg,
                  alignment: const Alignment(0.0, 0.8),
                );
              },
              loadingBuilder: (
                String msg,
                Color background,
              ) {
                return CustomLoadingWidget();
              },`
建议 在 config 传入的alignment能够打通到toastbuilder，这样只需要定义一次alignment就可以了

**Comment by xdd666t** [comment]
toast里面的alignment和config里面的全局参数无关；注释里也写了：以 'temp' 后缀的参数，表示此类参数都可在[Config]中设置默认值

参数规范之前定了，现在也不能改了，影响太大。

如果觉得toastBuilder里面的alignment不是自己想要的效果，建议你不要用alignment，直接在自定义toast里面写死位置

**Comment by ManInTheWind** [comment]
> toast里面的alignment和config里面的全局参数无关；注释里也写了：以 'temp' 后缀的参数，表示此类参数都可在[Config]中设置默认值
> 
> 参数规范之前定了，现在也不能改了，影响太大。
> 
> 如果觉得toastBuilder里面的alignment不是自己想要的效果，建议你不要用alignment，直接在自定义toast里面写死位置

好的，我现在是这么写的
