### ISSUE TITLE
Unable to click the toast.

### ISSUE THREAD

**Issue by arnold-parge** [fluttercandies/flutter_smart_dialog#27]
I created a toast with a custom widget and added an `IconButton` in it which is not clickable.
Or is there a better way to dismiss the toast by user's interaction apart from `clickBgDismissTemp`?

Below is the code snippet.

```dart
SmartDialog.showToast(
  'The message',
  isUseAnimationTemp: true,
  widget: Row(
    children: [
      Icon(
        Icons.ac_unit_outlined,
        color: Colors.white,
      ),
      const C10(),
      Expanded(
        child: Text(
          'The message',
          style: TextStyles.errorStyle.copyWith(
            color: Colors.white,
          ),
        ),
      ),
      IconButton(
        onPressed: () {
          SmartDialog.dismiss(status: SmartStatus.toast); // <-- This is not clickable. The debugger breakpoint doesn't stop here. 
        },
        icon: const Icon(
          Icons.add_business_rounded,
          color: Colors.white,
        ),
      ),
    ],
  ),
  time: _getTime(msg),
);
```

**Comment by arnold-parge** [comment]
Okay, I see @xdd666t has added `IgnorePointer` in b795374804938356faed8cdee0d5596e23c30703.
The commit message doesn't explain much about the change.
Is it important to have `IgnorePointer` in the tree?

**Comment by xdd666t** [comment]
Why don't you consider using SmartDialog.show() instead? showToast() is generally only displayed as a message, not suitable for interacting with users

**Comment by arnold-parge** [comment]
`show()` doesn't have the `time` parameter which is useful for auto dismissing the message.

**Comment by arnold-parge** [comment]
What can go wrong if we remove the `IgnorePointer`?

**Comment by xdd666t** [comment]
IgnorePoint is added to prevent messages from consuming touch events, which imitates the behavior of Android toast; tomorrow I will add a param to enable toast to consuming touch events; if this function is completed, I will remind you in this issue

**Comment by arnold-parge** [comment]
Oh, got it. Thanks a ton! 👍 💟 
If you want I can do the change and create a PR.

**Comment by arnold-parge** [comment]
Cool. 👍

**Comment by xdd666t** [comment]
Hi, this issue has been resolved

- Please upgrade to the next version

```dart
dependencies:
  flutter_smart_dialog: ^3.4.0
```

- If you need showToast to consume touch events, you can write like this

```
SmartDialog.showToast('test toast', consumeEvent: true);
```
