### ISSUE TITLE
LateInitializationError: Field 'loadingBuilder' has not been initialized.

### ISSUE THREAD

**Issue by WangFour** [fluttercandies/flutter_smart_dialog#31]
======== Exception caught by gesture ===============================================================
The following LateError was thrown while handling a gesture:
LateInitializationError: Field 'loadingBuilder' has not been initialized.

When the exception was thrown, this was the stack: 
#0      DialogProxy.loadingBuilder (package:flutter_smart_dialog/src/helper/dialog_proxy.dart)
#1      SmartDialog.showLoading (package:flutter_smart_dialog/src/smart_dialog.dart:423:46)
#2      _PhoneLoginPageState.build.<anonymous closure>.<anonymous closure> (package:frogsell/login/ui/phone_login_page.dart:254:45)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#c9f9c
  state: ready
  won arena
  finalPosition: Offset(190.0, 575.0)
  finalLocalPosition: Offset(168.0, 4.0)
  button: 1
  sent tap down
====================================================================================================

**Comment by xdd666t** [comment]
- https://juejin.cn/post/7026150456673959943

![image](https://user-images.githubusercontent.com/35656085/157582446-fba4bc0e-9d60-407e-897a-a16a166fd4f5.png)
