### ISSUE TITLE
字体问题

### ISSUE THREAD

**Issue by FN8087** [fluttercandies/flutter_smart_dialog#33]
大神好：请问下字体怎么设置的，flutter项目默认字体，您的弹窗改变了字体
![image](https://user-images.githubusercontent.com/90084202/158092687-a725f61e-d574-48a5-be8b-55e08b647d85.png)

**Comment by xdd666t** [comment]
你这问题描述的真是模糊，我只能去猜测你的意思

你是不是在MaterialApp里面设置了默认字体，然后在SmartDialog里面里面没应用到你设置的默认字体，SmartDialog是盖在页面上，他们是独立的关系，有俩个方法可能可以解决你的问题
- 你可以将Text控件封装下，在style里面设置下字体就行，然后在SmartDialog里面都使用这个封装的Text控件
- 你可以试试将useSystem设置为true，这个方式不太建议，因为你将useSystem设置为true，SmartDialog一些功能，你将无法使用，注释里面写了，你可以看看

**Comment by xdd666t** [comment]
这个issue先关，如果还有问题，提issue的时候，记得把细节描述清楚哈
