### ISSUE TITLE
当显示的dialog未关闭的时候,关闭页面,再次进入这个页面的时候会出现错误

### ISSUE THREAD

**Issue by sbiweeq** [fluttercandies/flutter_smart_dialog#34]
当显示的dialog未关闭的时候,关闭页面,再次进入这个页面的时候会出现错误,有时候关闭后也会偶尔出现
出现异常。
版本:3.4.0+1
_AssertionError ('package:flutter/src/animation/animation_controller.dart': Failed assertion: line 487 pos 7: '_ticker != null': AnimationController.reverse() called after AnimationController.dispose()
AnimationController methods should not be used after calling dispose.)
![image](https://user-images.githubusercontent.com/10651998/158292396-b64fbf6c-7576-47a4-826a-364ee65ae14f.png)

当已经存在一个SmartDialog.show()的情况下,如果处于关闭中,第二个SmartDialog.show无法打开,程序异常

**Comment by xdd666t** [comment]
老哥，你说的几种场景，我都没法复现啊

能提供一个可以复现这个问题的demo吗？

**Comment by sbiweeq** [comment]
> 老哥，你说的几种场景，我都没法复现啊
> 
> 能提供一个可以复现这个问题的demo吗？

`

SmartDialog.show(
          //只允许一个
          // keepSingle: false,
          //返回键是否可关闭
          backDismiss: backDismiss,
          //是否可点击背景关闭
          clickBgDismissTemp: clickBgDismissTemp,
          alignmentTemp: alignmentTemp,
          isLoadingTemp: false,
          useSystem: true,
          widget: ws);

`
我项目使用了getx不知道是不是有冲突.弹出窗口和,不关闭弹窗,直接关闭页面,然后再此进入此页面的时候就会出现这个动画异常

**Comment by xdd666t** [comment]
- 你试试新版本，看看还有没有报错

```dart
dependencies:
  flutter_smart_dialog: ^3.4.0+2
```

你上面说的几种场景，我试了下，都没能成功复现

如果用新版本发现还是有异常，希望你能提供一个能复现问题的最简demo

贴一些不能复现问题的代码片段，真的没啥意义，咱们也不能切实解决这个问题

**Comment by sbiweeq** [comment]
> * 你试试新版本，看看还有没有报错
> 
> ```dart
> dependencies:
>   flutter_smart_dialog: ^3.4.0+2
> ```
> 
> 你上面说的几种场景，我试了下，都没能成功复现
> 
> 如果用新版本发现还是有异常，希望你能提供一个能复现问题的最简demo
> 
> 贴一些不能复现问题的代码片段，真的没啥意义，咱们也不能切实解决这个问题

感谢,目前测试未发现了,是修改了什么吗

**Comment by xdd666t** [comment]
做了一些优化

**Comment by xiaoge668** [comment]
![image](https://user-images.githubusercontent.com/6657242/159897396-abd85bda-70c1-4370-a8c9-706a69321f7e.png)
最新的还会有问题的
flutter:
[VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 487 pos 7: '_ticker != null': AnimationController.reverse() called after AnimationController.dispose()
AnimationController methods should not be used after calling dispose.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:47:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      AnimationController.reverse (package:flutter/src/animation/animation_controller.dart:487:7)
#3      _SmartDialogWidgetState.dismiss (package:flutter_smart_dialog/src/widget/smart_dialog_widget.dart:182:14)
#4      SmartDialogController.dismiss (package:flutter_smart_dialog/src/widget/smart_dialog_widget.dart:208:19)
<asynchronous suspension>
#5      MainDialog.dismiss (package:flutter_smart_dialog/src/custom/main_dialog.dart:145:5)
<asynchronous suspension>
#6      CustomLoading.dismiss (package:flutter_smart_dialog/src/custom/custom_loading.dart:48:5)
<asynchronous suspension>
#7      DialogProxy.dismiss (package:flutter_smart_dialog/src/helper/dialog_proxy.dart:213:7)
<asynchronous suspension>
#8      SmartDialog.dismiss (package:flutter_smart_dialog/src/smart_dialog.dart:580:5)
<asynchronous suspension>
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 487 pos 7: '_ticker != null': AnimationController.reverse() called after AnimationController.dispose()
AnimationController methods should not be used after calling dispose.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:47:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      AnimationController.reverse (package:flutter/src/animation/animation_controller.dart:487:7)
#3      _SmartDialogWidgetState.dismiss (package:flutter_smart_dialog/src/widget/smart_dialog_widget.dart:182:14)
#4      SmartDialogController.dismiss (package:flutter_smart_dialog/src/widget/smart_dialog_widget.dart:208:19)
<asynchronous suspension>
#5      MainDialog.dismiss (package:flutter_smart_dialog/src/custom/main_dialog.dart:145:5)
<asynchronous suspension>
#6      CustomLoading.dismiss (package:flutter_smart_dialog/src/custom/custom_loading.dart:48:5)
<asynchronous suspension>
#7      DialogProxy.dismiss (package:flutter_smart_dialog/src/helper/dialog_proxy.dart:213:7)
<asynchronous suspension>
#8      SmartDialog.dismiss (package:flutter_smart_dialog/src/smart_dialog.dart:580:5)
<asynchronous suspension>
flutter: *** DioError ***:
flutter: uri: https://app-api.tenflect.com/cart/delete_mine_items?item_id=183281
flutter: DioError [DioErrorType.connectTimeout]: Connecting timed out [20000ms]
flutter:
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: DioError [DioErrorType.connectTimeout]: Connecting timed out [20000ms]
Source stack:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:473:35)
#1      DioMixin.request (package:dio/src/dio_mixin.dart:468:12)
#2      DioMixin.get (package:dio/src/dio_mixin.dart:55:12)
#3      HttpManager.deleteProduct (package:povison/common/net/http_manager.dart:729:33)
#4      CartLogic.deleteProduct (package:povison/pages/cart/cart_logic.dart:75:34)
#5      CartPage._buildProductListItemWidget.<anonymous closure> (package:povison/pages/cart/cart_view.dart:101:24)
#6      _CartProductItemWidgetState._buildProductInfoWidget.<anonymous closure> (package:povison/widgets/cart/cart_product_item_widget.dart:207:56)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
#9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#10     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267:7)
#11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:443:20)
#13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
#14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322:11)
#15     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#16     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#19     _rootRunUnary (dart:async/zone.dart:1444:13)
#20     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#22     _invoke1 (dart:ui/hooks.dart:169:10)
#23     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#24     _dispatchPointerDataPacket (dart:ui/hooks.dart:88:31)


#0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:628:7)
#1      _rootRunBinary (dart:async/zone.dart:1452:47)
#2      _CustomZone.runBinary (dart:async/zone.dart:1342:19)
#3      _FutureListener.handleError (dart:async/future_impl.dart:175:22)
#4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:779:47)
#5      Future._propagateToListeners (dart:async/future_impl.dart:800:13)
#6      Future._completeError (dart:async/future_impl.dart:610:5)
#7      _SyncCompleter._completeError (dart:async/future_impl.dart:61:12)
#8      _Completer.completeError (dart:async/future_impl.dart:33:5)
#9      Future.any.onError (dart:async/future.dart:544:45)
#10     _rootRunBinary (dart:async/zone.dart:1452:47)
#11     _CustomZone.runBinary (dart:async/zone.dart:1342:19)
#12     _FutureListener.handleError (dart:async/future_impl.dart:175:22)
#13     Future._propagateToListeners.handleError (dart:async/future_impl.dart:779:47)
#14     Future._propagateToListeners (dart:async/future_impl.dart:800:13)
#15     Future._completeError (dart:async/future_impl.dart:610:5)
#16     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:666:7)
#17     _rootRun (dart:async/zone.dart:1428:13)
#18     _CustomZone.run (dart:async/zone.dart:1328:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

**Comment by xdd666t** [comment]
给个能复现这个问题的demo吧

如果给不了能复现这个问题的demo，恕我无能为力

**Comment by xiaoge668** [comment]
> 

好的，项目不好直接给你，最近几天比较忙，周末有空给你一个demo。我现在用3.0.6的版本了，这个版本没问题。
