### ISSUE TITLE
运行每次都有报错

### ISSUE THREAD

**Issue by 690858187** [fluttercandies/flutter_smart_dialog#36]
<img width="932" alt="image" src="https://user-images.githubusercontent.com/11513292/158540834-8a5f55e0-7aca-4e75-b2b9-8d5557978d6f.png">每次运行为啥都有这个报错呢

**Comment by xdd666t** [comment]
你flutter是啥版本的

**Comment by 690858187** [comment]
我是用的master分支
<img width="738" alt="image" src="https://user-images.githubusercontent.com/11513292/158542476-1cfa7eff-174a-4558-8be6-38ceeb0171a5.png">

**Comment by xdd666t** [comment]
你切到stable版本吧，稳定版WidgetBinding不为空，不需要做空判断

**Comment by 690858187** [comment]
好，我试试
