### ISSUE TITLE
LateInitializationError: Field 'toastBuilder'

### ISSUE THREAD

**Issue by alexlovar** [fluttercandies/flutter_smart_dialog#37]
Hi, i'm calling: SmartDialog.showToast('test toast')  on onpressed event, but i get the follow error:

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: LateInitializationError: Field 'toastBuilder' has not been initialized.
E/flutter ( 6841): #0      DialogProxy.toastBuilder (package:flutter_smart_dialog/src/helper/dialog_proxy.dart)
E/flutter ( 6841): #1      SmartDialog.showToast (package:flutter_smart_dialog/src/smart_dialog.dart:529:46)

**Comment by xdd666t** [comment]
Please read the README before use, you are missing initialization operations

![image](https://user-images.githubusercontent.com/35656085/159195496-d9559a68-f44d-4706-a3b2-b3226a76cc3d.png)
