### ISSUE TITLE
custom show中tag和keepSingle不可以同时为存在吗

### ISSUE THREAD

**Issue by lucky1213** [fluttercandies/flutter_smart_dialog#38]
custom show中tag和keepSingle同时存在时，弹窗不显示

**Comment by xdd666t** [comment]
不是不显示，我加了断言做限制了，你可以看控制台的日志打印

keepSingle和tag同时用，会存在逻辑上的矛盾，我建议你不要同时用

![image](https://user-images.githubusercontent.com/35656085/160137340-45efa343-1e0b-451b-b6a6-66eb6e251ef9.png)
