### ISSUE TITLE
会阻挡页面的默认背景颜色设置，建议改成可对外透传

### ISSUE THREAD

**Issue by liangdas** [fluttercandies/flutter_smart_dialog#4]
class FlutterSmartDialog extends StatelessWidget {
  FlutterSmartDialog({
    Key? key,
    required this.child,
  }) : super(key: key);

  final Widget? child;

  @override
  Widget build(BuildContext context) {
    return Material(
      color: Colors.lightBlue,// 这里可以改为可传

**Comment by CNAD666** [comment]
大兄弟，material这地方，我没加颜色值啊
![image](https://user-images.githubusercontent.com/35656085/117309107-b80ae480-aeb4-11eb-930a-19016a68aa1c.png)

**Comment by CNAD666** [comment]
你如果想定义遮罩颜色

可以使用show方法自定以，maskColorTemp参数就可以设置遮罩颜色了

```dart
SmartDialog.show(
    maskColorTemp: Colors.amber.withOpacity(0.2),
    alignmentTemp: Alignment.bottomCenter,
    widget: Container(height: 100, color: Colors.black),
);
```

**Comment by liangdas** [comment]
比如想改应用的最底色背景

**Comment by CNAD666** [comment]
是不是Material本身的颜色是灰色，你的应用上层页面改成半透明的颜色，会产生色值混淆的情况？

**Comment by CNAD666** [comment]
底层背景已经改为透明色了，请更新到2.0.5版本
```
dependencies:
  flutter_smart_dialog: ^2.0.5
```
issue先关了，有问题再提
