### ISSUE TITLE
showToast是否可以位于系统dialog之上？

### ISSUE THREAD

**Issue by lucky1213** [fluttercandies/flutter_smart_dialog#40]

**Comment by xdd666t** [comment]
是位于Flutter 自带的Dialog之上

但是应该无法显示在原生的弹窗上面，这个需要你自行使用各原生的toast

**Comment by lucky1213** [comment]
不是啊，我先用material/dialog弹出一个框之后调用插件的showToast，实际上toast是被遮住的

**Comment by xdd666t** [comment]
你是不是没初始化？

![image](https://user-images.githubusercontent.com/35656085/161202314-78517e98-5e66-4321-8039-f6b5861c4d50.png)

**Comment by lucky1213** [comment]
<img width="722" alt="image" src="https://user-images.githubusercontent.com/37032543/161202599-4bcb2716-c4aa-4ab7-b748-c54698224922.png">
初始化过了

**Comment by xdd666t** [comment]
按理来说，toast是不可能置于flutter dialog之下

你提供下可复现问题的最简demo吧，我看看是什么原因

**Comment by lucky1213** [comment]
我尝试了一下系统dialog上设置useRootNavigator: fasle则不会被遮挡，这个能帮助你定位问题吗？如需demo晚些提供

**Comment by xdd666t** [comment]
给个可复现问题的demo吧

**Comment by xdd666t** [comment]
先关了，后面要是还有问题，重新开个issue，并提供下可复现的demo
