### ISSUE TITLE
调用 SmartToastType.last 的toast 之后，再调用SmartToastType.normal的toast，第一个toast会一直显示不消失

### ISSUE THREAD

**Issue by pinguo-laihouxin** [fluttercandies/flutter_smart_dialog#42]
### 版本信息
- Flutter版本：v2.10.3
- flutter_smart_dialog版本：v3.4.1

### 描述bug/需求
调用 SmartToastType.last 的toast 之后，再调用SmartToastType.normal的toast，第一个toast会一直显示不消失
### 问题demo
```
SmartDialog.showToast('last', type: SmartToastType.last);
await Future.delayed(Duration(seconds: 1));
SmartDialog.showToast('normal');
```

**Comment by xdd666t** [comment]
这个问题比较复杂，涉及到各种状态之间的转化，又不能影响到之前存储toast的队列；我尝试引入中间队列的方式解决这个问题，测了很多场景下的状态变化，toast效果都可以达到预期

- 你更新下版本试试吧

```dart
dependencies:
  flutter_smart_dialog: ^3.4.2
```

如果还有问题，欢迎继续反馈

**Comment by pinguo-laihouxin** [comment]
谢谢大佬，试了下，不会有一只显示的bug了，但是有个疑问，我如果先用了normal 的toast，然后马上用last的toast，这时候还得等normal的消失了才展示last的，不太符合预期呢，因为有些特殊的toast，是希望把优先级提到最高，可以立即顶掉当前toast

**Comment by xdd666t** [comment]
last状态实现逻辑很特殊，我建议你不要把这个状态和其它状态混用，不然可能会出现非预期效果

- 你更新下版本吧

```dart
dependencies:
  flutter_smart_dialog: ^3.4.2+2
```

- 使用 `SmartStatus.allToast ` 状态可以解决你这个问题

```dart
for(var i = 1; i <= 6; i++ ) {
  SmartDialog.showToast('test toast---$i');
}
await Future.delayed(Duration(milliseconds: 1500));
await SmartDialog.dismiss(status: SmartStatus.allToast);
SmartDialog.showToast("priority display");
```

**Comment by xdd666t** [comment]
目前，3.x的版本已经不适合在config里面加东西了（职能比较混乱）

我现在正在写4.0版本，type已经移到了toast的config中，4.0发布了，我会在这条toast里面提醒下你

**Comment by pinguo-laihouxin** [comment]
嗯，好的，多谢大佬！

**Comment by xdd666t** [comment]
这个属性新版本中已经加入了config，有需要的话，可参照：https://juejin.cn/post/7093867453012246565

**Comment by pinguo-laihouxin** [comment]
> 

感谢，已经迁移
