### ISSUE TITLE
MaterialApp.router没有navigatorObserverss属性

### ISSUE THREAD

**Issue by JDongKhan** [fluttercandies/flutter_smart_dialog#44]
看文档配置navigatorObservers和builder两个参数，但是以MaterialApp.router方式没有navigatorObservers参数，是否能像flutter_screenutil一样支持方法调用注册。

**Comment by xdd666t** [comment]
- 看了下，使用MaterialApp.router，你需要自己去处理Navigator吧，你可以把路由监控实例放在Navigator中

```dart
Navigator(
  observers: [FlutterSmartDialog.observer],
);
```

![image](https://user-images.githubusercontent.com/35656085/163666818-bac7ec19-c385-40f1-b728-9d3893a9d46c.png)

**Comment by ManInTheWind** [comment]
你在routeDelegate构造函数那里把oversers传进去给navigator就行了

**Comment by JDongKhan** [comment]
@xdd666t  我开发web端，使用的第三方routemaster，目前无法更改它的源码。

**Comment by xdd666t** [comment]
你应该去routemaster的项目开个issue，让他将这类基础的api暴露出来

**Comment by JDongKhan** [comment]
@xdd666t  它提供了一个RoutemasterObserver的数组，继承了NavigatorObserver， 类型不匹配无法传过去。我能在其对应的生命周期直接FlutterSmartDialog.observer的方法？

**Comment by xdd666t** [comment]
- 这不是的吗？？？？？？？？？

![image](https://user-images.githubusercontent.com/35656085/163676793-59cbfaa4-4aff-46a9-bdc1-cbb43b83b51a.png)

**Comment by JDongKhan** [comment]
> * 这不是的吗？？？？？？？？？
> 
> ![image](https://user-images.githubusercontent.com/35656085/163676793-59cbfaa4-4aff-46a9-bdc1-cbb43b83b51a.png)
它的类型是自定义的，我现在是这样写的，正在测试有没有问题。
![image](https://user-images.githubusercontent.com/4929805/163676987-baebd3c4-8325-49db-a490-be34c0b8be34.png)
