### ISSUE TITLE
isPenetrateTemp=TRUE 可穿透的弹窗，跳转至其他页面后。弹窗还在其他页面上显示

### ISSUE THREAD

**Issue by luodongwen** [fluttercandies/flutter_smart_dialog#45]
### 版本信息
- Flutter版本：[v2.8.1]
- flutter_smart_dialog版本：[v3.4.1]

### 需求
isPenetrateTemp=TRUE 可穿透的弹窗，跳转至其他页面后。弹窗还在其他页面上显示，有没有属性能控制弹窗只能在当前页显示，而不是一直在界面最上层

**Comment by xdd666t** [comment]
你看看注释吧，useSystem参数可以解决这个问题

**Comment by luodongwen** [comment]
> 你看看注释吧，useSystem参数可以解决这个问题
可能是我描述得不清楚，我的意思是。我的可穿透弹窗不关闭的情况下，打开新页面，弹窗需要不可见，而不是在新页面的上面

**Comment by xdd666t** [comment]
穿透参数开启的时候，不支持和系统路由页面的交互

你要的这种效果，你自己也是很轻松就能实现的：你点击弹窗后面的页面跳转的时候，这个动作是可知的，你在跳转的时候可以将整个dialog弹窗布局动态的隐藏掉，await 等待就行了，等页面回来的时候，再将dialog显示出来

将dialog绑定到页面上，动态隐藏显示，这个功能后期可能会在4.0版本加上，但是最近刚换了坑，很多事，不确定什么时候弄；建议你自己先弄下，而且4.0版本是个 breaking change

**Comment by luodongwen** [comment]
> 穿透参数开启的时候，不支持和系统路由页面的交互
> 
> 你要的这种效果，你自己也是很轻松就能实现的：你点击弹窗后面的页面跳转的时候，这个动作是可知的，你在跳转的时候可以将整个dialog弹窗布局动态的隐藏掉，await 等待就行了，等页面回来的时候，再将dialog显示出来
> 
> 将dialog绑定到页面上，动态隐藏显示，这个功能后期可能会在4.0版本加上，但是最近刚换了坑，很多事，不确定什么时候弄；建议你自己先弄下，而且4.0版本是个 breaking change

OK，我自己已经改好了，谢谢大佬答疑

**Comment by xdd666t** [comment]
这个功能新版本已经实现了，有需要的话，可参照：https://juejin.cn/post/7093867453012246565
