### ISSUE TITLE
Unhandled Exception: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 487 pos 7: '_ticker != null': AnimationController.reverse() called after AnimationController.dispose()

### ISSUE THREAD

**Issue by luodongwen** [fluttercandies/flutter_smart_dialog#46]
### 版本信息
- Flutter版本：[v2.8.1]
- flutter_smart_dialog版本：[v3.4.1]

### 描述bug
显示loading弹窗的时候会偶尔会报这个异常，
快速切换菜单的时候。多次调用showLoading

### 问题
E/flutter (11733): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 487 pos 7: '_ticker != null': AnimationController.reverse() called after AnimationController.dispose()
E/flutter (11733): AnimationController methods should not be used after calling dispose.
E/flutter (11733):       _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:47:61)
E/flutter (11733):       _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (11733):       AnimationController.reverse (package:flutter/src/animation/animation_controller.dart:487:7)
E/flutter (11733):       _SmartDialogWidgetState.dismiss (package:flutter_smart_dialog/src/widget/smart_dialog_widget.dart:182:14)
E/flutter (11733):      SmartDialogController.dismiss (package:flutter_smart_dialog/src/widget/smart_dialog_widget.dart:208:19)
E/flutter (11733): <asynchronous suspension>
E/flutter (11733):       MainDialog.dismiss (package:flutter_smart_dialog/src/custom/main_dialog.dart:145:5)
E/flutter (11733): <asynchronous suspension>
E/flutter (11733):      CustomLoading.dismiss (package:flutter_smart_dialog/src/custom/custom_loading.dart:48:5)
E/flutter (11733): <asynchronous suspension>
E/flutter (11733):      DialogProxy.dismiss (package:flutter_smart_dialog/src/helper/dialog_proxy.dart:213:7)
E/flutter (11733): <asynchronous suspension>
E/flutter (11733):     SmartDialog.dismiss (package:flutter_smart_dialog/src/smart_dialog.dart:580:5)
E/flutter (11733): <asynchronous suspension>
E/flutter (11733):

**Comment by xdd666t** [comment]
请升到最新版本

```
dependencies:
  flutter_smart_dialog: ^3.4.2+2
```

**Comment by xdd666t** [comment]
这个问题最近新版本已经解决了

如果用了最新版本还出现，建议附上可复现问题的最简demo
