### ISSUE TITLE
getx搭配使用问题

### ISSUE THREAD

**Issue by lobtao** [fluttercandies/flutter_smart_dialog#47]
### 版本信息
- Flutter版本：[举例：v2.8.1]
- flutter_smart_dialog版本：[举例：v^3.4.2+2]

### 描述bug/需求
E/flutter ( 4769): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 4769): #0      new MonitorPopRoute._ (package:flutter_smart_dialog/src/helper/monitor_pop_route.dart:16:28)
E/flutter ( 4769): #1      MonitorPopRoute.instance (package:flutter_smart_dialog/src/helper/monitor_pop_route.dart:13:72)
E/flutter ( 4769): #2      FlutterSmartDialog.monitor (package:flutter_smart_dialog/src/dialog.dart:44:44)
E/flutter ( 4769): #3      FlutterSmartDialog.init (package:flutter_smart_dialog/src/dialog.dart:56:5)
E/flutter ( 4769): #4      main (package:getx_demo/main.dart:16:35)
E/flutter ( 4769): #5      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:129:25)
E/flutter ( 4769): #6      _rootRun (dart:async/zone.dart:1428:13)
E/flutter ( 4769): #7      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 4769): #8      _runZoned (dart:async/zone.dart:1863:10)
E/flutter ( 4769): #9      runZonedGuarded (dart:async/zone.dart:1851:12)
E/flutter ( 4769): #10     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:125:5)
E/flutter ( 4769): #11     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
E/flutter ( 4769): #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
E/flutter ( 4769): 

### 问题demo
void main() {
  runApp(
    GetMaterialApp(
      title: "Application",
      initialRoute: AppPages.INITIAL,
      getPages: AppPages.routes,
      // here
      navigatorObservers: [FlutterSmartDialog.observer],
      // here
      builder: FlutterSmartDialog.init(),
    ),
  );
}

**Comment by xdd666t** [comment]
你把你可复现问题场景的main.dart打包传下

你写个初始化有啥用；我这个功能演示项目，就是搭配getx使用的，没有问题：https://github.com/xdd666t/flutter_use

**Comment by xdd666t** [comment]
服了，你这个初始化写法问题很大，你这样写会导致WidgetBinding未初始化好；你应该把runApp里面的widget提成一个StatelessWidget或者StatefulWidget

![image](https://user-images.githubusercontent.com/35656085/163748129-add15aad-b5ae-45aa-9190-1226ce2b77f6.png)

**Comment by LinMaris** [comment]
@xdd666t  你这根本就没解决问题, 自顾自的把issue给关了

**Comment by xdd666t** [comment]
@LinMaris  真是搞心态，我没解决什么问题？

首先你看懂了我上面的回答？就搁着莫名其妙的来这一句话

他这种初始化，会导致runApp里面操作还没处理，直接就加载GetMaterialApp，这样会导致WidgetBinding.instance没初始化，将GetMaterialApp提成一个widget就行了

3系列的新版本，3.4.7版本也做了兜底处理，按照他那样写也不会报错，你试过吗？你就自顾自的踩一下怼一句
