### ISSUE TITLE
请问dialog能否自适应高度?

### ISSUE THREAD

**Issue by FrankyLee-dev** [fluttercandies/flutter_smart_dialog#48]
![image](https://user-images.githubusercontent.com/17977044/164146965-0697f562-4526-43b5-a8f5-7e6e9720dd23.png)

请问dialog的高度可以实现自适应高度吗？

**Comment by xdd666t** [comment]
。。。。这是布局的基础，你自己去实现的，最外层包一个center，column中mainAxisSize: MainAxisSize.min
