### ISSUE TITLE
与get扩展overlay冲突

### ISSUE THREAD

**Issue by aibow** [fluttercandies/flutter_smart_dialog#5]
get扩展：https://pub.flutter-io.cn/packages/get

`One or more of the specified entries are already present in another Overlay.
'package:flutter/src/widgets/overlay.dart':
Failed assertion: line 370 pos 7: 'entries.every((OverlayEntry entry) => entry._overlay == null)'`

**Comment by CNAD666** [comment]
能贴下你使用getx overlay的代码，最后能贴下小颗粒度代码
我完全懵逼吧，我demo也用了getx，但是没用getx的什么overlay

**Comment by CNAD666** [comment]
先关了，你想起来，再提吧，记得把demo贴上
