### ISSUE TITLE
能不能指定弹窗的层级，解决页面间跳转到问题。

### ISSUE THREAD

**Issue by guotao** [fluttercandies/flutter_smart_dialog#50]
### 版本信息
- Flutter版本：v2.10.4
- flutter_smart_dialog版本：v3.4.1

### 需求
能不能指定弹窗的层级，否则未关闭弹窗是，通过 Navigator.of(context).pushNamed 跳转页面，弹窗仍然会覆盖在新页面上面。关闭弹窗可以解决一部分问题，但是有些弹窗需要返回原页面时仍展示着。

### 问题demo
暂无

**Comment by xdd666t** [comment]
useSystem设置为true

**Comment by xlfdyzcs** [comment]
> useSystem设置为true

有可能新增一个这样的功能么：为弹窗新增一个参数 int priority，通过修改该参数，从而达到精细化指定(修改：已经显示了三个弹窗，想把第一个弹窗显示在最上层或者中间)多个弹窗的层级

**Comment by wengxianxun** [comment]
同问,遇到这个问题,  需要设置层级来显示不同的弹窗位置
