### ISSUE TITLE
Issue on initialization.

### ISSUE THREAD

**Issue by sreejagath** [fluttercandies/flutter_smart_dialog#51]
I am already using a builder function in MaterialApp which is for MediaQuery factors. When it is initialized on that builder function, it shows : 

Unhandled Exception: LateInitializationError: Field 'toastBuilder' has not been initialized.
#0      DialogProxy.toastBuilder (package:flutter_smart_dialog/src/helper/dialog_proxy.dart)
#1      SmartDialog.showToast (package:flutter_smart_dialog/src/smart_dialog.dart:534:46)

**Comment by xdd666t** [comment]
Can you post the init code?

**Comment by sreejagath** [comment]
builder: (context, child) {
            //builder:
            FlutterSmartDialog.init();
            final mediaQueryData = MediaQuery.of(context);
            final scale = mediaQueryData.textScaleFactor.clamp(0.5, 0.9);
            return MediaQuery(
              child: child,
              data: MediaQuery.of(context).copyWith(textScaleFactor: scale),
            );
          }

**Comment by xdd666t** [comment]
- There is something wrong with the way you initialize, please initialize according to the way on the document

![image](https://user-images.githubusercontent.com/35656085/164891082-f83d3951-4349-41fe-93ef-04e9e1efdb1e.png)

- With FlutterSmartDialog.init() you can still use the function builder parameter

![image](https://user-images.githubusercontent.com/35656085/164891146-5d0ed86e-daf8-49d8-a3fb-5234325422f7.png)

**Comment by sreejagath** [comment]
Thanks. Got it.
