### ISSUE TITLE
Loading 在页面初始化之后 调用 不会显示

### ISSUE THREAD

**Issue by vvkeep** [fluttercandies/flutter_smart_dialog#53]
### 版本信息
- Flutter版本：[举例：v2.10.4]
- flutter_smart_dialog版本：[举例：v4.0.0]

### 描述bug/需求
使用GetX框架， 在onInit的时候，调用`SmartDialog.showLoading`,  页面不显示Loading,  放在`onReady`是可以显示的，带页面展示出来候后 ，再次调用就会显示Loading,初步判断和生命周期有关，希望可以快速解决下，我这面花了一上午把Loading 和 Toast替换成你这个库呢，不然又要改回去😂

**Comment by xdd666t** [comment]
写在onReady里面，你把onInit改成onReady就行了，一帧的区别

很多这类dialog框架，都必须等页面渲染后才能去展示页面的

**Comment by vvkeep** [comment]
是的，但是我们项目之前使用的是flutter_easyloading, 这个库是支持放在onInit的，而且我们工程有200多个controller, 那要一个一个改了

**Comment by xdd666t** [comment]
这个我今天看看哈

**Comment by vvkeep** [comment]
好的 thank you!

**Comment by xdd666t** [comment]
这个问题已经解决了，你升级下版本吧

```dart
dependencies:
  flutter_smart_dialog: ^4.0.1
```
