### ISSUE TITLE
flutter 2.10.5 实始化的时候出现以下错误

### ISSUE THREAD

**Issue by gicexxopode** [fluttercandies/flutter_smart_dialog#54]
flutter 2.10.5 实始化的时候出现以下错误
Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null
` builder: (BuildContext context, Widget? child) {
                        FlutterSmartDialog.init(
                          //default toast widget
                          toastBuilder: (String msg) => CustomToastWidget(msg: msg),
                          //default loading widget
                          loadingBuilder: (String msg) => CustomLoadingWidget(msg: msg),
                        );
}`

**Comment by xdd666t** [comment]
4.1.0及其以上的版本适配了flutter 3

flutter 2用4.0.1版本就行了

**Comment by gicexxopode** [comment]
用4.0.1版本之后， Field 'contextOverlay' has not been initialized.

**Comment by xdd666t** [comment]
- 请按照文档初始化好

![image](https://user-images.githubusercontent.com/35656085/168196949-f0101169-b26e-497b-a51f-c2be707e9248.png)

**Comment by xdd666t** [comment]
# 用4.0.1版本之后，

> `Field 'contextOverlay' has not been initialized.
> When the exception was thrown, this was the stack:
> #0 DialogProxy.contextOverlay (package:flutter_smart_dialog/src/helper/dialog_proxy.dart)
> #1 CustomDialog._pushDialog. (package:flutter_smart_dialog/src/custom/custom_dialog.dart:220:30)
> #2 ViewUtils.addRouteSafeUse. (package:flutter_smart_dialog/src/util/view_utils.dart:15:15)
> #3 SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
> #4 SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1089:9)
> #5 SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
> #9 _invoke (dart:ui/hooks.dart:151:10)
> #10 PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
> #11 _drawFrame (dart:ui/hooks.dart:115:31)
> (elided 3 frames from dart:async)
> Application finished`
