### ISSUE TITLE
升级4后，使用默认的toast，aligment 参数不生效了

### ISSUE THREAD

**Issue by EvanJin** [fluttercandies/flutter_smart_dialog#57]
### Version Information
- Flutter version: [e.g. v3.0.0]
- flutter_smart_dialog version: [4.1.0+2]

### Describe the bug/requirement
升级4后，使用默认的toast，aligment 参数不生效，看了下源码，默认都是center，不过ios上展示的时候，是在底部？

**Comment by xdd666t** [comment]
这个参数移除了，alignment和整体的动画有关，和位置无关，位置是自定义的，你可以自定义toast

- 移除说明：https://juejin.cn/post/7093867453012246565#heading-3
- 自定义全局toast或loading：https://github.com/fluttercandies/flutter_smart_dialog/issues/24

**Comment by EvanJin** [comment]
> 这个参数移除了，alignment和整体弹窗的位置及动画有关，和自定义的toast位置无关；toast位置是写死的，你可以自定义toast
> 
> * 移除说明：https://juejin.cn/post/7093867453012246565#heading-3
> * 自定义全局toast或loading：[如何配置全局的自定义loading和toast #24](https://github.com/fluttercandies/flutter_smart_dialog/issues/24)

OK, 多谢这么快回复，那我们关闭这个issues了
