### ISSUE TITLE
ExtendedNestedScrollView 里面 第一次显示不出来

### ISSUE THREAD

**Issue by xietian0908** [fluttercandies/flutter_smart_dialog#58]
### 版本信息
- Flutter版本: v2.10.5
- flutter_smart_dialog版本：v4.0.1

### 描述bug/需求
  在 ExtendedNestedScrollView(
            headerSliverBuilder: _headerSliverBuilder,）
  List<Widget> _headerSliverBuilder(BuildContext context, bool innerBoxIsScrolled) {
    return [
      SliverToBoxAdapter(
        child: Column(
          children: [
            GestureDetector(
              onTap: () {
               /// 第一次显示不出来
                DialogUtils.show(
                  // alignment: Alignment.bottomCenter,
                  // tag: 'send_whatsapp',
                  useSystem: true,
                  widget: const DialogSendWhatsApp(
                      // tag: 'send_whatsapp',
                      ),
                );
              },
              child: Container(
                child: Text('xxx'),
              ),
            ),
...........
_headerSliverBuilder 里面的点击事件 第一次显示弹框不出来

**Comment by xdd666t** [comment]
用4.0.2版本试试

**Comment by xietian0908** [comment]
可以了，感谢🙏




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fluttercandies/flutter_smart_dialog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月17日(星期二) 下午2:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fluttercandies/flutter_smart_dialog] ExtendedNestedScrollView 里面 第一次显示不出来 (Issue #58)





 
用4.0.2版本试试
