### ISSUE TITLE
Get.to 路由跳转到新界面后，没有覆盖住弹框

### ISSUE THREAD

**Issue by yfming93** [fluttercandies/flutter_smart_dialog#6]
某些场景，PopA 是自定义的局部小组件内有一个按钮点击是如下回调处理Get.to 跳转，但是Get.to 路由跳转到登录界面后，期望覆盖住弹框。点击返回后任然可见弹框。除非在SmartDialog 使用界面点击弹框外主动关闭。目前是这个弹框一直在最顶层，跳转到LoginPage 后 弹框还是可见就不符合预期了。
 SmartDialog.show(
              widget: PopA((){
                Get.to(LoginPage());
              }));

问题展示图片：https://i.loli.net/2021/06/09/hyUocMZB7lDNmj6.png

**Comment by yfming93** [comment]
https://i.loli.net/2021/06/09/hyUocMZB7lDNmj6.png

**Comment by CNAD666** [comment]
我懂你的意思，Overlay是位于全局顶层的；这种时候，你可以试下系统Dialog

使用系统Dialog，然后加用Get.to；你是不是遇到了这个问题
![image](https://user-images.githubusercontent.com/35656085/121324101-fe83b100-c942-11eb-88b3-b502e6e411e6.png)

**Comment by yfming93** [comment]
> 我懂你的意思，Overlay是位于全局顶层的；这种时候，你可以试下系统Dialog
> 
> 使用系统Dialog，然后加用Get.to；你是不是遇到了这个问题
> ![image](https://user-images.githubusercontent.com/35656085/121324101-fe83b100-c942-11eb-88b3-b502e6e411e6.png)

谢谢。换成系统showDialog加上 Get.to(XxxxPage(), preventDuplicates: false); 解决了。

**Comment by xdd666t** [comment]
目前SmartDialog已经支持和原生路由交互：https://juejin.cn/post/7026150456673959943

![image](https://user-images.githubusercontent.com/35656085/150621899-66f66064-5d84-49bf-9b4e-a704a79eace2.png)
