### ISSUE TITLE
SmartDialog.showAttach scrollbar 不能设置为isAlwaysShown

### ISSUE THREAD

**Issue by xietian0908** [fluttercandies/flutter_smart_dialog#60]
### 版本信息
- Flutter版本：[v2.10.5]
- flutter_smart_dialog版本：[v4.0.2]

### 描述bug/需求
SmartDialog.showAttach scrollbar 不能设置为isAlwaysShown 
err:ScrollController attached to multiple scroll views.
### 问题demo
```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_smart_dialog/flutter_smart_dialog.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: SmartDialogPage(),
      navigatorObservers: [FlutterSmartDialog.observer],
      builder: FlutterSmartDialog.init(),
    );
  }
}

class SmartDialogPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(title: Text('SmartDialog-EasyDemo')),
      body: Container(
        alignment: Alignment.center,
        child: ElevatedButton(
          onPressed: () => _showAttach(context),
          child: Text('showAttach'),
        ),
      ),
    );
  }

  void _showAttach(BuildContext ctx) {
    final scrolcontroller = ScrollController();

    var attachDialog = (BuildContext context) {
      SmartDialog.showAttach(
        targetContext: context,
        alignment: Alignment.topCenter,
        useSystem: true,
        builder: (_) {
          return Container(
            height: 150,
            child: CupertinoScrollbar(
              isAlwaysShown: true,
              // controller: scrolcontroller,
              child: ListView.builder(
                // controller: scrolcontroller,
                padding: const EdgeInsets.all(0),
                itemBuilder: (_, i) {
                  return Container(
                    width: 50,
                    height: 50,
                    color: Colors.primaries[i],
                  );
                },
                itemCount: Colors.primaries.length - 1,
              ),
            ),
          );
        },
      );
    };

    // var attachDialog = (BuildContext context) {
    //   SmartDialog.show(
    //     // targetContext:/ context,
    //     alignment: Alignment.topCenter,
    //     useSystem: true,
    //     builder: (_) {
    //       return Container(
    //         height: 150,
    //         child: CupertinoScrollbar(
    //           isAlwaysShown: true,
    //           controller: scrolcontroller,
    //           child: ListView.builder(
    //             controller: scrolcontroller,
    //             padding: const EdgeInsets.all(0),
    //             itemBuilder: (_, i) {
    //               return Container(
    //                 width: 50,
    //                 height: 50,
    //                 color: Colors.primaries[i],
    //               );
    //             },
    //             itemCount: Colors.primaries.length - 1,
    //           ),
    //         ),
    //       );
    //     },
    //   );
    // };

    //target widget
    SmartDialog.show(
      useSystem: true,
      builder: (_) {
        return Container(
          height: 300,
          width: 500,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(20),
            color: Colors.white,
          ),
          alignment: Alignment.center,
          child: Builder(builder: (context) {
            return ElevatedButton(
              onPressed: () => attachDialog(context),
              child: Text('target widget'),
            );
          }),
        );
      },
    );
  }
}
```

**Comment by xdd666t** [comment]
提示都这么明显，你的scrollController被用在了多个scroll views上

自己搜搜看，这种问题和SmartDialog无关；想验证和SmartDialog有没有关系，你可以把布局放在页面里和放在SmartDialog上面，看看有没有区别

**Comment by xietian0908** [comment]
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_smart_dialog/flutter_smart_dialog.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: SmartDialogPage(),
      navigatorObservers: [FlutterSmartDialog.observer],
      builder: FlutterSmartDialog.init(),
    );
  }
}

class SmartDialogPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(title: Text('SmartDialog-EasyDemo')),
      body: Container(
        margin: EdgeInsets.all(30),
        child: Wrap(spacing: 20, children: [
          //toast
          ElevatedButton(
            onPressed: () => _showToast(),
            child: Text('showToast'),
          ),

          //loading
          ElevatedButton(
            onPressed: () => _showLoading(),
            child: Text('showLoading'),
          ),

          //dialog
          ElevatedButton(
            onPressed: () => _show(),
            child: Text('show'),
          ),

          //attach
          ElevatedButton(
            onPressed: () => _showAttach(context),
            child: Text('showAttach'),
          ),

          //attach
          ElevatedButton(
            onPressed: () => _bindPage(context),
            child: Text('bindPage'),
          ),
        ]),
      ),
    );
  }

  void _showToast() async {
    await SmartDialog.showToast('test toast');
    print('--------------------------');
  }

  void _show() {
    SmartDialog.show(builder: (_) {
      return Container(
        height: 80,
        width: 180,
        decoration: BoxDecoration(
          color: Colors.black,
          borderRadius: BorderRadius.circular(10),
        ),
        alignment: Alignment.center,
        child: Text(
          'easy custom dialog',
          style: TextStyle(color: Colors.white),
        ),
      );
    });
  }

  void _showAttach(BuildContext ctx) {
    final scrolcontroller = ScrollController();

    // var attachDialog = (BuildContext context) {
    //   SmartDialog.showAttach(
    //     targetContext: context,
    //     alignment: Alignment.topCenter,
    //     useSystem: true,
    //     builder: (_) {
    //       return Container(
    //         height: 150,
    //         child: CupertinoScrollbar(
    //           isAlwaysShown: true,
    //           controller: scrolcontroller,
    //           child: ListView.builder(
    //             controller: scrolcontroller,
    //             padding: const EdgeInsets.all(0),
    //             itemBuilder: (_, i) {
    //               return Container(
    //                 width: 50,
    //                 height: 50,
    //                 color: Colors.primaries[i],
    //               );
    //             },
    //             itemCount: Colors.primaries.length - 1,
    //           ),
    //         ),
    //       );
    //     },
    //   );
    // };
    var attachDialog = (BuildContext context) {
      SmartDialog.show(
        // targetContext:/ context,
        alignment: Alignment.topCenter,
        useSystem: true,
        builder: (_) {
          return Container(
            height: 150,
            child: CupertinoScrollbar(
              isAlwaysShown: true,
              controller: scrolcontroller,
              child: ListView.builder(
                controller: scrolcontroller,
                padding: const EdgeInsets.all(0),
                itemBuilder: (_, i) {
                  return Container(
                    width: 50,
                    height: 50,
                    color: Colors.primaries[i],
                  );
                },
                itemCount: Colors.primaries.length - 1,
              ),
            ),
          );
        },
      );
    };

    //target widget
    SmartDialog.show(
      useSystem: true,
      builder: (_) {
        return Container(
          height: 300,
          width: 500,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(20),
            color: Colors.white,
          ),
          alignment: Alignment.center,
          child: Builder(builder: (context) {
            return ElevatedButton(
              onPressed: () => attachDialog(context),
              child: Text('target widget'),
            );
          }),
        );
      },
    );
  }

  void _bindPage(BuildContext ctx) {
    //target widget
    SmartDialog.show(
      bindPage: true,
      builder: (_) {
        return Container(
          height: 300,
          width: 500,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(20),
            color: Colors.white,
          ),
          alignment: Alignment.center,
          child: ElevatedButton(
            onPressed: () {
              Navigator.push(ctx, MaterialPageRoute(builder: (_) {
                return Scaffold(
                  appBar: AppBar(
                    title: Text("New Page"),
                  ),
                  body: Center(child: Text("New Page")),
                );
              }));
            },
            child: Text('to new page'),
          ),
        );
      },
    );
  }

  void _showLoading() async {
    SmartDialog.showLoading();
    await Future.delayed(Duration(seconds: 2));
    SmartDialog.dismiss();
  }
}

**Comment by xietian0908** [comment]
试一下_showAttach里面的两个attachDialog方法，一个是可以的一个是有那个问题的；

**Comment by xietian0908** [comment]
大哥 我重新弄了份demo 放在那个问题里面了==&gt;
我的问题是只有在使用showattach的时候才会出现那个attached to more than one scrollpositoin的问题；我也很奇怪也检查了这个controller是否存在被多个使用但是事实就只存在listview 和 scrollbar使用(正常show 和 普通使用都是ok的)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fluttercandies/flutter_smart_dialog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月29日(星期天) 下午4:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fluttercandies/flutter_smart_dialog] SmartDialog.showAttach scrollbar 不能设置为isAlwaysShown (Issue #60)





 
提示都这么明显，你的scrollController被用在了多个scroll views上
 
自己搜搜看，这种问题和SmartDialog无关；想验证和SmartDialog有没有关系，你可以把布局放在页面里和放在SmartDialog上面，看看有没有区别

**Comment by xdd666t** [comment]
排查了下，确实是showAttach的一个bug，定位的实现和Scrollbar的一些机制冲突了，我想了一些办法，解决了这个问题

你可以升级下插件版本试试

- flutter 2

```dart
dependencies:
  flutter_smart_dialog: 4.0.3
```

- flutter 3

```dart
dependencies:
  flutter_smart_dialog: ^4.3.2
```

**Comment by xietian0908** [comment]
嗯嗯,可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fluttercandies/flutter_smart_dialog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月30日(星期一) 上午10:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fluttercandies/flutter_smart_dialog] SmartDialog.showAttach scrollbar 不能设置为isAlwaysShown (Issue #60)





 
排查了下，确实是showAttach的一个bug，定位的实现和Scrollbar的一些机制冲突了，我想了一些办法，解决了这个问题
 
你可以升级下插件版本试试
  
flutter 2
  dependencies:   flutter_smart_dialog: 4.0.3
  
flutter 3
  dependencies:   flutter_smart_dialog: ^4.3.2
