### ISSUE TITLE
求助showLoading要加上进度百分比该怎么做？

### ISSUE THREAD

**Issue by roger66** [fluttercandies/flutter_smart_dialog#62]
### 版本信息
- Flutter版本：v3.0.1
- flutter_smart_dialog版本：v4.3.2+1

**Comment by xdd666t** [comment]
用builder参数去自定义进度加载样式

**Comment by roger66** [comment]
> 用builder参数去自定义进度加载样式

自定义我懂，怎么在一次loading的情况下去更新百分比

**Comment by xdd666t** [comment]
你的问题，无非是在外部通过传进度不间断的刷新你自定义的loading控件

方法有很多

- 如果用getx框架，可以直接用GetBuilder在进度改变的时候，去刷新你的自动loading
- 或者事件总线的方式去传递数据通知刷新
- 也可以参考一些控制器的实现Textfield之类的，在外部控制控件的刷新
- 也可以参考回调的方式在外部控制：https://juejin.cn/post/7026150456673959943#heading-16
![image](https://user-images.githubusercontent.com/35656085/171589316-328a8fcf-f802-433f-99ea-ed0cdf133a0a.png)

**Comment by roger66** [comment]
> 你的问题，无非是在外部通过传进度不间断的刷新你自定义的loading控件
> 
> 方法有很多
> 
> * 如果用getx框架，可以直接用GetBuilder在进度改变的时候，去刷新你的自定义loading
> * 或者事件总线的方式去传递数据通知刷新
> * 也可以参考一些控制器的实现Textfield之类的，在外部控制控件的刷新
> * 也可以参考回调的方式在外部控制：https://juejin.cn/post/7026150456673959943#heading-16
> 
> ![image](https://user-images.githubusercontent.com/35656085/171589316-328a8fcf-f802-433f-99ea-ed0cdf133a0a.png)

好的，谢谢
