### ISSUE TITLE
loading

### ISSUE THREAD

**Issue by MaLonghui** [fluttercandies/flutter_smart_dialog#63]
### 版本信息
- Flutter版本：3.0
- flutter_smart_dialog版本：4.3.1

### 描述bug/需求
在factory修饰的方法之前调用showloading不会显示，要等到factory的那个方法执行完才执行loading

**Comment by xdd666t** [comment]
什么意思？你说实例化前后？？？

**Comment by MaLonghui** [comment]
`/// SmartDialog.showLoading(builder: (_) => const CustomLoading(type: 2,));
    /// factory Class.xxx()
    /// SmartDialog.dismiss();`
我的代码大概是这样，但是不会显示。如果把dismiss去掉，就会在factory之后显示loading

**Comment by xdd666t** [comment]
你直接写，打开loading之后，就dismiss关掉了loading，loading咋显示呢；去掉dismiss，loading就没关掉，还在界面，这有啥问题

**Comment by MaLonghui** [comment]
去掉dismiss也是先执行的factory方法，执行完才showloading的，但是showLoading方法是写在factory之前的

**Comment by xdd666t** [comment]
showLoading是个Futrue方法，会被添加事件队列中，执行完main中的方法，才会去执行微任务队列和事件队列中的方法

![image](https://user-images.githubusercontent.com/35656085/174038351-587816ed-96ae-4400-ae59-0d31fcf4533a.png)

**Comment by xdd666t** [comment]
你没加async和await修饰吧

**Comment by xdd666t** [comment]
factory一般代表工厂模式，是来封装类，做单例的效果；我不太明白你这边用法的意思

这个问题，好像和SmartDialog没关系，你用任何Future方法估计也是同样的表现，issue先关了
