### ISSUE TITLE
loading如何监听back事件 ？

### ISSUE THREAD

**Issue by ElleCity06** [fluttercandies/flutter_smart_dialog#66]
### 版本信息
- Flutter版本：[举例：v3.0.1]
- flutter_smart_dialog版本：[举例：v4.5.3+2]

showLoading 如何监听back事件，我现在dismiss的时候做一些取消的操作 。

**Comment by xdd666t** [comment]
- 升下版本吧，加了个onDismiss，可以解决你这个问题

```
dependencies:
  flutter_smart_dialog: ^4.5.3+3
```
