### ISSUE TITLE
使用Navigator.push的时候弹窗一直在最顶层，bingPage和useSystem都没有效果

### ISSUE THREAD

**Issue by muggleXin** [fluttercandies/flutter_smart_dialog#67]
### 版本信息
- Flutter版本：[举例：v2.15.0]
- flutter_smart_dialog版本：[举例：v4.5.3+2]

### 问题demo
代码大概是这样：
```dart
SmartDialog.show(
  builder: (_) {
    return InkWell(
      onTap: () {
        Navigator.push(
          context,
          MaterialPageRoute<WineDetailsScreen>(
            builder: (BuildContext context) => PricePage(),
          ),
        );
      },
      child: Container(
        color: Colors.red,
        width: 300,
        height: 300,
      ),
    );
  },
);
```
业务逻辑是这样：我在A页面打开弹窗之后点击跳转到B页面，在B获取到数据之后把数据带入弹窗。但是目前弹窗一直显示在最上层，把新页面挡住了，试了下bingPage和useSystem都没有效果，请大佬指点一下，万分感谢！

**Comment by muggleXin** [comment]
![1656464774924](https://user-images.githubusercontent.com/105698719/176329483-16ee637c-575b-45b6-bb0a-7f297755214e.jpg)

**Comment by muggleXin** [comment]
![WechatIMG56](https://user-images.githubusercontent.com/105698719/176329533-be696282-4baa-430f-94ae-a231301c9fc9.jpeg)

**Comment by xdd666t** [comment]
- 我这边测了，不会覆盖到跳转页面上的，这是我的测试代码

```
SmartDialog.show(builder: (_) {
  return InkWell(
    onTap: () {
      Navigator.push(
        ctx,
        MaterialPageRoute(builder: (BuildContext context) {
          return Container(color: Colors.blue);
        }),
      );
    },
    child: Container(color: Colors.red, width: 300, height: 300),
  );
});
```

- 初始化的时候，路由监听参数加了吗？

![image](https://user-images.githubusercontent.com/35656085/176343277-7feff8f9-1302-4013-ae74-c0fa5e5aa453.png)

**Comment by xdd666t** [comment]
我这边试了bindPage和useSystem都是没问题，这个先关了

如果你还是有疑问，建议写个最小颗粒度demo验证下，或者用我上面的demo代码验证下也行

要是能给出可复现的场景代码，可以再提一个issue哈

**Comment by qflbai** [comment]
问题同上：使用Navigator.push的时候弹窗一直在最顶层
版本：flutter：3.3.4 dart：2.18.2，flutter_smart_dialog: ^4.5.5+6
`  static void upDataTip(BuildContext mContext, AppUpdateInfo appUpdateInfo) {
    SmartDialog.show(
        builder: (_) {
          return UpdateDialog(
            data: appUpdateInfo,
            onTap: () {
              if (Platform.isAndroid) {
                SmartDialog.dismiss();
                AppNavigator.push(
                    mContext, AppUpdatePage(appUpdateInfo: appUpdateInfo));
              } else {
                //跳转应用商店
                RUpgrade.upgradeFromAppStore(
                  '您的AppId', //例如:微信的AppId:414478124
                );
              }
            },
          );
        },
        backDismiss: false,
        keepSingle: true,
        bindPage: true,
        clickMaskDismiss: false);
  }`

**Comment by xdd666t** [comment]
@qflbai 贴下你是怎么初始化的

**Comment by qflbai** [comment]
`MultiProvider(
        providers: providers,
        child: Consumer2<LanguageModel, ThemeModel>(
          builder: (context, languageModel, themeData, child) {
            return MaterialApp(
              supportedLocales: LocalizationDelegateManage.supportedLocales,
              localizationsDelegates: [
                ...LocalizationDelegateManage.localizationsDelegates
              ],
              localeListResolutionCallback: (locales, supportedLocales) {
                if (locales?.isNotEmpty == true) {
                  languageModel.setCurrentLanguageInfo(locales![0]);
                }
              },
              useInheritedMediaQuery: true,
              locale: languageModel.locale,
              theme: themeData.themeData(),
              navigatorObservers: [
                FlutterSmartDialog.observer,
                defaultLifecycleObserver
              ],
              /*builder: FlutterSmartDialog.init(builder: (context, child) {
                return DevicePreview(builder: (context) {
                  return MediaQuery(
                    //Setting font does not change with system font size
                    data: MediaQueryData.fromWindow(
                            WidgetsBinding.instance.window)
                        .copyWith(textScaleFactor: 1),
                    child: child!,
                  );
                });
              }),*/
              builder: FlutterSmartDialog.init(builder: (context, child) {
                return MediaQuery(
                  //Setting font does not change with system font size
                  data:
                      MediaQueryData.fromWindow(WidgetsBinding.instance.window)
                          .copyWith(textScaleFactor: 1),
                  child: child!,
                );
              }),
              debugShowCheckedModeBanner: false,
              onGenerateRoute: MyRouter.generateRoute,
              initialRoute: RouteName.splash,
            );
          },
        ))`

**Comment by qflbai** [comment]
`MultiProvider(
        providers: providers,
        child: Consumer2<LanguageModel, ThemeModel>(
          builder: (context, languageModel, themeData, child) {
            return MaterialApp(
              supportedLocales: LocalizationDelegateManage.supportedLocales,
              localizationsDelegates: [
                ...LocalizationDelegateManage.localizationsDelegates
              ],
              localeListResolutionCallback: (locales, supportedLocales) {
                if (locales?.isNotEmpty == true) {
                  languageModel.setCurrentLanguageInfo(locales![0]);
                }
              },
              useInheritedMediaQuery: true,
              locale: languageModel.locale,
              theme: themeData.themeData(),
              navigatorObservers: [
                FlutterSmartDialog.observer,
                defaultLifecycleObserver
              ],
              /*builder: FlutterSmartDialog.init(builder: (context, child) {
                return DevicePreview(builder: (context) {
                  return MediaQuery(
                    //Setting font does not change with system font size
                    data: MediaQueryData.fromWindow(
                            WidgetsBinding.instance.window)
                        .copyWith(textScaleFactor: 1),
                    child: child!,
                  );
                });
              }),*/
              builder: FlutterSmartDialog.init(builder: (context, child) {
                return MediaQuery(
                  //Setting font does not change with system font size
                  data:
                      MediaQueryData.fromWindow(WidgetsBinding.instance.window)
                          .copyWith(textScaleFactor: 1),
                  child: child!,
                );
              }),
              debugShowCheckedModeBanner: false,
              onGenerateRoute: MyRouter.generateRoute,
              initialRoute: RouteName.splash,
            );
          },
        ))`

**Comment by qflbai** [comment]
FlutterSmartDialog.observer
 FlutterSmartDialog.init(builder: (context, child)
这两个都初始化了

**Comment by xdd666t** [comment]
你这贴的都是什么鬼，不能格式化下吗？

你这种刷新全局MaterialApp写法很少见，你可以尝试设置下useSystem:true，可能也能解决你的问题

如果不能解决问题，你看看能不能给个可复现场景的最简可执行的main文件demo

**Comment by qflbai** [comment]
`
 @override
  void initState() {
    super.initState();
    upgrade();
  }

`

**Comment by Dabbit-Chan** [comment]
刚好也遇到了类似的问题。我用了`GetMaterialApp.route`，然后路由跳转用的是`Get.to`。我在一个statefulWidget的initState阶段调用了`SmartDialog.show`。在这种情况下，`bindPage: true`不起作用，只有`bindWidget: context`且路由跳转使用原来的`Navigator.of(context).push`才能做到弹窗隐藏的效果。 @xdd666t

**Comment by xdd666t** [comment]
@Dabbit-Chan 路由监听没加吧

- 参考他的用法：#69

![image](https://user-images.githubusercontent.com/35656085/227136950-77860b8d-90a5-4c55-a01e-bef8f2fa8d67.png)

**Comment by Dabbit-Chan** [comment]
> @Dabbit-Chan 路由监听没加吧
> 
> * 参考他的用法：[与Navigator2.0好像不兼容 #69](https://github.com/fluttercandies/flutter_smart_dialog/issues/69)
> 
> ![image](https://user-images.githubusercontent.com/35656085/227136950-77860b8d-90a5-4c55-a01e-bef8f2fa8d67.png)

哦哦，原来2.0要加在这！我把这个加在`GetMaterialApp.route`里了。`MaterialApp.route`根本就没`navigatorObservers`这个东西，上当了

**Comment by felix0324324** [comment]
> > @Dabbit-Chan 路由监听没加吧
> > 
> > * 参考他的用法：[与Navigator2.0好像不兼容 #69](https://github.com/fluttercandies/flutter_smart_dialog/issues/69)
> > 
> > ![image](https://user-images.githubusercontent.com/35656085/227136950-77860b8d-90a5-4c55-a01e-bef8f2fa8d67.png)
> 
> 哦哦，原来2.0要加在这！我把这个加在`GetMaterialApp.route`里了。`MaterialApp.route`根本就没`navigatorObservers`这个东西，上当了

@Dabbit-Chan  @xdd666t  
試了好一陣子還是不太懂 "GetMaterialApp" 加 FlutterSmartDialog.init() 和 [FlutterSmartDialog.observer]的地方
可以再給我多一點提示嗎? 
因上面說的 Navigator() 我完全找不到...

**Comment by xdd666t** [comment]
这个issue里面有完整代码，可以点进去看下：https://github.com/fluttercandies/flutter_smart_dialog/issues/69

**Comment by felix0324324** [comment]
> 这个issue里面有完整代码，可以点进去看下：#69

有關Getx的GetMaterialApp的結構應該很不同...暈了

```
return GetMaterialApp.router(
        routerDelegate: delegate,
        navigatorObservers: [FlutterSmartDialog.observer],
        debugShowCheckedModeBanner: false,
        getPages: AppPages.routes,
        builder: FlutterSmartDialog.init());
```

<img width="1344" alt="螢幕截圖 2023-03-30 下午4 04 24" src="https://user-images.githubusercontent.com/16462532/228770906-c177bf30-8eb0-4a84-a82f-9b61a63a6810.png">
