### ISSUE TITLE
dialog里用inkwell水波纹组件貌似不起作用呢

### ISSUE THREAD

**Issue by panyy** [fluttercandies/flutter_smart_dialog#74]

**Comment by xdd666t** [comment]
给下复现代码

**Comment by panyy** [comment]
`static ensureDialog(String title, {Function? confirmFun}) {
    SmartDialog.show(
        animationType: SmartAnimationType.fade,
        builder: (_) {
          return Container(
            height: 120,
            width: 280.5,
            decoration: BoxDecoration(
              color: Colours.white,
              borderRadius: BorderRadius.circular(10),
            ),
            alignment: Alignment.center,
            child: Column(
              children: [
                Expanded(
                  child: Center(
                    child: Text(
                      title,
                      style: const TextStyle(
                          fontSize: 15, color: Colours.color_323232),
                    ),
                  ),
                ),
                const Divider(
                  height: 0,
                  thickness: 0.5,
                  color: Colours.color_e8e8e8,
                ),
                Row(
                  children: [
                    InkWell(
                      onTap: () {
                        SmartDialog.dismiss();
                      },
                      child: Container(
                          width: 140,
                          height: 42,
                          alignment: Alignment.center,
                          child: const Text(
                            '取消',
                            style: TextStyle(
                                fontSize: 15, color: Colours.color_8a000000),
                          )),
                    ),
                    Container(
                      width: 0.5,
                      height: 42,
                      color: Colours.color_e8e8e8,
                    ),
                    InkWell(
                      onTap: () {
                        SmartDialog.dismiss();
                        if (confirmFun != null) {
                          confirmFun();
                        }
                      },
                      child: Container(
                          width: 140,
                          height: 42,
                          alignment: Alignment.center,
                          child: const Text(
                            '确定',
                            style: TextStyle(
                                fontSize: 15, color: Colours.color_3393ff),
                          )),
                    ),
                  ],
                ),
              ],
            ),
          );
        });
  }`

**Comment by panyy** [comment]
```
static ensureDialog(String title, {Function? confirmFun}) {
    SmartDialog.show(
        animationType: SmartAnimationType.fade,
        builder: (_) {
          return Container(
            height: 120,
            width: 280.5,
            decoration: BoxDecoration(
              color: Colours.white,
              borderRadius: BorderRadius.circular(10),
            ),
            alignment: Alignment.center,
            child: Column(
              children: [
                Expanded(
                  child: Center(
                    child: Text(
                      title,
                      style: const TextStyle(
                          fontSize: 15, color: Colours.color_323232),
                    ),
                  ),
                ),
                const Divider(
                  height: 0,
                  thickness: 0.5,
                  color: Colours.color_e8e8e8,
                ),
                Row(
                  children: [
                    InkWell(
                      onTap: () {
                        SmartDialog.dismiss();
                      },
                      child: Container(
                          width: 140,
                          height: 42,
                          alignment: Alignment.center,
                          child: const Text(
                            '取消',
                            style: TextStyle(
                                fontSize: 15, color: Colours.color_8a000000),
                          )),
                    ),
                    Container(
                      width: 0.5,
                      height: 42,
                      color: Colours.color_e8e8e8,
                    ),
                    InkWell(
                      onTap: () {
                        SmartDialog.dismiss();
                        if (confirmFun != null) {
                          confirmFun();
                        }
                      },
                      child: Container(
                          width: 140,
                          height: 42,
                          alignment: Alignment.center,
                          child: const Text(
                            '确定',
                            style: TextStyle(
                                fontSize: 15, color: Colours.color_3393ff),
                          )),
                    ),
                  ],
                ),
              ],
            ),
          );
        });
  }
```

**Comment by xdd666t** [comment]
- 基础小知识：InkWell点击效果，需要基于Material控件

```dart
SmartDialog.show(
  animationType: SmartAnimationType.fade,
  builder: (_) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(10),
      child: Material(
        color: Colors.white,
        child: Container(
          height: 120,
          width: 280.5,
          alignment: Alignment.center,
          child: Column(children: [
            Expanded(child: Center(child: Text("提示"))),
            const Divider(height: 0, thickness: 0.5),
            Row(children: [
              InkWell(
                onTap: () {
                  SmartDialog.dismiss();
                },
                child: Container(
                  width: 140,
                  height: 42,
                  alignment: Alignment.center,
                  child: const Text('取消'),
                ),
              ),
              Container(width: 0.5, height: 42, color: Colors.black12),
              InkWell(
                onTap: () {
                  SmartDialog.dismiss();
                },
                child: Container(
                  width: 140,
                  height: 42,
                  alignment: Alignment.center,
                  child: const Text('确定'),
                ),
              ),
            ]),
          ]),
        ),
      ),
    );
  },
);
```

**Comment by panyy** [comment]
好的，多谢大佬，我是个新手，哈哈
