### ISSUE TITLE
replaceBuilder 未正确生效

### ISSUE THREAD

**Issue by sabernwj** [fluttercandies/flutter_smart_dialog#78]
### 版本信息
- Flutter版本：3.3
- flutter_smart_dialog版本：4.5.5+1

### 描述bug/需求
SmartDialog.showAttach中
replaceBuilder被调用后视图未更新
手动HotReload后正确显示replaceBuilder结果

**Comment by xdd666t** [comment]
这个是解耦动画实现的时候导致的，已经解决了，更新下版本试试

```dart
dependencies:
  flutter_smart_dialog: ^4.5.5+2
```

**Comment by sabernwj** [comment]
OK，感谢
