### ISSUE TITLE
使用了flutterboost导致无法返回dismiss

### ISSUE THREAD

**Issue by ProerMo** [fluttercandies/flutter_smart_dialog#79]
### 版本信息
- Flutter版本：3.0.4
- flutter_smart_dialog版本：4.5.1

### 描述bug/需求
使用了flutterboost，初始化已经按照文档进行，点击系统返回按键，页面先返回，dialog不dismiss

**Comment by xdd666t** [comment]
填下你初始化的代码

**Comment by ProerMo** [comment]
Widget appBuilder(Widget home) {
    jhDebug.setGlobalKey = commonConfig.getGlobalKey;
    appSetupInit();

    var initSmartDialog = FlutterSmartDialog.init();

    return Consumer<ThemeStore>(
      builder: (context, themeStore, child) {
        return MaterialApp(
          navigatorKey: jhDebug.getNavigatorKey,
          showPerformanceOverlay: false,
          locale: const Locale('zh', 'CH'),
          localizationsDelegates: const [
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          supportedLocales: const [
            Locale('zh', 'CH'),
          ],
          theme: themeStore.getTheme,
          // 如果是单独编译就把initialRoute打开
          initialRoute: SINGLE_COMPILE ? initialRoute : null,
          // 如果是集成编译就把home打开
          home: SINGLE_COMPILE ? null : home,
          onGenerateRoute: generateRoute,
          // 路由处理
          debugShowCheckedModeBanner: false,
          navigatorObservers: [FlutterSmartDialog.observer],
          builder: (context, child) => initSmartDialog(context, home),
        );
      },
    );
  }

**Comment by ProerMo** [comment]
老哥回复速度也太快了吧，给老哥点赞

**Comment by xdd666t** [comment]
- 初始化代码要放在appBuilder之前

![image](https://user-images.githubusercontent.com/35656085/191402071-a8e6c9b6-c4af-48d6-9c6d-a9159e0893ae.png)

**Comment by ProerMo** [comment]
改成这样了，还是不行
```
  Widget appBuilder(Widget home) {
    jhDebug.setGlobalKey = commonConfig.getGlobalKey;
    appSetupInit();

    return Consumer<ThemeStore>(
      builder: (context, themeStore, child) {
        return MaterialApp(
          navigatorKey: jhDebug.getNavigatorKey,
          showPerformanceOverlay: false,
          locale: const Locale('zh', 'CH'),
          localizationsDelegates: const [
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          supportedLocales: const [
            Locale('zh', 'CH'),
          ],
          theme: themeStore.getTheme,
          // 如果是单独编译就把initialRoute打开
          initialRoute: SINGLE_COMPILE ? initialRoute : null,
          // 如果是集成编译就把home打开
          home: SINGLE_COMPILE ? null : home,
          onGenerateRoute: generateRoute,
          // 路由处理
          debugShowCheckedModeBanner: false,
          navigatorObservers: [FlutterSmartDialog.observer],
          builder: (context, child) => initSmartDialog(context, home),
        );
      },
    );
  }

  late var initSmartDialog;

  @override
  Widget build(BuildContext context) {
    initSmartDialog = FlutterSmartDialog.init();
    return FlutterBoostApp(
      routeFactory,
      appBuilder: appBuilder,
    );
  }
```

**Comment by xdd666t** [comment]
你简化下代码吧，给下可复现这个场景，可执行的main文件demo

- 按理来说是可以，因为很多人都用过了，我自己之前也试过

**Comment by xdd666t** [comment]
这个先关了，如果还有问题，请提供下可复现问题的最简demo，重新开个issue

**Comment by xdd666t** [comment]
@yye824 @ProerMo 这个问题应该解决了，请重新看下这个issue，使用说明已更新：https://github.com/fluttercandies/flutter_smart_dialog/issues/64

**Comment by yye824** [comment]
@xdd666t 感谢大神回复 暂时用原生的处理了 部分使用了这个 感谢
