### ISSUE TITLE
能不能同时存在多个实例

### ISSUE THREAD

**Issue by guotao** [fluttercandies/flutter_smart_dialog#8]
比如我通过 SmartDiaload。showLoading（） 弹loading的toast 的时候，如果再Smartdialog。show（）弹出底部浮层，loadig
toast就会消失。即使没有调用 dismiss（），谢谢。

**Comment by guotao** [comment]
说错了，实际场景是：通过Smartdialog。show（）弹出一个弹窗提示，再Smartdialog。show（）弹出底部Dialog浮层，这时弹窗就会消失。两个无法并存。

**Comment by CNAD666** [comment]
这边不考虑开额外浮层

- 开一个额外OverlayEntry对用户操作都会造成很大麻烦
- 关闭的方法就需要增加额外type类型
- 实际上show，showLoading，showToast都是单独的OverlayEntry

有俩个方法可以解决你的问题

> **SmartDialog**

SmartDialog里面有个SmartDialog.showLoading，里面有个widget参数，可以自定义你的布局，曲线救国

```dart
///关闭Dialog
///
/// closeType：关闭类型
///
/// 0：关闭主体OverlayEntry和loading
/// 1：仅关闭主体OverlayEntry
/// 2：仅关闭Toast
/// 3：仅关闭loading
/// 4：都关闭
SmartDialog.dismiss(closeType: 3)
```

> **系统弹窗**

系统弹窗和SmartDialog配合使用

**Comment by guotao** [comment]
> 这边不考虑开额外浮层
> 
> * 开一个额外OverlayEntry对用户操作都会造成很大麻烦
> * 关闭的方法就需要增加额外type类型
> * 实际上show，showLoading，showToast都是单独的OverlayEntry
> 
> 有俩个方法可以解决你的问题
> 
> > **SmartDialog**
> 
> SmartDialog里面有个SmartDialog.showLoading，里面有个widget参数，可以自定义你的布局，曲线救国
> 
> ```dart
> ///关闭Dialog
> ///
> /// closeType：关闭类型
> ///
> /// 0：关闭主体OverlayEntry和loading
> /// 1：仅关闭主体OverlayEntry
> /// 2：仅关闭Toast
> /// 3：仅关闭loading
> /// 4：都关闭
> SmartDialog.dismiss(closeType: 3)
> ```
> 
> > **系统弹窗**
> 
> 系统弹窗和SmartDialog配合使用

要实现类似微信里全屏查看图片，长按弹出底部菜单的效果，看来只能用系统弹窗配合Smart Dialog了。因为showLoading 还带有特殊的动画，而且层级高过了show的弹层。

**Comment by CNAD666** [comment]
Toast最上层，Loading中间，show在下层；这个没办法，按照显示的优先级，必要这样做

**Comment by guotao** [comment]
> Toast最上层，Loading中间，show在下层；这个没办法，按照显示的优先级，必要这样做

这可以理解，

我在想有没有可能show和dismiss方法传入一个可选参数id，dismiss传入id的话，仅关闭对应的弹层，这样能应对的场景多很多。

**Comment by CNAD666** [comment]
> > Toast最上层，Loading中间，show在下层；这个没办法，按照显示的优先级，必要这样做
> 
> 这可以理解，
> 
> 我在想有没有可能show和dismiss方法传入一个可选参数id，dismiss传入id的话，仅关闭对应的弹层，这样能应对的场景多很多。

这个我会考虑，这个issue先开着；最近比较忙，回头有结果了，会在这里告诉你

**Comment by xdd666t** [comment]
重构已完成，这是文档：https://juejin.cn/post/7026150456673959943

**Comment by xlfdyzcs** [comment]
> Toast最上层，Loading中间，show在下层；这个没办法，按照显示的优先级，必要这样做

show层本身，有可能再细分层么？比如，AB两个依次show被显示后，B会在A上方，有没有一种方法或配置，指定A显示在B上方，而不管AB被显示出来时候的顺序。感谢da'yi

**Comment by xdd666t** [comment]
> > Toast最上层，Loading中间，show在下层；这个没办法，按照显示的优先级，必要这样做
> 
> show层本身，有可能再细分层么？比如，AB两个show依次被显示后，B会在A上方，有没有一种方法或配置，指定A显示在B上方，而不管AB被显示出来时候的顺序。感谢答疑

目前来说使用useSystem为true的弹窗，都在useSystem为false底下

**Comment by xlfdyzcs** [comment]
> > > Toast最上层，Loading中间，show在下层；这个没办法，按照显示的优先级，必要这样做
> > 
> > 
> > show层本身，有可能再细分层么？比如，AB两个show依次被显示后，B会在A上方，有没有一种方法或配置，指定A显示在B上方，而不管AB被显示出来时候的顺序。感谢答疑
> 
> 目前来说使用useSystem为true的弹窗，都在useSystem为false底下

有可能新增一个这样的功能么(仅在show层)：为弹窗新增一个参数 int priority，通过修改该参数，从而达到精细化指定(修改：已经显示了三个弹窗，想把第一个弹窗显示在最上层或者中间)多个弹窗的层级

**Comment by xdd666t** [comment]
@xlfdyzcs 这个你重新开个issue吧，把需求细节描述的详细点
