### ISSUE TITLE
如何禁用 Android 返回键

### ISSUE THREAD

**Issue by neverlist** [fluttercandies/flutter_smart_dialog#80]
### 版本信息
- Flutter版本：3.3.1
- flutter_smart_dialog版本：^4.5.5+3

### 描述bug/需求
如何禁用 Android 返回键   本来以为是设置 backDismiss 为false 但无效

**Comment by neverlist** [comment]
我知道了，useSystem为true时好像不能和 backDismiss  共用 目前我的解决方法 是在 builder的container外再套一层 WillPopScope(
            onWillPop: () async => false,

**Comment by xdd666t** [comment]
回头加下用useSystem的时候把backDismiss禁掉

目前的SmartDialog的功能基本能覆盖useSystem的功能，如果非必须，还是不要开始useSystem属性吧，使用这个属性，KeepSingle，tag，permanent，backDismiss都会有非预期表现

**Comment by neverlist** [comment]
useSystem 为 false 时 跳转页面时 dialog会短暂的消失 然后再打开页面 true就没这个问题

**Comment by xdd666t** [comment]
这个是特地写的特性，跨页面的交互表现
- 跨页面的交互确实没有开发useSystem的丝滑（useSystem就是用的flutter的dialog）

如果你觉得SmartDialog跨页面交互效果不佳，可以使用useSystem哈

**Comment by neverlist** [comment]
好的，谢谢

**Comment by xdd666t** [comment]
这个问题，我查看了下对返回事件的处理，对useSystem状态的拦截欠妥，算是个bug，已经修改了
- 你可以更新下版本试试，新版本backDismiss同样对useSystem弹窗生效

```dart
dependencies:
  flutter_smart_dialog: ^4.5.5+5
```
