### ISSUE TITLE
SmartDialog.show之后，调用showModalBottomSheet，会使弹窗消失

### ISSUE THREAD

**Issue by wudb** [fluttercandies/flutter_smart_dialog#81]
### 版本信息
- Flutter版本：[v3.3.4]
- flutter_smart_dialog版本：[v4.6.1]

### 描述bug/需求
我用SmartDialog.show弹出了一个弹框，并且需要开启可穿透，然后再点击另一个按钮调用showModalBottomSheet显示bottom sheet，这时候弹窗会消失，关掉bottom sheet，弹窗又显示出来了。
另：因为我开启了permanent(需要关不掉)，退回上级界面后再回到此界面，然后显示bottom sheet，弹窗就不会消失了

**Comment by wudb** [comment]
SmartDialog.show(builder: (ctx) {
      return CallPage(toUserInfo: toUserInfo, callType: type);
    },
      useAnimation: false,
      usePenetrate: true,
      clickMaskDismiss: false,
      keepSingle: true,
      permanent: true,
      debounce: true,
      alignment: Alignment.centerRight,
    );
  }
弹窗代码如上

**Comment by xdd666t** [comment]
这确实是个bug，设置了permanent参数，变换路由的时候，不应该隐藏弹窗

- 已经解决了，升级下版本吧

```dart
dependencies:
  flutter_smart_dialog: ^4.6.1+1
```

debounce这种参数有全局配置，全局配置下就行了，不用每次都是设置哈

**Comment by wudb** [comment]
谢谢！问题解决。这几天github打不开，囧
