### ISSUE TITLE
SmartDialog.showAttach() 里无法使用 PageStorage.of(context)

### ISSUE THREAD

**Issue by wh19990906** [fluttercandies/flutter_smart_dialog#83]
### 版本信息
- Flutter版本：[举例：v2.10.4]
- flutter_smart_dialog版本：[举例：v3.4.1]

### 描述bug/需求
问题：SmartDialog.showAttach() 里使用 打开StatefulWidget，在打开的页面中无法获取PageStorage.of(context)

需求：使用官方ShowDialog是可以的，SmartDialog.showAttach可不以传入context

**Comment by wh19990906** [comment]
`SmartDialog.showAttach(
      targetContext: state.globalKey.currentContext,
      highlightBuilder: (Offset targetOffset, Size targetSize) {
        return Positioned(
          top: 0,
          child: Container(
            width: targetSize.width,
            height: targetSize.height,
            color: Colors.white,
          ),
        );
      },
      builder: (_) {
        return const Demo();
      },
    );`



`import 'package:flutter/material.dart';

class Demo extends StatefulWidget {
  const Demo({Key? key}) : super(key: key);

  @override
  _DemoState createState() => _DemoState();
}

class _DemoState extends State<Demo> {
  @override
  void initState() {
    super.initState();

    Future.delayed(const Duration(seconds: 0)).then((value) {
      PageStorageBucket? pageStorageBucket = PageStorage.of(context);
      debugPrint(pageStorageBucket == null ? "yes" : "no");
      var readState = pageStorageBucket?.readState(context);
      debugPrint(readState == null ? "yes" : "no");
    });
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 100,
      height: 100,
      color: Colors.red,
    );
  }
}
`

**Comment by wh19990906** [comment]
`import 'package:flutter/material.dart';

class Demo extends StatefulWidget {
  const Demo({Key? key}) : super(key: key);

  @override
  _DemoState createState() => _DemoState();
}

class _DemoState extends State<Demo> {
  @override
  void initState() {
    super.initState();

    Future.delayed(const Duration(seconds: 0)).then((value) {
      PageStorageBucket? pageStorageBucket = PageStorage.of(context);
      debugPrint(pageStorageBucket == null ? "yes" : "no");
      var readState = pageStorageBucket?.readState(context);
      debugPrint(readState == null ? "yes" : "no");
    });
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 100,
      height: 100,
      color: Colors.red,
    );
  }
}
`

**Comment by wh19990906** [comment]
在打开的页面中获取不到PageStore.of(context)，控制台输出了两个yes

**Comment by xdd666t** [comment]
你把页面上使用PageStorage的简化demo也写下吧

**Comment by wh19990906** [comment]
这个是Azlistview报的错

scrollable_positioned_list.dart

<img width="787" alt="image" src="https://user-images.githubusercontent.com/37242815/197983204-6b788d82-b0f5-40ec-81dd-85fd8bce0186.png">

错误就在277这一行

**Comment by xdd666t** [comment]
useSystem设置为true，试下看看

这个我之前也试过，useSystem设置为true就可以正常使用azlist，如果你试了不行，看看能不能给下你那边能复现的简化demo

**Comment by wh19990906** [comment]
可以了，useSystem设置为true可以正常使用azlist

**Comment by wh19990906** [comment]
感谢作者👍！！！
好用的插件点下Star！！！
