### ISSUE TITLE
 键盘弹出的时候toast不显示

### ISSUE THREAD

**Issue by hukejia** [fluttercandies/flutter_smart_dialog#84]
4.6.1 版本，使用默认toast，键盘弹出的时候不显示

SmartDialog.showToast(text,alignment: Alignment.topCenter,displayType: SmartToastType.last);

**Comment by xdd666t** [comment]
这个确实有问题，目前看来是SmartToastType.last导致的，使用默认的normal类型不会有问题

- 如果问题修复了，会在这个issue告知下你

**Comment by hukejia** [comment]
> 这个确实有问题，目前看来是SmartToastType.last导致的，使用默认的normal类型不会有问题
> 
> * 如果问题修复了，会在这个issue告知下你

使用normal一样有问题

**Comment by xdd666t** [comment]
- 更新版本再试试吧

```dart
dependencies:
  flutter_smart_dialog: ^4.6.2
```

**Comment by hukejia** [comment]
> 

可以了

**Comment by xdd666t** [comment]
看你使用alignment属性，可能是想改变toast的位置

- 目前默认toast的位置是写死，不支持定制
- 建议你配置全局自定义toast样式，可参考：https://github.com/fluttercandies/flutter_smart_dialog/issues/24
