### ISSUE TITLE
Not Working in web with release mode in docker container

### ISSUE THREAD

**Issue by JaehoonHyun** [fluttercandies/flutter_smart_dialog#85]
### Version Information
- Flutter version: 
Flutter 3.3.6 • channel stable • https://github.com/flutter/flutter.git 
Framework • revision 6928314d50 (5 days ago) • 2022-10-25 16:34:41 -0400 
Engine • revision 3ad69d7be3 
Tools • Dart 2.18.2 • DevTools 2.15.0 

- flutter_smart_dialog version: 4.6.2

### Describe the bug/requirement
Please describe the bug or requirement accurately

### Problem demo
<!-- Provide the simplest demo (executable main file) that can reproduce the problem, which can save a lot of communication time, and can quickly locate and solve the problem -

->
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/10256916/198889916-f8c3b2f8-2316-4f39-86fa-7972d17aefde.png">

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/10256916/198889881-38c16ae9-9b31-4a59-99e2-886f9794d043.png">

It is working on localhost, but I think it is not working in release mode of web.
Could you check this??!

Thanks!

**Comment by JaehoonHyun** [comment]
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/10256916/198889928-69b4f659-34af-470c-a827-8ca9155825d1.png">

**Comment by JaehoonHyun** [comment]
it just happend on release build and run

**Comment by JaehoonHyun** [comment]
`flutter run -d chrome ` command , it works. but flutter build is not working... :(

**Comment by xdd666t** [comment]
Can you provide a simplified demo that can reproduce the problem?

**Comment by JaehoonHyun** [comment]
Oh I figure out. This is my problem.
I used Column Widget in Expanded Widget. :)
THX!!
