### ISSUE TITLE
使用Get导航时不显示

### ISSUE THREAD

**Issue by WGHADWR** [fluttercandies/flutter_smart_dialog#87]
### 版本信息
- Flutter版本：3.3
- flutter_smart_dialog版本：4.6.2+1

### 描述bug/需求
使用Get导航时，showToast不显示（其他也不显示）
使用Navigator导航可以显示

### 问题demo
```dart
Get.to(() => const NewPage());
```

#### NewPage
```dart
Future<void> save() async {
    await SmartDialog.showToast('test');
}
```

**Comment by xdd666t** [comment]
- 我这边试了，没浮现你说的情况，给个可复现的demo？

```dart
SmartDialog.showToast('test toast');
await Future.delayed(const Duration(milliseconds: 200));
Get.to(() => const Scaffold(body: Center(child: Text("111111"))));
```

https://user-images.githubusercontent.com/35656085/199990455-8aee21cd-3b4c-4ea8-800a-fb6a0b01275f.mp4

**Comment by WGHADWR** [comment]
### Demo

`import 'package:flutter/material.dart';
import 'package:flutter_smart_dialog/flutter_smart_dialog.dart';
import 'package:get/get.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const GetMaterialApp(home: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      navigatorObservers: [FlutterSmartDialog.observer],
      builder: FlutterSmartDialog.init(),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  void nav() {
    Get.to(() => const SecondPage());
    // Navigator.push(context, MaterialPageRoute(builder: (_) => const SecondPage()));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: ElevatedButton(onPressed: () => nav(), child: const Text('Open SecondPage')),
    );
  }
}

class SecondPage extends StatelessWidget {
  const SecondPage({super.key});

  void open() {
    SmartDialog.showToast('test');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('SecondPage'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(onPressed: () => open(), child: Text('Open Toast'))
          ],
        ),
      ),
    );
  }
}

`

**Comment by xdd666t** [comment]
麻了，你初始化的时候，不要用GetMaterialApp盖住MaterialApp

- 你这样搞，会导致Get打开的路由盖住MaterialApp之上
- 然后，SmartDialog又在MaterialApp中初始化的，导致Get的路由盖住了SmartDialog

你按照图上标的初始化吧

![image](https://user-images.githubusercontent.com/35656085/200217889-8e5f9be9-cb76-464b-8136-0add9c9c8255.png)

**Comment by WGHADWR** [comment]
好的，解决了，谢谢
