### ISSUE TITLE
Toast 优化点

### ISSUE THREAD

**Issue by wenchaosong** [fluttercandies/flutter_smart_dialog#88]
### 版本信息
- Flutter版本：3.3.4
- flutter_smart_dialog版本：flutter_smart_dialog: ^4.6.2+1

### 描述bug/需求
Toast 问题
有个场景是右侧字母索引, 快速滑动后显示 toast, 需求是要每次滑动都要快速显示, 并且停止后 toast 消失

**Comment by xdd666t** [comment]
你这种场景可以使用功能SmartDialog.show去自定义下弹窗就行了，感觉和toast关系不大

- usePenetrate：可以穿透遮罩，让你滑动列表
- controller：该参数可以让你在外部刷新内部数据

**Comment by wenchaosong** [comment]
@xdd666t  我是说的 toast ,不是弹窗
左侧是显示你的 toast, 右侧是显示我自定义的 toast, 鼠标滑动或者手指触摸滑动会提示 Y 坐标距离

![GIF](https://user-images.githubusercontent.com/16938075/199689592-f2ae083d-c3cb-4649-aefc-8e06feb15555.gif)

**Comment by xdd666t** [comment]
我是说你这个场景可以用dialog实现

- 你如果非得在意toast这种形式，也可以稍微自定下
  - toast显示时间设置足够的大
  - 使用toast创建你的自定义布局，传入数据变量；改变数据变量的时候，使用toast中的controller刷新

**Comment by xdd666t** [comment]
我明白你的意思，你是想连续调用toast，只更新toast的文字

但是感觉这种方式和android的这类toast的形式区别就有点大佬

**Comment by wenchaosong** [comment]
在 android 中同样需要 连续调用 toast, 快速显示文字

我一开始说的  右侧城市导航栏, 联系人列表, 点击或者滑动可以显示字母 这个就是实实在在的需求

我以为你会问我 右侧的 自定义 toast 怎么实现, 但是你说用 dialog 实现, 那你定义 toast 方法的意义是什么

用 dialog 实现还要设置去掉阴影等一些多余操作, 为啥不能直接用 toast 呢

**Comment by xdd666t** [comment]
目前displayType的api扩展留出来了，这个我记个todo吧，周末的时候弄下

**Comment by xdd666t** [comment]
- 这个功能加上了，更新下版本吧

```dart
dependencies:
  flutter_smart_dialog: ^4.7.0
```

- 使用

```dart
for (var i = 0; i < 7; i++) {
  SmartDialog.showToast('test toast ---- $i', displayType: SmartToastType.onlyRefresh);
  await Future.delayed(Duration(milliseconds: 500));
}
```
