### ISSUE TITLE
结合Flutter_boost，showLoading 未屏蔽返回键

### ISSUE THREAD

**Issue by i-farmer** [fluttercandies/flutter_smart_dialog#89]
### 版本信息
- Flutter版本：3.3.1
- flutter_smart_dialog版本：4.6.2+1

### 描述bug/需求
结合fluttter_boost，打开flutter页面，请求数据，使用 SmartDialog.showLoading(backDismiss: false)，在未完成请求之前，点击物理键返回，可以直接返回，没有拦截

### 问题demo

```dart
  Widget _appBuilder(Widget home) {
    var initSmartDialog = FlutterSmartDialog.init(
      loadingBuilder: (msg) => CustomLoadingDialog(msg),
    );
    return MaterialApp(
      home: home,
      debugShowCheckedModeBanner: false,
      theme: AppStyles.appTheme,

      navigatorObservers: [FlutterSmartDialog.observer],

      /// 必须加上builder参数，否则showDialog等会出问题
      builder: (context, _) => initSmartDialog(context, home),
    );
  }

  @override
  Widget build(BuildContext context) {
    return FlutterBoostApp(
      _routeFactory,
      appBuilder: _appBuilder,
    );
  }
```

**Comment by xdd666t** [comment]
初始化操作需要放在APPBuilder外
- 参考下使用说明吧：https://github.com/fluttercandies/flutter_smart_dialog/issues/89

**Comment by i-farmer** [comment]
这个只是写法不一样，结果是一样的啊。即使按你的写法，还是不能拦截返回键

**Comment by xdd666t** [comment]
这种写法是为了确保SmartDialog的手势拦截处于拦截链的最上游，我之前试了是可以的

- 你这边还是不行，提供下可复现问题的简化demo吧

**Comment by i-farmer** [comment]
就我提问题的那段代码，没有其他的东西，然后页面是android那边打开的，进入页面就用dio做了一次请求（当然你可以直接showloading，然后看看是不是直接就返回了）

**Comment by xdd666t** [comment]
你连可复现问题的demo都懒得弄，你让我怎么有动力去帮你解决这个问题

- 一个是，这个问题，之前有人反馈过，我这边建了复现demo，使用这种初始化方式没有问题
- 另一个是，简化问题demo，可以排除是不是其它东西的干扰

**Comment by i-farmer** [comment]
我现在去弄，我的错

**Comment by i-farmer** [comment]
## main.dart 文件
import 'package:flutter/material.dart';
import 'package:flutter_boost/flutter_boost.dart';
import 'package:flutter_smart_dialog/flutter_smart_dialog.dart';

import 'test_page.dart';

void main() {
  //用于控制Boost状态的resume和pause
  MyFlutterBinding();
  runApp(const MyApp());
}

class MyFlutterBinding extends WidgetsFlutterBinding with BoostFlutterBinding {}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  /// 路由工厂
  Route<dynamic>? _routeFactory(RouteSettings settings, String? uniqueId) {
    // 如果需要更多配置，可修改 router_model.dart增加属性
    return MaterialPageRoute(
        settings: settings,
        builder: (_) {
          return const TestPage();
        });
  }

  @override
  Widget build(BuildContext context) {
    var initSmartDialog = FlutterSmartDialog.init();
    return FlutterBoostApp(
      _routeFactory,
      appBuilder: (Widget home) {
        return MaterialApp(
          home: home,
          debugShowCheckedModeBanner: true,
          //here
          navigatorObservers: [FlutterSmartDialog.observer],
          //here
          builder: (context, child) => initSmartDialog(context, home),
        );
      },
    );
  }
}

## test_page.dart 文件
import 'package:flutter/material.dart';
import 'package:flutter_smart_dialog/flutter_smart_dialog.dart';

class TestPage extends StatelessWidget {
  const TestPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    SmartDialog.showLoading(backDismiss: false);
    return Container(
      decoration: const BoxDecoration(color: Colors.amberAccent),
    );
  }
}

## android 点击跳转事件
FlutterBoostRouteOptions options = new FlutterBoostRouteOptions.Builder()
                    .pageName("/page/test")
                    .build();
            FlutterBoost.instance().open(options);

**Comment by xdd666t** [comment]
我用你的代码：可以拦截返回事件，我debug了代码，也监听到了返回事件进行拦截

https://user-images.githubusercontent.com/35656085/199973259-b467edde-8066-4161-bade-e81a22743aea.mp4

**Comment by i-farmer** [comment]
https://user-images.githubusercontent.com/17808903/200001758-92c37480-75d4-4ed5-8fdf-fa756c0cfce2.mp4

**Comment by i-farmer** [comment]
[demo.zip](https://github.com/fluttercandies/flutter_smart_dialog/files/9939287/demo.zip)
整个demo文件，你试试，我用的是最新的gradle版本，白天用的是红米note7，android 7还是8吧；晚上用的是华为p40pro

**Comment by xdd666t** [comment]
- flutter_boost的对路由的处理着实很奇葩，全局监听pop事件失效，路由监听也失效
  - 我们内部也是混合框架，路由监听和全局监听事件都很正常
  - 这边采取一种曲线方式监听了willPop事件，但是路由监听实在没辙，flutter_boost对路由的处理也没抛出来，功能存在一定程度的阉割
- 采用新的初始化方式，路由监听不用写了，也没法监听到
  - 注意，这边需要跳转flutter路由，必须使用flutter_boost这套，路由需要写在routerMap中
  - 如果有弹窗有跨页面操作交互，请使用SmartDialog的useSystem参数（bindPage参数在无法监听路由的情况下会失效）

```dart
void main() {
  MyFlutterBinding();
  runApp(const MyApp());
}

class MyFlutterBinding extends WidgetsFlutterBinding with BoostFlutterBinding {}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static Map<String, FlutterBoostRouteFactory> routerMap = {
    '/page/test': (settings, uniqueId) {
      return MaterialPageRoute(settings: settings, builder: (_) => const TestPage());
    },
  };

  Route<dynamic>? _routeFactory(RouteSettings settings, String? uniqueId) {
    var func = routerMap[settings.name!];
    // here
    return FlutterSmartDialog.boostMonitor(func?.call(settings, uniqueId));
  }

  @override
  Widget build(BuildContext context) {
    var initSmartDialog = FlutterSmartDialog.init();
    return FlutterBoostApp(
      _routeFactory,
      appBuilder: (Widget home) {
        return MaterialApp(
          home: home,
          debugShowCheckedModeBanner: true,
          //here
          builder: (context, child) => initSmartDialog(context, home),
        );
      },
    );
  }
}
```

**Comment by i-farmer** [comment]
好的，谢谢
