### ISSUE TITLE
使用Devtools 选择selectWidget Mode出现异常

### ISSUE THREAD

**Issue by Unicorn254** [fluttercandies/flutter_smart_dialog#9]
Failed assertion: line 370 pos 7: 'entries.every((OverlayEntry entry) => entry._overlay == null)'

**Comment by CNAD666** [comment]
我的源码里面好像没这个代码呀？？？

你确定是这个框架的问题？

**Comment by CNAD666** [comment]
先关了，有问题再提，提的时候最好能给出更加详细的错误说明
