### ISSUE TITLE
SmartDialog.showAttach 增加对齐位置的选项，而不是默认中心对齐。

### ISSUE THREAD

**Issue by leavky** [fluttercandies/flutter_smart_dialog#90]
### 版本信息
- Flutter版本：3
- flutter_smart_dialog版本：4.5.5+6

### 需求
非常感觉作者这个功能强大的包。希望 SmartDialog.showAttach 实现下拉按钮的时候，希望增加左对齐的选项，而不是默认中心对齐。在web与桌面上，按钮通常都是左对齐的，虽然可以通过自定义位置计算得到，但显得繁琐。在桌面上通常是这样子的，
![image](https://user-images.githubusercontent.com/46547390/200987021-b2007805-08f1-46cd-bc43-c5eb2a14000c.png)
希望可以增加一个参数，指定对齐位置。

**Comment by xdd666t** [comment]
- 这个加上了，更新下版本吧

```dart
dependencies:
  flutter_smart_dialog: ^4.7.1
```

- 使用，这边是配置在attach全局属性内，你可以调整下

```dart
SmartDialog.config
  ..custom = SmartConfigCustom()
  ..attach = SmartConfigAttach(
    attachAlignmentType: SmartAttachAlignmentType.inside,
  )
  ..loading = SmartConfigLoading()
  ..toast = SmartConfigToast();
```

- 效果地址：https://xdd666t.github.io/flutter_use/web/index.html#/smartDialog

![image](https://user-images.githubusercontent.com/35656085/201465716-cdf89ffd-efd9-48c7-af20-9854b0b5d5de.png)

**Comment by leavky** [comment]
好的，谢谢修改，祝您生活愉快。
