### ISSUE TITLE
toast 没有 error primary

### ISSUE THREAD

**Issue by front-ck996** [fluttercandies/flutter_smart_dialog#91]
### 描述bug/需求
toast 不是应该提供几种模式 primary warninfo error 
或者提供 fontColor 和 fillColor

**Comment by xdd666t** [comment]
目前提供的是底层基础能力，这类样式方面的请使用builder参数去自定义吧

或者，你需要配置自定义的统一样式，可参考：https://github.com/fluttercandies/flutter_smart_dialog/issues/24

**Comment by front-ck996** [comment]
好的感谢，
