### ISSUE TITLE
SmartDialog.showToast('the toast at the center', alignment: Alignment.center); 对齐方式无效

### ISSUE THREAD

**Issue by shang1219178163** [fluttercandies/flutter_smart_dialog#92]
<img width="452" alt="截屏2022-11-16 14 39 18" src="https://user-images.githubusercontent.com/3699729/202103738-35314d8a-4ce8-44e9-943a-cf244836dbc5.png">
### 版本信息
- Flutter版本：v2.8.0
- flutter_smart_dialog版本：  flutter_smart_dialog: ^4.2.0

### 描述bug/需求

SmartDialog.showToast('the toast at the center', alignment: Alignment.center);

仍显示在底部，没有居中显示；

**Comment by xdd666t** [comment]
升级最新版本吧

**Comment by xdd666t** [comment]
- 实现这个版本
```dart
dependencies:
  flutter_smart_dialog: ^4.2.1
```

**Comment by shang1219178163** [comment]
可以了
