### ISSUE TITLE
建议：添加一个属性（布尔值），用于判断当前页面上是否正在显示弹窗

### ISSUE THREAD

**Issue by shang1219178163** [fluttercandies/flutter_smart_dialog#93]

**Comment by xdd666t** [comment]
描叙下具体的业务场景？

**Comment by shang1219178163** [comment]
如果页面正在弹窗，我可能需要立即关闭这个弹窗换个弹窗，也可能等这个弹窗完成再进行下一个。用于某个页面多个请求连续触发的情况。

**Comment by xdd666t** [comment]
- 前面这种关闭弹窗再打开，感觉你可以使用功能keepSingle参数解决
- 后面这种，你可以等前一个弹窗关闭之后（onDismiss回调监听）再进行后面网络请求

**Comment by xdd666t** [comment]
看起来你说的场景，现有功能能够覆盖

这个issue先关了，如果有现有功能不能覆盖的场景，需要新的功能，再提吧
