### ISSUE TITLE
release包,点击遮罩关闭弹窗报错

### ISSUE THREAD

**Issue by wh19990906** [fluttercandies/flutter_smart_dialog#94]
### Version Information
- Flutter version: [e.g. v3.3.2]
- flutter_smart_dialog version: [e.g. v4.6.2]

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'FutureOr<WardEntity>'
    #0      _AsyncCompleter.complete (dart:async/future_impl.dart:36)
    #1      MainDialog._handleAwaitOver (package:flutter_smart_dialog/src/custom/main_dialog.dart:183)
    #2      MainDialog.dismiss (package:flutter_smart_dialog/src/custom/main_dialog.dart:207)
    <asynchronous suspension>
    #3      CustomDialog._closeSingle (package:flutter_smart_dialog/src/custom/custom_dialog.dart:395)
    <asynchronous suspension>

**Comment by xdd666t** [comment]
- 你是不是在使用的时候加上了泛型，类似这样的

```dart
SmartDialog.show<String>(builder: (_) {
  return Container(
    height: 80,
    width: 180,
    color: Colors.black,
  );
});
```

- 你可以把泛型去掉，不会有影响；或者像下面这样，设置为可控

```
SmartDialog.show<String?>(builder: (_) {
  return Container(
    height: 80,
    width: 180,
    color: Colors.black,
  );
});
```

**Comment by wh19990906** [comment]
- 泛型设置为可空是可行的

SmartDialog.show<String?>(builder: (_) {
  return Container(
    height: 80,
    width: 180,
    color: Colors.black,
  );
});
