### ISSUE TITLE
弹窗不会出现

### ISSUE THREAD

**Issue by chengfan2017** [fluttercandies/flutter_smart_dialog#96]
### 版本信息
- Flutter版本：2.19.0
- flutter_smart_dialog版本：^4.5.3+6

### 描述bug/需求

就是点击按钮 显示弹窗-》网络请求数据》关闭弹窗，但是弹窗不会出现

### 问题demo
![image](https://user-images.githubusercontent.com/19389193/206084021-dfbcf2ed-34b3-448c-8c58-1fbd288bc49f.png)
![image](https://user-images.githubusercontent.com/19389193/206084048-afcb72a5-7354-49d2-9f6a-c6c583e5b70a.png)

**Comment by chengfan2017** [comment]
![image](https://user-images.githubusercontent.com/19389193/206084198-2d850f8b-f129-4339-8cae-07d1bde7172a.png)

**Comment by chengfan2017** [comment]
showLoading 执行了，但是没有显示

**Comment by xdd666t** [comment]
给个可复现的demo吧；这种情况按理来说不太可能存在，如果这是必现情况，应该会有很多人提

**Comment by chengfan2017** [comment]
![image](https://user-images.githubusercontent.com/19389193/206090696-4ee6ecc9-3aba-4b9d-894c-2757d70d4282.png)
请问 为什么用注释的那行耗时代码，就有问题，这种就没有问题

**Comment by chengfan2017** [comment]
![image](https://user-images.githubusercontent.com/19389193/206090854-2dd89ac3-b76e-4572-b5ff-86e31f83503f.png)
请问大佬，为什么用注释的那行耗时代码就有问题，使用下面那行代码就正常显示弹窗，不都一样吗

**Comment by xdd666t** [comment]
有没有一种可能：计算耗时太短，你还没反应过来，弹窗就被关掉了

**Comment by chengfan2017** [comment]
不会，第三张截图是有计时，7秒

**Comment by chengfan2017** [comment]
第三张截图计时了，11秒

**Comment by xdd666t** [comment]
我觉得你还是给个可复现且可执行的main文件代码，这样凭借几张代码都不全的图，讨论没啥意义

**Comment by chengfan2017** [comment]
我加你微信吧
