### ISSUE TITLE
初始化错误

### ISSUE THREAD

**Issue by sdjwj1118** [fluttercandies/flutter_smart_dialog#97]
### 版本信息
- Flutter版本：[举例：v3.3.8]
- flutter_smart_dialog版本：[举例：v4.7.1]

### 描述bug/需求
请准确描述bug或需求
在mian函数初始化smartdialog，当我的child是StatefulWidget的时候 我在initstate调用打开一个自定义弹框之前会报LateInitializationError: Field 'contextOverlay' has not been initialized，如果换成StatelessWidget通过点击事件去触发就不会报错。如图，myapp里第一个页面是loginbycode页面，在这个页面initstate方法里我执行了confirmDialog方法，弹框也能正常显示但是在显示前会先报错

### 问题demo

![image](https://user-images.githubusercontent.com/33438073/206914347-a630e60d-5b78-4b62-a266-85fd2609ba13.png)
![image](https://user-images.githubusercontent.com/33438073/206914353-e7594a66-1f45-49d3-bd8f-120769467aba.png)
![image](https://user-images.githubusercontent.com/33438073/206914362-89b54a9b-c41a-4c76-9639-903f3a54028e.png)

**Comment by xdd666t** [comment]
我会在打开页面第一帧刷新后获取到context去插入OverlayEntry，你这用法是放在第一个页面的initState中，导致context没拿到
- 第一个页面的initState要这样写，后面的页面就可以随便写了
![image](https://user-images.githubusercontent.com/35656085/206977830-ebfead05-95ab-4b59-bfda-fe9a26c71576.png)

- 而且你这个初始化有点奇怪，你为啥要把初始化放在builder里？你这样写可能会导致无法监听返回事件
![image](https://user-images.githubusercontent.com/35656085/206978087-e7422010-0355-4372-906c-26906cfc3e82.png)

**Comment by sdjwj1118** [comment]
这个初始化是参照一个issues来写的

**Comment by xdd666t** [comment]
如果你能正常使用，返回事件没问题，你就保持当前初始化吧

- 还有有没有尝试上面贴的写法？

**Comment by xdd666t** [comment]
这个先关了，上面给的方案，应该能解决你的问题

- 如果还有问题，请给个完整可执行的main，重新开个issue
